### ISSUE TITLE
Example of custom filter function for a Node Filterset 

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#1]
Awesome work guys really love this project!

I'm trying to do something that hasn't been documented yet and was hoping I could ask for some insight.

I have a simple node class that has a filterset for it with a custom filter function

    class BuildingNode(DjangoObjectType):
        class Meta:
            interfaces = (Node, )
            model = Buildings

     class BuildingFilter(django_filters.FilterSet):
         full_address = django_filters.MethodFilter()

        def filter_full_address(self, queryset, value):
            if value:
                   return querset.filter(#special_filter_case)
            return queryset

        class Meta:
             model = Buildings
             fields = {
                'address__route': ['exact', 'icontains'],
             } 

Everything filters fine on http://localhost:8000/graphiql

But on my frontend when I filter by my custom function I get warnings that look like this

`Attempted to add noncontiguous index to GraphQLSegment: 12 to (0, 10)`
`Attempted to add noncontiguous index to GraphQLSegment: 13 to (0, 10)`
`Attempted to add an ID already in GraphQLSegment: client:client:-18995767902:QnVpbGRpbmdOb2RlOjMzNjkxMGFlLTY5YzQtNDU5My1iMjliLTZiNjQ5NjY0MjQyNg==`

But when I filter by address__route these errors never appear.

I looked through django_graphene and couldn't find any clues on what I need to do to resolve these warnings. I'm guessing I need to wrap my queryset with something. 

It would be awesome to see how to do this in the cookbook example!

**Comment by syrusakbary** [comment]
Hi @BossGrand,

I added this to the documentation!
https://github.com/graphql-python/graphene-django/blob/master/docs/filtering.rst#custom-filtersets

(Closing the issue, feel free to reopen if doesn't work or something is not clear)

**Comment by BossGrand** [comment]
Thanks for responing @syrusakbary 

I think I may of been unclear I'm interested in knowing if there is something extra I have to do to make a 

 `django_filters.MethodFilter`

to work. Because when I do the one I have implemented above it gives me the errors I've stated. I can't reopen the issue because I wasn't the one to close it. Thanks again!

**Comment by BossGrand** [comment]
Based on the errors I'm guessing its something to do with not preserving the order, but I'm at a lost. I spent a few hours yesterday messing around with GrapheneFiltersets to try and see if I could find any clues

**Comment by BossGrand** [comment]
So turns out the warnings were caused by my filter function working improperly. I was returning duplicate models which was throwing those errors. 

I added distinct() to my querset calls and it works beautifully
