### ISSUE TITLE
GraphiQL not working in v2.12.0

### ISSUE THREAD

**Issue by grebsai** [graphql-python/graphene-django#1003]
* **What is the current behavior?**
  
In version v2.12.0 the GraphiQL playground no longer works. I always get the error `Cannot read property '1' of null` in my response. In version v2.11.1 everything works fine.

![nicememe ZbVai8zFifldc0UdeSZ](https://user-images.githubusercontent.com/17954650/87336205-c5c83580-c541-11ea-99bc-89dbb4d9fb31.png)

* **Please tell us about your environment:**
  
  - Version: graphene-django v2.12.0; graphene v2.1.8
  - Platform: Linux Ubuntu 20.04

**Comment by jkimbo** [comment]
I can reproduce this issue. Looking into it now.

**Comment by eabruzzese** [comment]
@grebsai As a quick workaround, give your query a name:

```graphql
query MyQuery {
  allNames {
    id
    title
  }
}
```

I'll fix this shortly.
