### ISSUE TITLE
Q: Mutation for file upload

### ISSUE THREAD

**Issue by creimers** [graphql-python/graphene-django#101]
Is there an example for graphene-django of a mutation for uploading a file floating around on the internet to anybody's knowledge?

**Comment by BossGrand** [comment]
yea I got you, the files are in the context variable

      class UploadFileMutation(graphene.ClientIDMutation):
             class Input:
                 pass
                 # nothing needed for uploading file
         
             # your return fields
    
    @classmethod
    def mutate_and_get_payload(cls, args, context, info):
          files = context.FILES
          print(files)

**Comment by syrusakbary** [comment]
Thanks @BossGrand for handling the question!

That's the way to make it work with Django :)

**Comment by smmoosavi** [comment]
I try similar code with [relay][1] and I got this error:

```
{"errors":[{"message":"POST body sent invalid JSON."}]}
```
request:
```
------WebKitFormBoundaryT2Bgy62Kcm3z30Yr
Content-Disposition: form-data; name="query"

mutation Medias($input_0:CreateMediaMutationInput!) {
  createMedia(input:$input_0) {
    clientMutationId,
    ...F1
  }
}
fragment F0 on ViewerNode {
  me {
    id
  },
  id
}
fragment F1 on CreateMediaMutationPayload {
  viewer {
    id,
    ...F0
  }
}
------WebKitFormBoundaryT2Bgy62Kcm3z30Yr
Content-Disposition: form-data; name="variables"

{"input_0":{"clientMutationId":"1"}}
------WebKitFormBoundaryT2Bgy62Kcm3z30Yr
Content-Disposition: form-data; name="file"; filename="somefile.png"
Content-Type: image/png


------WebKitFormBoundaryT2Bgy62Kcm3z30Yr--
```
Did I miss somethings? Tanks for your help

versions:
```
graphene==1.1.3
graphene-django==1.2.1
graphql-core==1.0.1
graphql-relay==0.4.5
Django==1.10.5
```

[1]: https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#getfiles

**Comment by BossGrand** [comment]
@smmoosavi What does your relay mutation look like? You need to have a getFiles function that is a dict of files you want to upload

**Comment by smmoosavi** [comment]
python:

```py
class CreateMediaMutation(ViewerFields, relay.ClientIDMutation): 
# ViewerFields only add viewer field and resolver.

    class Input:
        pass

    media = Field(MediaNode)

    @classmethod
    def mutate_and_get_payload(cls, input, context, info):
        user = context.user
        media_form = MediaForm(
            {'uploader': user.pk},
            context.FILES
        )
```

js:
```js
        const csrfToken = getCSRF();
        const headers = {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'X-CSRFToken': csrfToken,
        };

        Relay.injectNetworkLayer(
            new Relay.DefaultNetworkLayer(uri, {
                credentials: 'same-origin',
                headers,
            })
        );

class CreateMediaMutation extends Relay.Mutation {
    static fragments = {
        viewer: () => viewerFragment,
    };

    getMutation() {
        return Relay.QL`mutation {createMedia}`;
    }

    getFiles() {
        return {
            file: this.props.file,
        };
    }

    getVariables() {
        return {};
    }

    getFatQuery() {
      // ...
    }
    getConfigs() {
      // ...
    }
}
```

**Comment by smmoosavi** [comment]
I think I found the problem. I should remove `'Content-Type': 'application/json'` from `injectNetworkLayer` and let relay choice content type.

**Comment by savovs** [comment]
Hi guys, does anyone have an updated example for Graphene 2.0? I'm working on [a Flask example project](https://github.com/savovs/flask-graphene-hello) and would love to include file uploads in it.

**Comment by patrick91** [comment]
Here's an example I did a few days ago:

```python
class Upload(graphene.Scalar):
    def serialize(self):
        pass

class UploadSignature(graphene.Mutation):
    class Input:
        signature = Upload()
        id = graphene.String(required=True)

    ok = graphene.Boolean()

    @staticmethod
    def mutate(root, args, context, info):
        files = request.files
        client_signature = files['variables.signature']

        return UploadSignature(ok=True)


class MyMutations(graphene.ObjectType):
    upload_signature = UploadSignature.Field()

schema = graphene.Schema(query=XXX, mutation=MyMutations, types=[Upload])
```

let me know if you have any question :)

**Comment by savovs** [comment]
Thanks @patrick91, is there a way to test it in Graphiql, Postman or something?

**Comment by patrick91** [comment]
@savovs yes, you can use postman, you need to do a standard POST request with data encoded as multipart/form-data :)

You can't use Graphiql because it doesn't support file uploads :)

**Comment by alex-dotdev** [comment]
Has anyone had any luck getting file uploads to work with React Native and the Apollo Client?

**Comment by russelh15** [comment]
@ghost Did you ever find a solution with getting this to work from React-Native using Apollo Client?

Spent a full day trying various things, but no luck so far.

**Comment by russelh15** [comment]
Finally got file uploads working from React-Native to our Graphene backend. Here's the article that pointed me in the right direction

https://medium.com/@JamesCPoole/uploading-files-with-graphql-apollo-and-react-native-82016ca47d0a

The key is to use react-native-fetch-blob to make the fetch request to the server.

**Comment by thebenwaters** [comment]
Anyone have an idea how to do this asyncy?? With aiohttp-graphql?

**Comment by blackflame007** [comment]
> Here's an example I did a few days ago:
> 
> ```python
> class Upload(graphene.Scalar):
>     def serialize(self):
>         pass
> 
> class UploadSignature(graphene.Mutation):
>     class Input:
>         signature = Upload()
>         id = graphene.String(required=True)
> 
>     ok = graphene.Boolean()
> 
>     @staticmethod
>     def mutate(root, args, context, info):
>         files = request.files
>         client_signature = files['variables.signature']
> 
>         return UploadSignature(ok=True)
> 
> 
> class MyMutations(graphene.ObjectType):
>     upload_signature = UploadSignature.Field()
> 
> schema = graphene.Schema(query=XXX, mutation=MyMutations, types=[Upload])
> ```
> 
> let me know if you have any question :)

How would this example work with Django's models?

**Comment by kevinzDzul** [comment]
how to save a file  this is my  link   https://github.com/lmcgartland/graphene-file-upload/issues/28#issue-407027908

**Comment by harunurkst** [comment]
Hello @blackflame007 ,
I can upload a single file, but uploading multiple files is not working this way. It shows
`{
    "errors": [
        null
    ]
}`

**Comment by beraiarezo** [comment]
> Here's an example I did a few days ago:
> 
> ```python
> class Upload(graphene.Scalar):
>     def serialize(self):
>         pass
> 
> class UploadSignature(graphene.Mutation):
>     class Input:
>         signature = Upload()
>         id = graphene.String(required=True)
> 
>     ok = graphene.Boolean()
> 
>     @staticmethod
>     def mutate(root, args, context, info):
>         files = request.files
>         client_signature = files['variables.signature']
> 
>         return UploadSignature(ok=True)
> 
> 
> class MyMutations(graphene.ObjectType):
>     upload_signature = UploadSignature.Field()
> 
> schema = graphene.Schema(query=XXX, mutation=MyMutations, types=[Upload])
> ```
> 
> let me know if you have any question :)

signature = Upload() always required files. if you want to receive another parameters and file filed is not required  Upload() method returns error  `Variable "$file" of required type "Upload!" was not provided.` . 
what is solution to resolve that file won't be required always?
