### ISSUE TITLE
Replace Unidecode package with text_unidecode package

### ISSUE THREAD

**Issue by joricht** [graphql-python/graphene-django#1014]
* **What is the current behavior?**

  The Unidecode package is licensed under GPL, which makes it impossible to include it in any non-GPL/MIT licensed software. Since graphene-django is licensed under MIT, it would be great to allow graphene-django to be included in non-GPL/MIT licensed software, which is currently disallowed by the GPL of unidecode (which is the only dependency with such a problem). 

  The alternative package text_unidecode offers a drop-in replacement for unidecode with a less restrictive license. However, as stated to the project website unidecode offers better memory usage and better transliteration quality over text_unidecode. Will this be a show stopper or would it be possible to exchange the packages?

* **What is the expected behavior?**

  graphene-django should be usable within any project.

* **What is the motivation / use case for changing the behavior?**

  Allow graphene-django to be used in non-GPL/MIT licensed projects.

* **Please tell us about your environment:**
  
  - Version: 2.12.1
  - Platform: Linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by joricht** [comment]
Replacing unidecode with text_decode is as easy as replacing the import and the test suite passes. If this is a viable solution, I would be happy to provide the PR.

However, maybe someone has a generell opinion on the license problem?

**Comment by zbyte64** [comment]
I don't really have an opinion on the license but wouldn't mind removing impediments. The performance trade off is a concern though...

**Comment by joricht** [comment]
Thanks @artofhuman for the PR. Is there anything that needs to be done here, or are we just waiting for #1060 to be merged?
Thanks @zbyte64 for taking care of this issue.

Regarding the performance: The website of text_unidecode just states

> If you’re OK with GPL-only, use unidecode (it has better memory usage and better transliteration quality).

So I guess the loss is not really in performance but in memory consumption. I think that this is a viable trade-off since memory is not so much of a problem nowadays.
