### ISSUE TITLE
graphql.error.base.GraphQLError: Expected value of type "AuthUserType" but got: Store.

### ISSUE THREAD

**Issue by MartinSchere** [graphql-python/graphene-django#1018]
* **What is the current behavior?**
Graphene is raising this error even when the mutation is executed correctly.

This is the code for the mutation:

```
class CreateStore(graphene.Mutation):
    store = graphene.Field(StoreType)

    class Arguments:
        username = graphene.String(required=True)
        password = graphene.String(required=True)
        latitude = graphene.Float(required=True)
        longitude = graphene.Float(required=True)
        opening_time = graphene.DateTime(required=True)
        closing_time = graphene.DateTime(required=True)

    def mutate(self, info, username, password, latitude, longitude, opening_time, closing_time):
        auth_user = get_user_model()(
            username=username,
        )
        auth_user.set_password(password)
        store = Store(user=auth_user, name=username,
                      location=Point(latitude, longitude, srid=4326),
                      opening_time=opening_time, closing_time=closing_time)

        auth_user.save()
        store.save()
        return CreateStore(store=store)
```
When executed, everything registers correctly but an error is being raised.

* **What is the expected behavior?**
No errors being raised.

* **Please tell us about your environment:**
  
  - Version: 2.10.0
  - Platform: Windows

**Comment by jkimbo** [comment]
@MartinSchere do you have the full stack trace?

**Comment by MartinSchere** [comment]
> @MartinSchere do you have the full stack trace?

Had to change the whole thing for time's sake (it was urgent). Don't have the code available.

**Comment by jkimbo** [comment]
Ok sorry I couldn't help. In the future including the stack trace in the bug report is quite helpful to diagnose the issue.

**Comment by HakanPuente** [comment]
Hi @jkimbo , I've had all the same issue, 
When executed, everything registers correctly but an error is being raised.
What is the expected behavior? > No errors being raised.

my models:

```
from polymorphic.models import PolymorphicModel

Activity(models.Model, PolymorphicModel)

ParentActivity(Activity)

Goal(models.Model):
   activity = models.ForeignKey("Activity", on_delete=models.CASCADE, related_name="activity_goals", blank=True) 


class ActivityNode(DjangoObjectType):
    class Meta:
        model = Activity
        interfaces = (relay.Node,)
        filter_fields: typing.List[str] = []
        convert_choices_to_enum = True

```

The mutation  is successfully but I can't get it's result. 
It just throws this ```graphql.error.base.GraphQLError: Expected value of type "ActivityNode" but got: ParentActivity.```
