### ISSUE TITLE
When passing null as input in mutation, value does not show up in args

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#103]
For example the following will raise an exception when number is null

     class EditNumber(graphene.ClientIDMutation):
        class Input:
            number = graphene.Int()
        
         success = graphene.Boolean()

         @classmethod
         def mutate_and_get_payload(cls, args, context, info):
               args['number'] # this raises a errror when i pass in null 

On the JS side my getVariables input is:

     getVariables() {
         return {
            number: null
         };
     }

I would expect calling args['number'] to return None instead of raising an exception if I specifically supply null as my input

Is this the desired behavior, or is this a bug?

**Comment by imsickofmaps** [comment]
Keen to know this too

**Comment by syrusakbary** [comment]
This is a bug in the `GraphQL-core` (and `GraphQL-js` version up to 0.6).
Will keep this issue open until is solved :)

**Comment by imsickofmaps** [comment]
@syrusakbary I think you are referring to https://github.com/graphql-python/graphene/issues/280 ?

**Comment by syrusakbary** [comment]
@imsickofmaps yes :)

**Comment by insolite** [comment]
Seems like the same thing happens with variables as well. As @prokofiev mentioned here:
https://github.com/graphql-python/graphene/issues/280#issuecomment-249126004
`null` can be passed using variables and there is no `Unexpected Name "null"` anymore. But instead, I am getting `Variable "$var1" of required type "String!" was not provided`. Of course everything is ok when `var1` is `25` or so.

**Comment by BossGrand** [comment]
Solved in 2.0

**Comment by Eraldo** [comment]
I don't get it. :|
When passing `null` in my client I get `None` on the server. How am I able to distinguish between `null` and not provided?

**Comment by jkimbo** [comment]
@Eraldo if you pass null from the client the argument will be `None` in the mutate function. However if you don't provide the argument then an argument won't be provided to the mutation function.

Example:

```python
class SomeMutation(graphene.Mutation):
    class Arguments:
        name = graphene.String()

    ok = graphene.Boolean()

    def mutate(self, info, **args):
		# If no name provided then `args = {}`
		# If name is `null` then `args = { 'name': None }`
```

**Comment by cbouvier15** [comment]
Hi there! 

I'm using `graphene==2.1.8` and `graphene-django==2.10.1`. It is not working as expected for me..

When I send `value=null` from `graphiql` the argument is ignored, instead of appearing with `null` value.
Is this still a problem? Am I doing something wrong?

Thanks in advance!
