### ISSUE TITLE
AttributeError: 'function' object has no attribute '__func__' error while using SerializerMutation 

### ISSUE THREAD

**Issue by sfahad1414** [graphql-python/graphene-django#1038]
graphene-django version 2.13.0

gettting following error

  File "D:\miniconda\envs\deeplearning\lib\site-packages\graphene_django\rest_framework\mutation.py", line 110, in __init_subclass_with_meta__
    super(SerializerMutation, cls).__init_subclass_with_meta__(
  File "D:\miniconda\envs\deeplearning\lib\site-packages\graphene\relay\mutation.py", line 43, in __init_subclass_with_meta__
    if cls.mutate and cls.mutate.__func__ == ClientIDMutation.mutate.__func__:
AttributeError: 'function' object has no attribute '__func__'

**Comment by zbyte64** [comment]
Would it be possible to show us your Mutation? Also would be good to know which version of DRF you're using.

**Comment by zbyte64** [comment]
Was able to reproduce this, it happens when you define a mutation and the mutate function is not a classmethod.

**Comment by zbyte64** [comment]
Open issue covering usage: https://github.com/graphql-python/graphene/issues/810

Other issue is our docs are out of date, the following does not use `classmethod`: https://docs.graphene-python.org/projects/django/en/latest/mutations/

**Comment by zbyte64** [comment]
Closing issue as the documentation is now updated.
