### ISSUE TITLE
Custom Fields on an ObjectType should be recognized by the Queryset

### ISSUE THREAD

**Issue by irvinktang** [graphql-python/graphene-django#1045]
Queryset doesn't recognize the custom fields created using Resolvers. I'm trying to order my query results based on these fields and having trouble figuring out how to do it.

Example code:
```
class MyObjectType(DjangoObjectType):
    class Meta:
        model = MyObj
        fields = [ .. ]
        filterset_class = MyObjFilter
        ...

    my_custom_field = graphene.Field(AnotherType)
  
    def resolve_my_custom_field(self, info):
        return ...
```
I tried creating a custom filter class based on the `django-filters` [documentation](https://django-filter.readthedocs.io/en/master/ref/filters.html#adding-custom-filter-choices)
```
class MyObjFilter(django_filters.OrderingFilter):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.extra["choices"] += [
            ("total_field", "total_field"),
            ("-total_field", "-total_field")
        ]

    def filter(self, qs, value):
        if any(v in ["total_field", "-total_field"] for v in value):
            return qs.sort_by_total_field()
        return super().filter(qs, value)
```
I would get this error when trying to create my custom filter 
```
Cannot resolve keyword 'total_field' into field. Choices are: ...
```
However, since the queryset doesn't actually include the custom field that I created, I can't filter based on this field anyways. 

Is there any way currently that I could achieve this without needing this change on your end? 

Thank you!

**Comment by zbyte64** [comment]
I think this is invalid. Filters operate on Querysets, if you want to filter by `total_field` then it has to be part of the model/database.
