### ISSUE TITLE
Filtering by reverse OneToMany relationsship results in duplicate objects in result

### ISSUE THREAD

**Issue by silvanm** [graphql-python/graphene-django#1051]
I used the [cookbook-example](https://github.com/graphql-python/graphene-django/tree/master/examples/cookbook) and added the filter `amounts__ingredient__name` (changes are [here](https://github.com/graphql-python/graphene-django/compare/master...silvanm:master))

```
class RecipeNode(DjangoObjectType):
    class Meta:
        model = Recipe
        interfaces = (Node,)
        filter_fields = {
            "amounts__ingredient__name": ["exact", "icontains", "istartswith"]
        }
```

I added a recipe which contains two ingredients: "Chicken" ans "Milk". (Fixture can be found [here](https://github.com/silvanm/graphene-django/blob/master/examples/cookbook/fixture.json) )

Query:
```
query {
	allRecipes(amounts_Ingredient_Name_Icontains:"i") {
    edges {
      node {
        id
        title 
      }
    }
  }
}
```

### Actual behavior

Node "Chicken with Milk" appears twice in the result:

```
{
  "data": {
    "allRecipes": {
      "edges": [
        {
          "node": {
            "id": "UmVjaXBlTm9kZTox",
            "title": "Milk-Beef"
          }
        },
        {
          "node": {
            "id": "UmVjaXBlTm9kZToy",
            "title": "Chicken with Milk"
          }
        },
        {
          "node": {
            "id": "UmVjaXBlTm9kZToy",
            "title": "Chicken with Milk"
          }
        }
      ]
    }
  }
}
```

### Expected behavior

Node "Chicken with Milk" appear just once:

```
{
  "data": {
    "allRecipes": {
      "edges": [
        {
          "node": {
            "id": "UmVjaXBlTm9kZTox",
            "title": "Milk-Beef"
          }
        },
        {
          "node": {
            "id": "UmVjaXBlTm9kZToy",
            "title": "Chicken with Milk"
          }
        },
      ]
    }
  }
}
```

### Environment

```
graphene==2.1.8
graphene-django==2.13.0
graphql-core==2.3.2
graphql-relay==2.0.1
```

### Related 
* #767

**Comment by zbyte64** [comment]
Thinking about what is happening here, I think the recipe "Chick with Milk" has two ingredients that match the query, hence it shows up twice. I believe this functionality is handled by django-filters, which documents how to enable distinct on the filter: https://django-filter.readthedocs.io/en/master/ref/filters.html#distinct

To utilize this we would need to define our own filterset, perhaps that is what the example should do as well.

**Comment by silvanm** [comment]
You were right. A custom filter solved the problem.

Here's the code which is doing what I expected:

```
class RecipeFilter(django_filters.FilterSet):
    amounts = django_filters.CharFilter(lookup_expr='ingredient__name__icontains', distinct=True)

    class Meta:
        model = Recipe
        fields = ['amounts']


class Query(object):
    recipe = Node.Field(RecipeNode)
    all_recipes = DjangoFilterConnectionField(RecipeNode, filterset_class=RecipeFilter)

    recipeingredient = Node.Field(RecipeIngredientNode)
    all_recipeingredients = DjangoFilterConnectionField(RecipeIngredientNode)
```
