### ISSUE TITLE
Official documentation & API reference

### ISSUE THREAD

**Issue by RadoRado** [graphql-python/graphene-django#106]
Hi there!

Kudos for the great library :beers: 

I have few questions, regarding the documentation:

* Is this the official documentation for the Django support - http://docs.graphene-python.org/projects/django/en/latest/ ?
* Is there a reference for the API of the library?

My questions are coming from [the tutorial](http://docs.graphene-python.org/projects/django/en/latest/tutorial/)

Without much explanation, in the tutorial we are using things like `interfaces = (relay.Node, )`, `relay.Node.Field`, `DjangoFilterConnectionField`. If you want to understand what's happening you need to read the code + do some checking with the `graphene` docs about `interfaces`. Aside from that, I couldn't find any reference or explanation why we are using that.

Also this brings the strange `edges / node` query:

```
query {
  allIngredients {
    edges {
      node {
        id,
        name
      }
    }
  }
}
```

What's the deal with that?

Wouldn't it be better if we have 2 tutorials?

* First one, with less magic, with `resolve_` methods, to get the feeling of how things should work.
* Second one, using those `relay` magic & explaining why we want to do that.

And if you think that's a good idea, do you need help with that?

Cheers :beers:

**Comment by mjtamlyn** [comment]
I don't have the time to work further on improved tutorials personally, but I feel they are necessary. I did some work when I ran a workshop, following along the lines of what you suggest there. Writing a "simple" API as the initial tutorial, and then explaining the extra complexities of Relay and/or Django is a good step. It's difficult to know how much graphene should be responsible for a relay or GraphQL tutorial, but at the moment they're not widely understood and I think the official docs aren't great either, so it would certainly help graphene adoption if we were able to explain them clearly ourselves.

https://speakerdeck.com/mjtamlyn/an-introduction-to-graphene-and-relay
https://github.com/mjtamlyn/graphene-tutorial

**Comment by RadoRado** [comment]
@mjtamlyn Thanks for the links - will take a look at them & write back. Do you have an accompanying video to the slides to watch?

Also, I think I can help with writing some more examples & tutorials for Graphene and Django. We will start using this in one of our projects.

Cheer! :beers:

**Comment by mjtamlyn** [comment]
Unfortunately my workshop was not filmed.

**Comment by RadoRado** [comment]
@mjtamlyn Will make some PRs in the next few days :+1:

**Comment by RadoRado** [comment]
@mjtamlyn Decided to start with something small - to get the hang of it - https://github.com/graphql-python/graphene-django/pull/110/files

Feedback would be appreciated :beers:

**Comment by RadoRado** [comment]
@mjtamlyn Actually made another PR with the so-called "Introduction tutorial" not using relay - https://github.com/graphql-python/graphene-django/pull/112

Feedback would be appreciated :beers: A lot of things yet to be done there.

**Comment by syrusakbary** [comment]
@RadoRado Thanks for taking the initiative! :)

**Comment by RadoRado** [comment]
@syrusakbary Thanks for merging #112 

What do you thing it should be helpful for me to do next? Maybe try to add some more details in the relay tutorial?

**Comment by mvanlonden** [comment]
@RadoRado we're starting to label issues with `Help wanted` and `Documentation`. Would be great if you could take some of those on! 🍻
