### ISSUE TITLE
DjangoListField returning stale data by default

### ISSUE THREAD

**Issue by lijok** [graphql-python/graphene-django#1061]
https://repl.it/talk/share/DjangoListField-bug/79205
Idk if this is the correct way of sharing the repl, if not, lmk

Repro:
1. Create superuser
2. In one tab, run query
```py
{
  allRecipes {
    id
    title
    instructions
  }
}
```
3. In another tab, go to admin panel, add new record to recipes
4. Rerun the above query

You'll see that the data returned does not include the new recipe that was added

**Comment by zbyte64** [comment]
I am able to reproduce on the repl.it environment but I feel like the environment might be sus. Are you seeing this outside the repl.it environment?

Anyhow, it shouldn't be too difficult to add a unit test for this. I have similar tests in my own project but they are based on DjangoFilterConnectionField

**Comment by eimantas-gecas-axomic** [comment]
Yes, I'm seeing this same behaviour outside the repl.it environment

**Comment by lijok** [comment]
Yes, I'm seeing the same behaviour in my local django project

**Comment by zbyte64** [comment]
Alrighty, I'll work to add a test for that tomorrow. Thanks for bringing this up
