### ISSUE TITLE
Question about mutation in the documentation

### ISSUE THREAD

**Issue by laurent-brisbois** [graphql-python/graphene-django#1066]
**Is your feature request related to a problem? Please describe.**
No. It is about a clarification that might be helpful about mutations in the documentation.

**Describe the solution you'd like**
In the documentation, [here](https://docs.graphene-python.org/projects/django/en/latest/mutations/#simple-example), in the `QuestionMutation` class, there is a `question` attribute. What does that actually mean ? It says that it defines the response and I don't understand this.

In my code I've been able to do this :

My type :
----------

```python
class UserType(DjangoObjectType):

    class Meta:
        model = User
        fields = (
            'id',
            'username',
            'password',
            'email',
            'first_name',
            'last_name',
            'is_active',
            'group_ids',
        )

    full_name = graphene.String()           # Python property
    full_identification = graphene.String() # Python property
```

My mutation :
---------------

```python
class UpdateUser(graphene.Mutation):
    # --------> I could comment these and no problem. Why ? <--------
    # id = graphene.ID()
    # username = graphene.String()
    # email = graphene.String()
    # first_name = graphene.String()
    # last_name = graphene.String()
    # is_active = graphene.Boolean()

    class Arguments:
        id = graphene.ID()
        username = graphene.String()
        email = graphene.String()
        first_name = graphene.String()
        last_name = graphene.String()
        is_active = graphene.Boolean()

    class Meta:
        output = UserType

    @login_required
    def mutate(self, info, **kwargs):
        user = get_object_or_404(User, id=kwargs['id'])
        for attr, value in kwargs.items():
            setattr(user, attr, value)
        user.save()
        return user
        # I'm not returning explicit UserType, is it a problem ?
        # I actually do it with the Meta class. I guess it is the same for this
```

and it works whereas I didn't specify anything for the response attributes. And I don't even return the same kind of thing.
Can someone explain if I'm doing it wrong ?

**Comment by zbyte64** [comment]
If you do not define an `output` type then you must define the return fields on your mutation itself. The example documentation does not define output but opts to return an instance of itself instead. Returning the `user` model instance works for you because it duck types to `UserType`.

From the code docs:
```
output (graphene.ObjectType): Or ``Output`` inner class with attributes on Mutation class.
            Or attributes from Mutation class. Fields which can be returned from this mutation
            field.
```

**Comment by laurent-brisbois** [comment]
So, I can get rid of the return values in my `UserType` class since I define the `output = UserType` which is linked to the `User` model.
And I can return an instance of the `User` model while I mentioned `output = UserType` because these two are bound to each other by `model = User`

Is that correct ?
Is that a good way to do this ?

**Comment by zbyte64** [comment]
Generally/Recommended we define the return field at the top level of the class, like `user = Field(UserType)` instead of using the output meta option. This was we know the exact field name the return value will be, and in the `mutate` method we return the mutation class with that return value, like `cls(user=user)` or `UpdateUser(user=user)`.

**Comment by laurent-brisbois** [comment]
@zbyte64 
Okay I see, thanks.
Last thing. You say `Generally/Recommended`. What does that mean ? That the way I do it isn't exactly the same ? That there are "deep inside differences" ? Or is it for pure conventions and clarity ?

**Comment by zbyte64** [comment]
I meant it's what I've seen done generally and what I recommend doing for clarity purposes.

**Comment by laurent-brisbois** [comment]
I see. Thanks for your advices !
