### ISSUE TITLE
Catching GraphQLLocatedError for tests

### ISSUE THREAD

**Issue by laurent-brisbois** [graphql-python/graphene-django#1072]
**Is your feature request related to a problem? Please describe.**
No, question about doing a particular thing

**Describe the solution you'd like**
I'd like to know the way to catch GraphQLLocatedError, or a way to `assertRaises` them.

I've tried :

- try...except way :
```python
try:
    response = self.client.execute(query, variables)
except GraphQLLocatedError:
    self.fail(...)
```

- with self.assertRaises(...) way :
```python
with self.assertRaises(GraphQLLocatedError):
    response = self.client.execute(query, variables)
```

But none of these work. How can I do this ?

**Comment by ulgens** [comment]
I think what does `do_smth` do here is important. Graphql executor doesn't just throw that error and break the operation. It tries to return the error in response body. You may want to look at `graphene_django.utils.testing.GraphQLTestCase`

**Comment by laurent-brisbois** [comment]
@ulgens Thanks for your answer.
> I think what does `do_smth` do here is important. Graphql executor doesn't just throw that error and break the operation. It tries to return the error in response body. You may want to look at `graphene_django.utils.testing.GraphQLTestCase`

I edited my post. the `do_smth` is in my case the execution of the query. In the test I'm trying to write, I execute the test once while being logged, which should be okay (I use graphql-jwt for authentication and I've set the `@login_required` decorator on my query).

And I also execute the query whereas I'm not logged in in a second test. The goal is to check that an exception is thrown If I perform a query while not logged in. If, for instance, an `assertRaises` fails, that would mean for me that someone has removed the `@login_required` decorator.

I hope I'm clear :D

**Comment by zbyte64** [comment]
Could provide a custom ExecutionContext class with it's own `handle_field_error` that could stash the original errors for you and then assert they are proper in the test. We need more documentation covering this pattern.

**Comment by laurent-brisbois** [comment]
> Could provide a custom ExecutionContext class with it's own `handle_field_error` that could stash the original errors for you and then assert they are proper in the test. We need more documentation covering this pattern.

@zbyte64 
Could your provide a basic structure for that ? I'm not sure to understand what you mean.

**Comment by zbyte64** [comment]
In the past I have used the following class to get stack traces of exceptions:

```
from graphql.execution import ExecutionContext

class DebugExecutionContext(ExecutionContext):
        def handle_field_error(
            self, raw_error: Exception, field_nodes, path, return_type,
        ) -> None:
            import traceback            
            traceback.print_exception(
                type(raw_error), raw_error, raw_error.__traceback__
            )
            return super().handle_field_error(raw_error, field_nodes, path, return_type)

```

Then when I setup my view in the urls.py I pass it as an option:
```
GraphQLView.as_view(execution_context_class=DebugExectionContext)
```

Kind of lame that this method still requires patching the urlconf for use in tests: https://pytest-django.readthedocs.io/en/latest/helpers.html#pytest-mark-urls-override-the-urlconf

**Comment by kubami** [comment]
There is a new `UnforgivingExecutionContext` in graphene's beta releases.

However passing the `execution_context_class` to `GraphQLView.as_view` yields this error:

```
TypeError: GraphQLView() received an invalid keyword 'execution_context_class'. as_view only accepts arguments that are already attributes of the class.
```

Looking at the code of the `GraphQLView` and `.as_view` it seems it should work. 
@zbyte64 have you had this problem?

**Comment by kubami** [comment]
The above error is caused by `hasattr` check in `.as_view`, as it is not aware that the `GraphQLView` has that attribute.
The above PR fixes that.
