### ISSUE TITLE
Error during installation -- ImportError: No module named 'graphql.language'

### ISSUE THREAD

**Issue by un33k** [graphql-python/graphene-django#108]
Following the official [site](http://docs.graphene-python.org/projects/django/en/latest/tutorial/#setup-the-django-project) ... during the installation of graphene-django, this error is seen. 

.../python3.4/site-packages/graphene/types/scalars.py", line 3, in <module>
    from graphql.language.ast import (BooleanValue, FloatValue, IntValue,
ImportError: No module named 'graphql.language'

$ pip freeze | grep -e graph -e Django
Django==1.10.5
django-graphiql==0.4.4
graphene==1.1.3
graphene-django==1.2.1
graphql-core==1.0.1
graphql-relay==0.4.5

macOS Sierra

**Comment by RadoRado** [comment]
@un33k can you try removing `django-graphiql` ?

**Comment by un33k** [comment]
@RadoRado problem is now resolved. There was a graphql directory in the project, on python path. renaming it fixed the issue. thx.

**Comment by larsoleruben** [comment]
PS: Just the path was a folder starting with GraphQL.... is enough to breal it :-(

**Comment by PramodTKodag** [comment]
pip install graphene_django

**Comment by yongtaekjun** [comment]
I followed the link  https://www.howtographql.com/graphql-python/2-queries/ 
PS > pip install graphene_django
PS > python manage.py startapp links
PS > pip list
==== it has graphene-django 2.2.0 ===================
The error message shown same as above.

**Comment by yongtaekjun** [comment]
I solved the problem ^^.
The python-django is running under Windows 10.
In the Python folder : (in my case ) E:\Programs\Python3.7.2\Lib\site-packages\graphene_django
The folder name should be graphene-django ( not underbar ). Or we should write correct the name inside settings.py like bellow

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django' # from graphene-django
]

**Comment by chadfurman** [comment]
> PS: Just the path has a folder starting with GraphQL.... is enough to break it :-(

This was my issue as well.  "no module named 'graphql.type'" or 'graphql.types' or something.  I had my schema in a "graphql" folder.

**Comment by cguillemette** [comment]
It also applies to filenames, once I renamed to something else than 'graphql', it worked. 🤨
