### ISSUE TITLE
GenericRelations

### ISSUE THREAD

**Issue by petertrotman** [graphql-python/graphene-django#11]
I've been reading through the source code and the docs and I've been trying to get a GenericRelation to work, but I can't work it out. I feel like there's some cleverness to be done with a `resolve` method. Any tips?

``` py
# ignoring imports

class TaggedItem(models.Model):
    tag = models.SlugField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')  # does not resolve

class Bookmark(models.Model):
    url = models.URLField()
    tags = GenericRelation(TaggedItem)  # is not automatically available

class TaggedItemNode(graphene_django.types.DjangoObjectType):
    # parent = graphene.ID() ... ?

    # resolve_parent(...) ... ?

    class Meta:
        model = TaggedItem
        interfaces = (graphene.Node,)

class BookmarkNode(graphene_django.types.DjangoObjectType):
    # tags = graphene.ID()  ... ?

    # resolve_tags(...) ... ?

    class Meta:
        model = Bookmark
        interfaces = (graphene.Node,)
```

Any help much appreciated.

P

**Comment by chaffeqa** [comment]
Try manually adding the `related_name='x'` to each of the `Model` relation declarations.

In graphene v0.x I found that was the secret to getting library to pick up on the relationship and hydrate the connections

**Comment by petertrotman** [comment]
@chaffeqa thanks but I've looked through the source code and it turns out graphene-django doesn't have any notion of `GenericRelation` or `GenericForeignKey` and can't process them. I had a look into adding the functionality myself and while I think it might be possible to get GenericRelation working (i.e. the 'parent' object's list of the generic children), because (as far as I can tell) graphene only supports the determination of node types 'statically' - without an instance of the object - it's impossible to generate a schema dynamically, i.e. one where the node type can only be determined using an actual instance (as in the case of Generic Relations).

I think the problem will need to be solved for Graphene - not being able to have generic relations is too limiting - but I think it will require changes to at least 2 of, if not all 3 of graphene-django, graphene and graphql-core.

**Comment by jameswyse** [comment]
I'm using `GenericRelation` successfully with a simple resolver. Something like this should work:

```python
class Bookmark(models.Model):
    url = models.URLField()
    tags = GenericRelation(TaggedItem, related_query_name="bookmarks")

class BookmarkNode(graphene_django.types.DjangoObjectType):
    tags = graphene.relay.ConnectionField(TaggedItemNode)

    def resolve_tags(self, args, context, info):
        return self.tags.all()

    class Meta:
        model = Bookmark
        interfaces = (graphene.Node,)
```

I don't use the reverse/parent lookup in my app so I'm not too sure how to do that. The resolver would be simple enough, but you'd need to determine the type dynamically somehow (since `content_object` could be any model)

It looks like graphene has support for dynamic types; there's not much documentation but the tests might help:
https://github.com/graphql-python/graphene/blob/master/graphene/types/tests/test_typemap.py
https://github.com/graphql-python/graphene/blob/master/graphene/types/tests/test_union.py

The Django docs on contenttypes / generic relations are worth reading through too: https://docs.djangoproject.com/en/1.10/ref/contrib/contenttypes/

**Comment by themotu** [comment]
This ended up being simpler than expected. I feel like this could be automatic in graphene-django but haven't dug very much.

models.py
```python
class Bookmark(models.Model):
    url = models.URLField()
    tags = GenericRelation(TaggedItem)
```
schema.py
```python
class TaggedItemType(DjangoObjectType):
    class Meta:
        model = TaggedItem

class Bookmark(DjangoObjectType):
    class Meta:
        model = Bookmark

    tags = graphene.List(TaggedItemType)

    def resolve_tags(self, args):
        return self.tags.all()
```

graphql query:
```
{
  bookmark(id:1) {
    id
    url
    tags {
      tag
    }
  }
}
```

**Comment by TitanFighter** [comment]
**Example of Reverse lookup (from Content Type model to usual Model)**

I have 4 types of profiles. Some fields are the same, some are different. Each profile has its own url, so I use ContentType as a central place of mappring urls<->profiles.

```
# profiles/models.py
class Sport(models.Model):
    pass

class ProfileAbstract(models.Model):
    pass

class ProfileOrganization(ProfileAbstract):
    pass

class ProfilePlace(ProfileAbstract):
    pass

class ProfileTeam(ProfileAbstract):
    pass

class ProfileUser(ProfileAbstract):
    pass

class ProfileURL(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(max_length=30)  # Url

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=36)  # CharField because I use UUID
    content_object = GenericForeignKey('content_type', 'object_id')
```

----

```
# profiles/schema.py
import graphene

from graphene_django.types import DjangoObjectType

from .models import (ProfileOrganization, ProfilePlace, ProfileTeam, ProfileUser,ProfileURL, Sport)

# [ START: Types ]
class SportType(DjangoObjectType):
    class Meta:
        model = Sport


class ProfileURLType(DjangoObjectType):
    class Meta:
        model = ProfileURL

    slug = graphene.String()
    model_name = graphene.String()

    def resolve_slug(self, info):
        return self.slug

    def resolve_model_name(self, info):
        return self.content_object.__class__.__name__


class ProfileOrganizationType(DjangoObjectType):
    """
    Use this class as a basic class for others Profile Types classes
    """

    class Meta:
        model = ProfileOrganization
        fields = ('name', 'logo_data', 'profile_url')

    profile_url = graphene.Field(ProfileURLType)

    def resolve_profile_url(self, args):
        return self.profile_url.first()


class ProfilePlaceType(ProfileOrganizationType):
    class Meta:
        model = ProfilePlace


class ProfileTeamType(ProfileOrganizationType):
    class Meta:
        model = ProfileTeam


class ProfileUserType(ProfileOrganizationType):
    class Meta:
        model = ProfileUser


class ProfileTypeUnion(graphene.Union):
    class Meta:
        types = (ProfileOrganizationType, ProfileTeamType, ProfilePlaceType, ProfileUserType)
# [ END: Types ]


# [ START: Queries ]
class Query(graphene.ObjectType):
    """
    EXAMPLE OF QUERY:

    query profileDetails {
      profileDetails(profileUrl: "8auB-pMH-6Sh") {
        ... on ProfileTeamType {
          id,
          name,
          skillLevel,
          sport {
            name
          },
          profileUrl {
            slug,
            modelName
          }
        }
        
        ... on ProfilePlaceType {
          id,
          name,
          sports {
            name
          },
          profileUrl {
            slug,
            modelName
          }
        }
      }
    }
    """

    profile_details = graphene.Field(ProfileTypeUnion, required=True, profile_url=graphene.String())

    def resolve_profile_details(self, info, profile_url):
        profile_url_type = ContentType.objects.get(app_label='profiles', model='profileurl')
        profile_url_inst = profile_url_type.get_object_for_this_type(slug=profile_url)

        return profile_url_inst.content_object
# [ END ]
```

`...  on ProfileTeamType` is inline fragments ([details](https://graphqlmastery.com/blog/how-to-query-your-schema-with-graphql-fragments)).
As you can see, we query 2 fragments in the example above (however in my case it should be 4, according to the number of profiles type), but just one fragment/model returns data - the one which refers to the provided `profileUrl` in the query.

From front end side based on the received `modelName` we can handle fields according to our needs.
