### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by kovan** [graphql-python/graphene-django#1104]
Following the README:

```
$ pip install "graphene-django>=3"

ERROR: Could not find a version that satisfies the requirement graphene-django>=3
ERROR: No matching distribution found for graphene-django>=3

```

Am I missing something here?

Using Python 3.8.5

**Comment by zbyte64** [comment]
Graphene Django v3 is a prelease, README should indicate that the "--pre" option is needed. More info this: https://stackoverflow.com/questions/35131861/what-does-the-pre-option-in-pip-signify

**Comment by weilu** [comment]
So do `pip install graphene-django --pre` instead of `pip install "graphene-django>=3"`
