### ISSUE TITLE
No exception message supplied

### ISSUE THREAD

**Issue by basilfx** [graphql-python/graphene-django#111]
I'm new to GraphQL and Graphene.

After playing with the examples, I started to migrate an existing application to use GraphQL.

This seems to work:

```python
from graphene_django.types import DjangoObjectType
from graphene_django.filter import DjangoFilterConnectionField

from design_framework.core import models

import graphene

class Hook(DjangoObjectType):
    class Meta:
        model = models.Hook
        interfaces = (graphene.Node, )

class Query(graphene.AbstractType):
    hook = graphene.Node.Field(Hook)
    all_hooks = DjangoFilterConnectionField(Hook)
```

When I add the following, it breaks (note how it is NOT referenced in the above code):

```python
class Node(DjangoObjectType):
    class Meta:
        model = models.Node
        interfaces = (graphene.Node, )
```

It ends with the following exception (when trying to open GraphiQL):

```
  File "/Users/basilfx/Desktop/trunk/application/backend-v2/env/lib/python3.6/site-packages/graphene/types/typemap.py", line 73, in graphene_reducer
    assert _type.graphene_type == type
AssertionError
```

Pretty sure it has something to do with the class name `Node`. If I change it to `NodeNode`, it works. However, I stick with the same naming scheme as per examples in the [README.md](https://github.com/graphql-python/graphene-django/blob/master/README.md).

An error page resulting in  `AssertionError at /graphql No exception message supplied` does not say much, and I had to dig into it to find the cause (that seems unrelated).

Version info:

```
Django==1.10.5
django-debug-toolbar==1.6
django-extensions==1.7.6
django-filter==1.0.1
graphene==1.1.3
graphene-django==1.2.1
graphql-core==1.0.1
graphql-relay==0.4.5
iso8601==0.1.11
mysqlclient==1.3.9
promise==1.0.1
singledispatch==3.4.0.3
six==1.10.0
sqlparse==0.2.2
typing==3.5.3.0
```

**Comment by syrusakbary** [comment]
If you are using relay, `Node` is a reserved type. That error means that you have different two types named `Node` (probably `relay.Node` and your custom `Node` type).

Renaming it to something else should solve the issue 👍
