### ISSUE TITLE
CSRF token not being set

### ISSUE THREAD

**Issue by dinkom** [graphql-python/graphene-django#114]
I'm using graphene 1.1.3 and graphene-django 1.2.1. There is a decorator `@method_decorator(ensure_csrf_cookie)` on top of `dispatch` method of `class GraphQLView`. So, it should work fine. I've tried it in latest versions of Chrome and Firefox and I get the same problem - the cookie isn't being sent back to the frontend.

Could this be an issue with graphene-django or should I search elsewhere? I am working on localhost. If this cannot be an issue with graphene-django, feel free to close this issue. Thanks!

**Comment by dinkom** [comment]
Closing this - the cookie is being sent so it's not backend fault, but it's not being set on the frontend for some reason. It's a different issue all together.

**Comment by andy128k** [comment]
@dinkom I have similar issue. In my case it is caused by CSRF_COOKIE_HTTPONLY = True in a settings file.

As soon as this option ["offers no security"](https://github.com/django/django/pull/7700) I've just removed it.

**Comment by gotexis** [comment]
I am having this exact issue.
