### ISSUE TITLE
Recent Change To relay requesting UUID in django-filters arguments

### ISSUE THREAD

**Issue by ramyak-mehra** [graphql-python/graphene-django#1144]
I was just going through my API and found out the argument ID is of type UUID when using django-filters . Earlier it was of type ID and we could just pass the relay global ID. 
![image](https://user-images.githubusercontent.com/55009050/111074678-23b28000-850a-11eb-81cc-e1a86cc9bbf4.png)

**Comment by tcleonard** [comment]
That must be a bug I introduced when changing the way we convert the filter input types. I'll look into it

**Comment by ramyak-mehra** [comment]
> That must be a bug I introduced when changing the way we convert the filter input types. I'll look into it

Sorry for the delay. It was automatically fixed for some reason. I don't know what caused that maybe the bundled js file with the graphiql

**Comment by tcleonard** [comment]
ok great! I'll close the issue then
