### ISSUE TITLE
Why `DjangoFormMutation.perform_mutate()` calls `form.save()`

### ISSUE THREAD

**Issue by ruohola** [graphql-python/graphene-django#1152]
Django's plain (non-model) `Form`s don't have the `save()` method. Why does `DjangoFormMutation.perform_mutate()` still call that here: 

https://github.com/graphql-python/graphene-django/blob/3058118e8fc64a0a0853b67364381eccc7746f67/graphene_django/forms/mutation.py#L104

Am I missing something or does this just always end up in an error?

**Comment by zbyte64** [comment]
You're correct. That should probably be part of the DjangoModelFormMutation instead

**Comment by ruohola** [comment]
> You're correct. That should probably be part of the DjangoModelFormMutation instead

Yeah, it is there: https://github.com/graphql-python/graphene-django/blob/3058118e8fc64a0a0853b67364381eccc7746f67/graphene_django/forms/mutation.py#L179-L183, and I think it should only be there.

**Comment by ruohola** [comment]
Made a PR for this, @zbyte64 could you review?
