### ISSUE TITLE
Json Schema for RxDB replication with GraphQL

### ISSUE THREAD

**Issue by raratiru** [graphql-python/graphene-django#1158]
**Is your feature request related to a problem? Please describe.**
* RxDB supports [replication with GraphQL](https://rxdb.info/replication-graphql.html)
* For this to work, a [schema for each collection](https://rxdb.info/rx-schema.html) defined with the jsonschema-standard, is required.
* `./manage.py graphql_schema --schema api.graphql.schema --out schema.json` emits thousands of lines of code which are indeed compatible with json schema, however:

   [Not everything within the jsonschema-spec is allowed](https://rxdb.info/rx-schema.html#encryption) (It is the last paragraph if the link does not properly work)

**Describe the solution you'd like**
Given the following Type:
```
class MyType(graphene.ObjectType):
    id = String()

    def resolve_id(parent, info):
        return f"{parent.id}"


class Query(graphene.ObjectType):
    mytypes = graphene.List(MyType)

    def resolve_mytypes(root, info):
        return MyModel.objects.all()


schema = graphene.Schema(query=Query)
```
I would like to receive this schema for `MyType` or a list o schemas if more types are defined:
```
[{
    'title': 'MyType',
    'description': 'A Description',
    'type': 'object',
    'properties': {
        'id': {'title': 'Id', 'description': 'id', 'type': 'string'},
    }
}]
```

**Describe alternatives you've considered**
I considered using [`graphene-pydantic`](https://github.com/graphql-python/graphene-pydantic) or [`apischema`](https://github.com/wyfo/apischema/) but both are incompatible with:

 `graphene<3,>=2.1.7 (from graphene-django==2.15.0)`.

**Comment by RainshawGao** [comment]
graphene-django has v3beta now compatible with graphene v3
you can use `pip install --pre` or `poetry install django-graphene@^3.0.0b1`
may help
