### ISSUE TITLE
Django v4.0 support

### ISSUE THREAD

**Issue by MisterGlass** [graphql-python/graphene-django#1274]
Hello!

Django 4.0 is due out next week and I was attempting to test the release candidate with my project. Have there been any efforts to check/fix compatibility with the new version?

**Comment by geniuz** [comment]
Hi!
I have error django-4 with graphene-2.15:
ImportError: cannot import name 'force_text' from 'django.utils.encoding'

**Comment by Anmol-Porwal18** [comment]
Hi - Any update/ETA on this ?

**Comment by ulgens** [comment]
I'll try to complete reviews related to Python / Django versions before the week ends.

**Comment by budleigh** [comment]
Quick workaround is to just change it to `force_str` in your library code until patch. I haven't seen any other immediate breakages

**Comment by MaehMaeh** [comment]
After overcoming the force_str problem via monkeypatching, I have the problem of getting GraphiQL integrated.

With the previous code:
```
from graphene_django.views import GraphQLView

urlpatterns = [
    re_path(r'^api/graphql', csrf_exempt(GraphQLView.as_view(graphiql=True)), name='graphql'),
]
```
only this error message appears:
`ImportError: cannot import name 'get_default_backend' from 'graphql'`

Does anyone have an idea how to get this fixed?

**Comment by sanju-gif** [comment]
> Hi! I have error django-4 with graphene-2.15: ImportError: cannot import name 'force_text' from 'django.utils.encoding'

right,  and you can shoud replace 'force_text' to 'force_str'

**Comment by ulgens** [comment]
@firaskafri Can you please give a reference / small explanation when closing issues, for the paper trail? Thank you.

**Comment by pors** [comment]
@firaskafri is it closed because graphene works with Django 4 now?

**Comment by firaskafri** [comment]
Sorry guys, yes v3 supports Django 4 now
