### ISSUE TITLE
Could we use a Mongo database with MongoEngine and Graphene?

### ISSUE THREAD

**Issue by JesusMurF** [graphql-python/graphene-django#128]
Thats all, I would like to know if is it possible work with both tecnologies together :)

Thanks

**Comment by abawchen** [comment]
@JesusMurF : Is there any finding? I am looking for it as well. Thanks.

**Comment by zbyte64** [comment]
I think this is less a question for graphene-django and more for graphene in general. Django isn't going to offer much help in this regard.

**Comment by zbyte64** [comment]
Use this: https://github.com/graphql-python/graphene-mongo
