### ISSUE TITLE
Ability to overwrite object ID with additional information

### ISSUE THREAD

**Issue by un33k** [graphql-python/graphene-django#129]
**Feature Request.**

**Versions:**
graphene==1.2
graphene-django==1.2.1

It would be great to have the ability to include a variable to all gql responses automatically.
This would be great in cases where a language-aware site can send the response language automatically with all responses.

**Comment by zbyte64** [comment]
I think you would just have a `language_code` field on query and just include the field in your client side query.

**Comment by phalt** [comment]
Can you just subclass a generic `ObjectType` with your default?
