### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [graphql-python/graphene-django#1321]
Could you please consider to utilize unittest.mock instead of mock?

Background:
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock
https://trello.com/c/S6eADbii/64-remove-python-mock

**Comment by pgajdos** [comment]
At least 3.8, 3.9 and 3.10 testsuite works with that:
https://build.opensuse.org/package/show/home:pgajdos:python/python-graphene-django/

**Comment by ulgens** [comment]
@pgajdos It seems this is resolved by https://github.com/graphql-python/graphene-django/pull/1336 If you think the problem still exists, feel free to reopen this issue.
