### ISSUE TITLE
Resolving DjangoConnectionField when return None

### ISSUE THREAD

**Issue by arghodayah** [graphql-python/graphene-django#1329]
* **What is the current behavior?**
DjangoConnectionField resolves all objects of the requested DjangoObjectTypeNode when we return none in the resolver!

* **Steps to reproduce:**
```
class Query(object):
    test = DjangoConnectionField(SomeNode)
    
    def resolve_test(self, info, **kwargs):
        return None
```

* **What is the expected behavior?**
Should return an empty edges-nodes

* **Please tell us about your environment:**
  - Version: 2.15.0

* **Notes:**
Same behavior in mutations

**Comment by zsiciarz** [comment]
Run into that as well. This behavior violates the principle of least surprise. The solution is to use `<Model>.objects.none()` of course, but what is the reasoning behind magically resolving the default (`all()`) queryset against the expectations? This can cause a massive data leak and should at least be documented with a big fat warning.
