### ISSUE TITLE
Choice string converter should not force upper case

### ISSUE THREAD

**Issue by Waitak** [graphql-python/graphene-django#133]
The convert_choice_name function in converters.py forces all string choices to upper case. These are the values taken from the choices field of a Django model field. This is less than ideal because:

- It forces the developer to use upper case in GraphQL methods, even if lower or mixed case is used everywhere else in Django apps.
- If makes all choices silently case-insensitive. This silently imposes a constraint that Django does not impose, introducing very difficult-to-detect bugs.

It would be preferable for graphene_django to respect the developers' decisions on the case of choice elements, rather than force upper case. The fix is to replace:

    def convert_choice_name(name):
        name = to_const(force_text(name))
        try:
            assert_valid_name(name)
        except AssertionError:
            name = "A_%s" % name
        return name

with:

    def convert_choice_name(name):
        name = force_text(name)
        try:
            assert_valid_name(name)
        except AssertionError:
            name = "A_%s" % name
        return name

**Comment by adamdonahue** [comment]
Agreed.  A `CharField` should be strictly a character field.  I don't understand why this conversion is taking place at all.  Questionable design choice, especially for queries.

**Comment by EmiM** [comment]
They're converting CharField with choices to enum  (see `convert_django_field_with_choices` method) and enum is written uppercase in GraphQL. However this still makes no sense to me to display it uppercase by force.

**Comment by denis-ryzhkov** [comment]
Maybe someone adds `GRAPHENE_CONVERT_CHOICES_TO_ENUMS = False` setting to `graphene_django` once.
Until then, you can opt out with monkey-patch somewhere before schema is imported, for example in settings file.
Patch: https://gist.github.com/denis-ryzhkov/fcb944f6ebfad4775efb74848703f0d7

**Comment by reverie** [comment]
This is a poor design decision with an easy fix. PR submitted.

**Comment by phalt** [comment]
Discussion is focusing on #67 so closing this to avoid duplicate conversations.
