### ISSUE TITLE
Filtering docs point to wrong URLs

### ISSUE THREAD

**Issue by BenQuigley** [graphql-python/graphene-django#1333]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**

At this graphene docs page: https://docs.graphene-python.org/projects/django/en/latest/filtering/ -
- the hyperlink on "django-filter" in the first sentence 404s because it points to https://django-filter.readthedocs.io/en/master/
- it should point to https://django-filter.readthedocs.io/en/stable/
- and the next one, on "usage documentation", 404s because it points to https://django-filter.readthedocs.io/en/master/guide/usage.html#the-filter
- it should point to https://django-filter.readthedocs.io/en/stable/guide/usage.html#the-filter

I cloned the repo but the issue appears to have been fixed in [main](https://raw.githubusercontent.com/graphql-python/graphene-django/main/docs/filtering.rst), so maybe the site just needs to be republished?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar (you can use this template as a starting point: https://repl.it/@jkimbo/Graphene-Django-Example).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 
  - Platform: 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

**Comment by sjdemartini** [comment]
@firaskafri I see the code was updated to reference the new django-filter docs URL here https://github.com/graphql-python/graphene-django/pull/1399. What is the process to deploy it, since it looks like the live graphene/django docs site https://docs.graphene-python.org/projects/django/en/latest/filtering/ still has the old URLs?

**Comment by firaskafri** [comment]
@sjdemartini docs CI/CD seems to be broken. 
Pinging @syrusakbary

**Comment by ndpu** [comment]
@firaskafri docs still haven't been updated. It looks like fixing the build process didn't help...

**Comment by firaskafri** [comment]
@erikwrede can you help us with this?
