### ISSUE TITLE
Should enums have sub-selection of value, label and choices?

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#134]
I think it would be useful for enums to be able to have sub-selection where you access the value, label and choices. 

Ideally it would work like this
```python
class BeersEnum(graphene.Enum):
    LOGGER= 0 
    IPA = 1
    HEFEWEIZEN = 2


class Beer(DjangoObjectType):
     beer_type = graphene.NonNull(BeersEnum)

```
an example query would be

    query{
          beers(first:10){
               beerType: { 
                      value, 
                      label,
                      choices{
                           value,
                           label,
                      }
                }
          }
    }

so enums could resolve their choices as well as their value/label.

This would make creating selects from the choices very simple.
You would only have to do something like this in your frontend
```javascript
      //React Code
      createSelectOptions(enumField){
             var options = enumField.choices.map(choice=>{
                    return (
                          <option value={choice.value} key={choice.value}>
                                 {choice.label}
                          </option>
                   )
             })

             return (
                    <select value={enumField.value}>
                        {options}
                    </select>
             )
      }


```
Looking for feedback on if this makes sense!
I want to get some thoughts from other people before diving into an implementation.

**Comment by BossGrand** [comment]
Alternatively a way to override the enum registry to allow for a custom field may work

**Comment by BossGrand** [comment]
I ended up rolling my own custom solution that involves a custom model field, if anyone is interested feel free to comment here/pm me

**Comment by morinx** [comment]
@BossGrand I agree with both points you made above. I've seen different discussions/issues here that could have benefited from either of these two approaches. Also it would be great if you could share your work around.
