### ISSUE TITLE
using multi schema file for scale project

### ISSUE THREAD

**Issue by webafra** [graphql-python/graphene-django#1347]
hello.

If the project is big, the number of methods in one file will be too much. Therefore, it is better to use several separate files.

I noticed that only one schema file can be used in this package.

Is it possible to provide the ability to use multiple separate files?

for example:
blog.schema

category.schema

product.schema

and more ...

thanks.

**Comment by firaskafri** [comment]
You can achieve this by having separate schema files inside each app and then import them all in main schema.
