### ISSUE TITLE
Update codebase to work with Graphene 3+.

### ISSUE THREAD

**Issue by helgihg** [graphql-python/graphene-django#1349]
**Current behavior**:

Upgrading `graphene` to version 3+ fails due to the most recent version of `graphene-django` requiring `graphene<3,>=2.1.7`.

**To reproduce**:

```
# In a new Python environment (Python 3.9.2), run the following:
pip install graphene-django
pip install --upgrade graphene
```

**Expected behavior**:

The newest versions of `graphene` and `graphene-django` should be able to co-exist without conflict.

**Motivation / Use case for changing the behavior**:

Other libraries that make use of `graphene` rely on it being of a more recent version than the latest version that `graphene-django` supports, which is `graphene` version 2.1.9. Thus, projects are forced to use outdated packages, either of `graphene` or some other library relying on it. A specific example is [`graphene-django-optimizer`](https://pypi.org/project/graphene-django-optimizer/) which is now at version `0.9.1` but projects that use `graphene-django` must use `graphene-django-optimizer 0.8.0` because newer versions rely on `graphene` 3+.

**Environment**:  
- Version: graphene-django 2.15.0
- Platform: Debian GNU/Linux 11 (Bullseye)

**Comment by firaskafri** [comment]
This will be fixed in v3.0.0
