### ISSUE TITLE
Consider adding Hacktoberfest label

### ISSUE THREAD

**Issue by villelaitila** [graphql-python/graphene-django#1362]
**Is your feature request related to a problem? Please describe.**
There are not many maintainers. It might not be too late for this year hacktoberfest.

**Describe the solution you'd like**
Just adding the label will help optimizing visibility of this project.

**Describe alternatives you've considered**
N/A 

**Additional context**
N/A

**Comment by ulgens** [comment]
A bit late but done 🙁

**Comment by erikwrede** [comment]
Definitely on the list for next year though!
