### ISSUE TITLE
raise GraphQLError inside resolver gives me "Received incompatible instance error" after bumping from 3.0.0b7 to 3.0.0b8

### ISSUE THREAD

**Issue by zhoudaxia233** [graphql-python/graphene-django#1367]
* **What is the current behavior?**
* In graphene-django **3.0.0b8**
```python
class Query(ObjectType):
    me = graphene.Field(UserNode)
    def resolve_me(root, info):
        if user.is_anonymous or not user.is_active:
            raise GraphQLError("Unauthenticated.")
        return user
```
If I send the query without logging in, I get
"Received incompatible instance \"<Promise at 0x7ff118d710b1 rejected with GraphQLError('Unauthenticated.')>\"."

However, in **3.0.0b7**, if I send the same query without logging in, I get
"Unauthenticated." (And this is the behavior I expected.)

* **Please tell us about your environment:**

  - Version: graphene-django==3.0.0b8 graphql-core==3.1.7 graphql-relay==3.1.1
  - Platform: Ubuntu

**Comment by dobsonjon** [comment]
I'm having the same issue in 3.0.0  (clean install with `pip install graphene-django`)

- graphene                   3.1.1
- graphene-django      3.0.0
- graphql-core             3.2.3
- graphql-relay            3.2.0

test case:
```python
class Query(graphene.ObjectType):
    hello_world = graphene.String()

    def resolve_hello_world(root, info):
        raise GraphQLError("hello error")
        return "hello"

schema = graphene.Schema(query=Query)
```

query:
```graphql
{
    helloWorld
}
```

result (unexpected behavior):
```json
{
  "data": {
    "helloWorld": "<Promise at 0x109c77550 rejected with GraphQLError('hello error')>"
  }
}
```

result (expected behavior) using same code and query with previous release:

- graphene                   2.1.9
- graphene-django      2.15.0
- graphql-core             2.3.2
- graphql-relay            2.0.1

```json
{
  "errors": [
    {
      "message": "hello error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "helloWorld"
      ]
    }
  ],
  "data": {
    "helloWorld": null
  }
}
```

**Comment by zhoudaxia233** [comment]
@dobsonjon Hi, I found a workaround and maybe this is helpful for you. This issue is caused by their update on the default `DjangoDebugMiddleware`, however, this is customizable. [Here](https://docs.graphene-python.org/projects/django/en/latest/debug/)
I just copy the old code and create a `MyDjangoDebugMiddleware` file, and replace the default one by specifying the path in the GRAPHENE settings.
```python
GRAPHENE = {
    ...
    'MIDDLEWARE': [
        'myproject.middlewares.MyDjangoDebugMiddleware',
    ]
}
```
Hope this helps.

**Comment by dobsonjon** [comment]
Thanks @zhoudaxia233 

Would that affect me even if I'm not using graphene's debug middleware? I have not enabled that feature explicitly anyway. My graphene settings just look like this:
```python
GRAPHENE = {
    "SCHEMA": "helloworld.schema.schema"
}
```

I do see a difference in this behavior when running on Django's built-in server vs a web server though. When running in my staging environment - (Django + GUnicorn + Caddy2), the errors section of the response appears as expected.

When running locally using Django's development server with `DEBUG=False`, the errors are also formatted correctly. However, when encountering multiple errors, I only get the first one.

When running locally using Django's development server with `DEBUG=True`, I get the `"<Promise at 0x109c77550 rejected with GraphQLError('hello error')>"` response I quoted above.

So it's not unusable, but this difference in behavior makes it very difficult to test effectively.

I'm using Django 3.2.16 if that matters.

**Comment by dobsonjon** [comment]
Ok @zhoudaxia233  I followed your suggestion and defined a custom DjangoDebugMiddleware class with the following change to the original class found in `graphene_django.debug.middleware` using the suggested edit:
 ```patch
<         try:
<             promise = next(root, info, **args)
<         except Exception as e:
<             return context.django_debug.on_resolve_error(e)
---
>         promise = next(root, info, **args)
```

and added that to my graphene settings:
```python
GRAPHENE = {
    "SCHEMA": "helloworld.schema.schema",
    "MIDDLEWARE": ['helloworld.schema.DjangoDebugMiddleware']
}
```

This solved my issues when running in debug mode. Thanks again @zhoudaxia233 for your help with this!

**Comment by khasbilegt** [comment]
@zhoudaxia233 's suggestion only solves the wrong value of message field in errors. However, it also removes the DjangoDebugMiddleware's ability to log and track exceptions in debug env. In order to get correct error message and working debug middleware, seems like the error_formatter method can be overwritten as the following.

```
@staticmethod
def format_error(error):
    if isinstance(error, Promise):
        error = error.reason

    if isinstance(error, GraphQLError):
        return error.formatted

    return {"message": str(error)}
```

**Comment by LVladymyr** [comment]
Version: graphene==3.2.1 graphene-django==v3.0.0 still actual.
