### ISSUE TITLE
Improving the icontains filter

### ISSUE THREAD

**Issue by dudanogueira** [graphql-python/graphene-django#138]
Hi there! Thanks for this awesome lib!!

I was wondering, as I plan to migrate from DRF, if is it possible to improve the icontains.

At DRF the search for "JOSE NOGUEIRA" will split the string and search the all the list. I was able to kind of implement this as following:

    def resolve_todos_beneficiarios(self, args, context, info):
        nome_contains = args.get('nome__icontains', None)
        if nome_contains:           
            queries = nome_contains.replace(',', ' ').split()
            qset1 =  reduce(operator.__and__, [Q(nome__icontains=query) for query in queries])
            return Beneficiario.objects.filter(qset1).distinct()

the problem here is that, when applied with another filter, let's say:

query{
  teste: todosBeneficiarios(nome_Icontains: "JOSE NOGUEIRA", cpf: "123456"){
    edges{
      node{
        nome
        nomeDaMae
      }
    }
  }
}

it will only apply the first filter.

My question is, what's the best approach for overring the icontain filter?

Thanks!!!

**Comment by mvanlonden** [comment]
@dudanogueira you can define custom filtersets http://docs.graphene-python.org/projects/django/en/latest/filtering/#custom-filtersets
