### ISSUE TITLE
GraphiQL v2.4.1 won't run IntrospectionQuery properly

### ISSUE THREAD

**Issue by sparktx-adam-gleason** [graphql-python/graphene-django#1402]
* **What is the current behavior?**

GraphiQL update to v2.4.1 won't load properly. Loading up the page gives this error 
```json
{
  "errors": [
    {
      "message": "Must provide query string."
    }
  ]
}
```

Investigating the Network tab  shows the IntrospectionQuery is giving a 400 error. I've tested the query against my app using Postman and it works correctly.

Queries against the `/graphq/` endpoint using Postman also work.

Just the update to the new interface for GraphiQL seems to break.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar (you can use this template as a starting point: https://repl.it/@jkimbo/Graphene-Django-Example).

[Example repo here](https://github.com/fullrobot/grapqhl_example)

1. Clone repo
2. pip install requirements
3. navigate to `localhost:8000/graphql/` to see error.

* **What is the expected behavior?**

GraphiQL view works properly.

* **Please tell us about your environment:**

  - Version: graphene-django==3.0.1
  - Platform: MacOS

> NOTE: GraphiQL works fine on graphene-django==3.0.0

**Comment by kiendang** [comment]
I just ran into this as well. Investigating.

**Comment by dicknetherlands** [comment]
I also had this problem.
