### ISSUE TITLE
_names_ are reserved for future Enum use

### ISSUE THREAD

**Issue by Thibaut-Fatus** [graphql-python/graphene-django#141]
Hi,

We run into this problem when using a CharField with choices, but only on the first choice, and the error disappears when we surround the value of the charfield by double underscores:

```
   # this does not work, whatever you choose to set in place of percentage ...
    PERCENTAGE = "percentage",
    AMOUNT = "amount"
    DEAL_TYPES = (
        (PERCENTAGE, "percentage"),
        (AMOUNT, "amount"),
    )

   # ... unless you use '__':
    PERCENTAGE = "__percentage__",
    AMOUNT = "amount"
    DEAL_TYPES = (
        (PERCENTAGE, "__percentage__"),
        (AMOUNT, "amount"),
    )

   # [...]
    type_of_deal = CharField(max_length=14,
                             choices=DEAL_TYPES)
```

Tested on 2 different machines (both MacOS)

graphene==1.2
graphene-django==1.2.1
graphql-core==1.0.1
graphql-relay==0.4.5

**Comment by Thibaut-Fatus** [comment]
the code leading to this error lives in graphene:
https://github.com/graphql-python/graphene/blob/6c7cd4e4fa6e29f55ebf02f173281d46d9f8fc1c/graphene/pyutils/enum.py

but it seems more likely to be an issue with graphene-django

**Comment by Thibaut-Fatus** [comment]
and switching constants declaration and use in the tuple allows us to use 'percentage' in combination of whatever we want as long as it's surrounded by double underscores.

```
    AMOUNT = "__amount__",
    PERCENTAGE = "percentage"
    DEAL_TYPES = (
        (AMOUNT, "__amount__"),
        (PERCENTAGE, "percentage"),
    )
```

**Comment by tamhv** [comment]
i got this issue, i can't use double underscores with ChoiceField from rest framework, always invalid_choice for double underscores choice
```
    def to_internal_value(self, data):
        if data == '' and self.allow_blank:
            return ''

        try:
            return self.choice_strings_to_values[six.text_type(data)]
        except KeyError:
            self.fail('invalid_choice', input=data)
```
