### ISSUE TITLE
method support for Node Field

### ISSUE THREAD

**Issue by KristofDM** [graphql-python/graphene-django#142]
Hey, 

I read another issue on here that explained how you could add a custom field to your Node. However, after this not working I inspected the graphene-django code and found that the source parameter only worked for fields of the model or regular functions but not methods.

A demonstration, the following code would not work and resulted in a the following error:
`      "message": "Received incompatible instance \"<bound method Recipe.get_allergens of <Recipe: are allergens saved?>>\"."
`

    class FooNode(DjangoObjectType):
        my_method_field = graphene.Field(AllergensNode, source='get_value')
        # get_value() is a method of the Foo model
        class Meta:
            model = Recipe
            only_fields = ('my_method_field', )
            interfaces = (relay.Node, )

I traced this back to the _source_resolver_ function in graphene/types/field.py. 
This was:
`    if inspect.isfunction(resolved):
        return resolved()
`
Changing this to the following solved the issue:
`    if inspect.isfunction(resolved) or inspect.ismethod(resolved):
        return resolved()
`

I think this is the actual desired behaviour?

**Comment by BossGrand** [comment]
@KristofDM the way you add methods to nodes is as follows:

```python

class FooNode(DjangoObjectType):
    my_method_field = graphene.Field(AllergensNode')

    def resolve_my_method_field(instance, args, request, info):
        return instance.allergens
```

a node looks for resolve functions that match the name of the field on them. Thats how they resolve which methods should trigger when a field is accessed.
