### ISSUE TITLE
Please document using csrf_exempt for read-only POST APIs

### ISSUE THREAD

**Issue by camd** [graphql-python/graphene-django#146]
I have a ReactJS application that is hosted on a separate domain from my Django app.  But the library (Apollo) currently only makes requests with POST.  Since I have no mutations in my Graphene implementations, it's pretty safe for me to use ``csrf_exempt`` for my GraphQL view.

Would you be able to add that to your documentation somewhere so that people know this is an option.  Would you also be able to confirm that I'm correct in my deduction?  :)  If it's still possible to write to GraphQL without mutations, I'll need to look for a different solution.

Thanks!!

**Comment by khankuan** [comment]
Related question: Is it possible to tie csrf only to Mutations?

**Comment by johandc** [comment]
:+1:
I had to install django-cors-headers to make the apollo client work.

**Comment by edmorley** [comment]
Not stale

**Comment by phalt** [comment]
Simply wrapping the view in a `csrf_exempt` is enough but yes, we should add this to the docs:
```python
from django.views.decorators.csrf import csrf_exempt

url(r'^graphql', csrf_exempt(GraphQLView.as_view(schema=schema)), name='graphql',),
```

**Comment by edmorley** [comment]
> Not stale
