### ISSUE TITLE
ModelInputObjecttypes

### ISSUE THREAD

**Issue by elyashedayat0101** [graphql-python/graphene-django#1463]
Can we Have sth like ModelInputObjecttypes for our Input

**Comment by sjdemartini** [comment]
@elyashedayat0101 The "New issue" -> "Feature request" form had several prompts to help us understand what you're requesting:

> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

Without it, we simply do not have enough information about what you're asking. I'm going to close this out, but if you can provide more context, we can reopen. Please do not spam graphene-django Issues with this sort of thing. Thanks.
