### ISSUE TITLE
Provide context for polymorphic type resolution to ancestor classes.

### ISSUE THREAD

**Issue by adamdonahue** [graphql-python/graphene-django#149]
We can use

```python
def resolve_type(self, ...):
    # Return appropriate GraphQL type.
```

when defining a new union type.  But I don't see a way to expose the type of object a user which to see details for from this function, meaning, `resolve_type` doesn't seem to allow for true polymorphism.

If a type B is also a type A, in theory a union should allow types ['A', 'B'], and resolve_type would resolve the object to either B or A depending on the `... on <type>` the user has requested.

Is this possible, and would that kind of query make sense to support?  It would be useful, to avoid queries of the type:

```graphql
{
    file: {
        ... on Directory {
           name
        }
        ... on Symlink {
          name
        }
        ... on RegularFile {
          name
        }
    }
}
```

Food for thought.

**Comment by 0xCMP** [comment]
I am also having issues trying to get this to work. I've managed to get the first level working

> *Names changed to protect the innocent*

```
class PolyDjangoConnectionField(DjangoConnectionField):
    def get_manager(self):
        return self.model._default_manager.non_polymorphic()

class MyNode(DjangoObjectType):
    children = PolyDjangoConnectionField('graphql_api.schema.MyNode')

    class Meta:
        model = MyModel
        filter_fields = ['title']
        interfaces = (relay.Node,)

    @classmethod
    def get_node(cls, id, context, info):
        try:
            return cls._meta.model.objects.non_polymorphic().get(pk=id)
        except cls._meta.model.DoesNotExist:
            return None

class Query(graphene.ObjectType):
    all_models = PolyDjangoConnectionField(MyNode)
```

This works for a simple query like this

```
{
  allModels(first:2) {
    edges{
      node{
        id
        title
        slug
        parent {
          id
        }
      }
    }
  }
}
```

However anything that is requesting the same type as children (i.e. using MPTT) can not be fixed right now because they query set stops using `non_polymorphic()`.

```
{
  allModels(first:2) {
    edges{
      node{
        id
        title
        slug
        parent {
          id
        }
        children {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

I wish there was a way to replace the base QuerySet.

**Comment by 0xCMP** [comment]
To support any field which uses `django-polymorphic` simply resolve that field yourself like this

```
class MyNode(DjangoObjectType):
    # REMOVE THIS
    # children = PolyDjangoConnectionField('graphql_api.schema.MyNode')
   [...]
    def resolve_children(self, args, context, info):
        return MyModel.objects.non_polymorphic()
```

**Comment by adamdonahue** [comment]
I intended to close this, my mistake.

This is, indeed, the approach we're taking, but one unfortunate thing is that it appears non-trivial to dynamically determine the typing spread the query is using from a `resolve` call.  (I'm not even sure it makes sense within the context of GraphQL to allow for that.)

That is, if we have three types:

```
class A:
    name

class B(A):
    bSpecificField

class C(A)
    cSpecificField
```

I can use:

```
{
    items: {
        ... on B {
            name
            bSpecificField
        }
        ... on C {
            name
            cSpecificField
        }
    }
}
```

but I cannot appear to use:

```
{
    items: {
        ... on A {
            name
        }
    }
}
```

I mean, I suppose I could do this if I knew the query was asking for A when resolving the classes, but I'm not convinced this is the right approach.

A second interesting wrinkle is that determining the type of objects returned in a union seems to be only possibly by introspecting those objects themselves, or by exposing a field specifically stating that type, as in:

```
{
    items: {
       ... on B {
           type       # Always "B"
           name
       }
    }
}
```    

These are minor items, and I only began looking at GraphQL yesterday so it's quite possible I'm ignorant at this point to more sophisticated (or recommended, at least) approaches.

**Comment by adamdonahue** [comment]
@0xCMP By the way, if you want to recursively refer to a type you can pass a function returning the type name in place of the actual type itself in the field definition.

**Comment by kimutaiRop** [comment]
sorry to comment after this is closed but what is the shared columns are so many, would it not be better if I was able to get all those shared in outer scope of all the `... on` for instance something like this
```
{
    items: {
            name
        ... on B {
            bSpecificField
        }
        ... on C {
            cSpecificField
        }
    }
}
```

how can I achieve such. thanks
