### ISSUE TITLE
Is it possible to add a schema path?

### ISSUE THREAD

**Issue by Designer023** [graphql-python/graphene-django#150]
Hi,

I'm using this in conjunction with reactjs and one of the files I need is the schema.json or at least the contents of it. I have been using the `manage.py graphql_schema` command to create the file and then copy it across to the react project, however this is not really the best from a workflow point of view.

Currently I'm just going to generate the schema into my templates folder and render directly which is still not ideal.

Is there a way to setup url that will generate an up to date schema that my react app can query as needed.

Does this exist or is there some better way I can do this?

Thanks 👍 

Carl

**Comment by dopeboy** [comment]
Could you setup your own endpoint that then runs this [command](https://github.com/graphql-python/graphene-django/blob/9a43f65b445abe49b9a34ce4b64c6384a3cd666f/graphene_django/tests/test_command.py#L9)
