### ISSUE TITLE
Serializer mutation choice field creation fails with django-rest-framework 3.15.0

### ISSUE THREAD

**Issue by MrThearMan** [graphql-python/graphene-django#1507]
## What is the current behavior?

See title. This is due to an [`isinstance` check in `converters.get_choices`](https://github.com/graphql-python/graphene-django/blob/54372b41d501229abdf21d8109a548fe60772b1a/graphene_django/converter.py#L73-L77) that changes the iterable if the choices are an OrderedDict. Django REST Framework 3.15.0 [changed from OrderedDicts to regular dicts](https://www.django-rest-framework.org/community/release-notes/#315x-series:~:text=Replaced%20OrderedDict%20with%20dict%20%5B%238964%5D), so this check no longer converts the iterable, meaning the loop now tries to iterate the dict by keys, but unpack it to two variables, which is not possible.

I've created an example repo reproducing the issue: https://github.com/MrThearMan/graphene-django-bug. The repo contains the exact traceback for the error.

## What is the expected behavior?

I should be able to use serializer mutations with choice fields in DRF 3.15.0. 

Changing the `isinstance` check to `isinstance(choices, dict)` should solve the issue without any breaking anything for older versions of DRF, as OrderedDicts are subclasses of dicts.

**Comment by MrThearMan** [comment]
Seems like there is already a pull request for this: https://github.com/graphql-python/graphene-django/pull/1506. Should've checked those first 😄

**Comment by kiendang** [comment]
@MrThearMan #1506 has been merged. Please check if that fixes the issue. Feel free to reopen the issue if that's not the case.

**Comment by MrThearMan** [comment]
Thanks, works like a charm! A patch release for this would be much appreciated!

**Comment by MrThearMan** [comment]
@kiendang Would you be able to release a v3.2.1 with this fix to PyPI?

**Comment by kiendang** [comment]
Pinging @firaskafri. When you have time could you look at making a patch release v3.2.1? Thanks!

**Comment by MrThearMan** [comment]
@kiendang @firaskafri Any updates on the PyPI?
