### ISSUE TITLE
Loaddata does not work in cookbook example

### ISSUE THREAD

**Issue by ridwanrahman** [graphql-python/graphene-django#152]
I tried to loaddata dummy_data.json but it kept giving me this error. Here's a screenshot

![image](https://cloud.githubusercontent.com/assets/17476457/25088858/8e045336-239b-11e7-8bb1-7cee7c78971a.png)

**Comment by gamesbrainiac** [comment]
What python version are you using?

**Comment by OlivierKnell** [comment]
Did you add the app into your INSTALLED_APPS in your settings.py?
