### ISSUE TITLE
default ordering in minor version breaks changes and compatibility

### ISSUE THREAD

**Issue by alamoureux** [graphql-python/graphene-django#1520]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **What is the current behavior?**

Since [3.2.1](https://github.com/graphql-python/graphene-django/releases/tag/v3.2.1) , we must patch every django.Model that don't implement Meta.ordering.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
a github repo, https://repl.it or similar (you can use this template as a starting point: https://repl.it/@jkimbo/Graphene-Django-Example).

```
class Event(models.Model):
    class Meta:
        ordering = None
```

* **What is the expected behavior?**

- Aa a patch, a retro compatible version ;
- More way to implement relay ordering ;
- Warnings or deprecation warnings for relay queries where ordering is not implemented.

* **What is the motivation / use case for changing the behavior?**

Lack of retro compatibility.
And to use relay, we have to modify the behaviour of all our Models. That means implementing a default ordering directly on django ORM level instead of graphene API level.

It is discouraged by django itself (https://docs.djangoproject.com/en/5.0/ref/models/options/ , see warning about **Options.ordering**).

* **Please tell us about your environment:**

  - Version: 3.2.1
  - Platform: linux

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

It will be usefull and safer to have more options to configure it : 

- like in settings.py, something like `GRAPHENE["RELAY_DEFAULT_ORDERING_FIELD"]=["pk"]` 
- a meta field like `DjangoObjectType.Meta.ordering=["pk"]`)

Regards,

**Comment by kiendang** [comment]
Fixed in #1518 @firaskafri could you help make a v3.2.2 release?
