### ISSUE TITLE
Could not import 'myapp.schema.schema' for Graphene setting 'SCHEMA'. ModuleNotFoundError: No module named 'urllib3.packages.six.moves'.

### ISSUE THREAD

**Issue by hazho** [graphql-python/graphene-django#1524]
* **What is the current behavior?**

when tunning server and visiting the site, I get the error :
Could not import 'framework.schema.schema' for Graphene setting 'SCHEMA'. ModuleNotFoundError: No module named 'urllib3.packages.six.moves'.

the related setting part is:

GRAPHENE = {
    'SCHEMA': 'framework.schema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}
 and the module "framework/framework/schema.py" already created based on the documentations in graphene and django-graphene

* **What is the expected behavior?**

simply running without this error

* **Please tell us about your environment:**

  - Version: python 3.12
  - Platform: ubuntu-server 24

**Comment by kiendang** [comment]
you need the python six package
