### ISSUE TITLE
Allow generation schema.graphql for Relay-Modern compatibility

### ISSUE THREAD

**Issue by femesq** [graphql-python/graphene-django#153]
The recently [released](https://facebook.github.io/relay/docs/relay-compiler.html) `relay-compiler` needs and different format of schema: [example](https://github.com/relayjs/relay-examples/blob/32f6beb3cf4ec1b51ac013b9a274d157a607f375/TodoMVC/data/schema.graphql)

Was trying to manage a way of getting current types, similar to an introspection query:
```
{
  __schema {
    queryType {
      name
    }
    mutationType{
      name
    }
    types {
      name
      possibleTypes {
        kind
        name
        description
      }
    }
  }
}
```

But was getting some "native" types...

What would be the best strategy to help implementing this?
My initial idea was to implement an similar method to [this](https://github.com/graphql-python/graphene/blob/master/graphene/types/schema.py#L84) and the, create/adapt an management command to call it [similar to this one](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/management/commands/graphql_schema.py#L92).

Thanks,

**Comment by femesq** [comment]
In the meanwhile, [this[(https://github.com/facebook/relay/issues/1639#issuecomment-295314954) `js` code should help...

**Comment by femesq** [comment]
Have done some more tests, and now (using Relay `rc2`), it works pointing to `schema.json`. The problem is that the root query **must** be named `Query`, so I've got to rename the base `class` on Django...
Opened [this issue](https://github.com/facebook/relay/issues/1667).

**Comment by bmcdaniel11** [comment]
Linking the [ core issue ](https://github.com/facebook/relay/issues/1624) for this problem
