### ISSUE TITLE
dunder '__', is reserved by GraphQL introspection

### ISSUE THREAD

**Issue by Yankzy** [graphql-python/graphene-django#1533]
Just upgrade to graphene-django 3.1.x now getting this in Graphiql
`{
  "errors": [
    {
      "message": "Name '__1' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__2' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__1' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__2' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__1' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__2' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__1' must not begin with '__', which is reserved by GraphQL introspection."
    },
    {
      "message": "Name '__2' must not begin with '__', which is reserved by GraphQL introspection."
    }
  ]
}`

**Comment by wimble3** [comment]
@Yankzy look at that shit again, its not completed. After migration your graphql query just crashed with this error.
For example:
1) i have model with "operator" varchar field
2) i make a desition to rename this field to "condition_operator"
3) rollback migration -> rename field -> makemigrations -> migrate
4) this error raises via graphql query

Maybe its just 1 point for that error, seems like its more than one.
I can try to do PR for this if you want
