### ISSUE TITLE
Registration mutation example?

### ISSUE THREAD

**Issue by mraak** [graphql-python/graphene-django#158]
Is there an example how to do a usual registration flow with this. Register, Activate, Login, Logout, ForgotPassword? 

Say if this was a backend for a mobile app.

**Comment by creimers** [comment]
@mraak I have an example app in my namespace in which I was exploring exactly that: https://github.com/creimers/graphene-auth-examples-relay

**Comment by mvanlonden** [comment]
Thanks @creimers
