### ISSUE TITLE
Executing a node directly?

### ISSUE THREAD

**Issue by Speedy1991** [graphql-python/graphene-django#161]
Is there a programatically way to run a Node scheme programatically? without a query?
The Usecase is a new created Model instance and i want to get the executed query of this new db entry.

Example:
```
u = User(name="paul")
Any black magic code running a query like this:
{
  user(id: u.id) {
    u.__all_fields__
  }
}
```
should return
```
{
  "data": {
    "user": {
      "id": 1
      "name": "TestUser"
    }
  }
}
```
At the moment i have to create this query always manually by formating a base string.

**Comment by mvanlonden** [comment]
@Speedy1991 you can execute a query against your schema. https://docs.graphene-python.org/en/latest/quickstart/#querying
