### ISSUE TITLE
When creating Mutation I get: AttributeError: 'Options' object has no attribute 'name'

### ISSUE THREAD

**Issue by mraak** [graphql-python/graphene-django#163]
Created simple Queries with no issues. No trying to create a Mutation and getting this error.

```
  File "C:\Program Files\Python36\lib\site-packages\graphene\types\typemap.py",
line 236, in construct_fields_for_type
    field_type = self.get_field_type(map, field.type)
  File "C:\Program Files\Python36\lib\site-packages\graphene\types\typemap.py",
line 295, in get_field_type
    return map.get(type._meta.name)
AttributeError: 'Options' object has no attribute 'name'
```

This is the code

```py
class AddProduct(graphene.Mutation):
    class Input:
        name = String(required=True)

    product = Field(Product)
    org = Field(Org)

    @classmethod
    def mutate(cls, input, context, info):
        product_name = input.get('product_name')
        org = Org.objects.first();
        desc = "description whatever...."
        product = Product(name = product_name, org = org, description = desc)

        return AddProduct(product = product)

class Mutation(ObjectType):
    add_product = AddProduct.Field()

```

**Comment by colanconnon** [comment]
Without knowing more about your code, I assume you are using Product and Org from your models and not making them into graphql types. If you make product and Org into graphene types this should work.

**Comment by mraak** [comment]
Still the same. I replaced model class with ProductNode (DjangoObjectType) inside the mutation class and I get the same error. 

```py

import graphene
from graphene import relay, ObjectType, AbstractType, List, String, Field
from graphene_django.types import DjangoObjectType
from graphene_django.filter import DjangoFilterConnectionField
from .models import Product
from orgs.models import Org



class ProductNode(DjangoObjectType):
    class Meta:
        model = Product
        filter_fields = {
            'name': ['exact', 'icontains', 'istartswith'],
            'org__name': ['icontains'],
            'org__admin__username':['icontains'],
        }
        interfaces = (relay.Node, )


class AddProduct(graphene.Mutation):
    class Input:
        name = String(required=True)

    product = Field(ProductNode)
    org = Field(Org)

    @classmethod
    def mutate(cls, input, context, info):
        product_name = input.get('product_name')
        org = Org.objects.first();
        desc = "description whatever...."
        product = ProductNode(name = product_name, org = org, description = desc)

        return AddProduct(product = product)


class Query(AbstractType):
    all_products = DjangoFilterConnectionField(ProductNode)

    def resolve_all_products(self, args, context, info):
        return Product.objects.all()

class Mutation(ObjectType):
    add_product = AddProduct.Field()


```

**Comment by colanconnon** [comment]
**However in the mutate method, do I still have to use model class to retrieve the Org I want?**
 yes, you need to query using django models and then you can return those in your mutate method and they will automatically get mapped to graphql types.


Scanning over your code quickly i see one problem. you need to return org in your mutate method
        return AddProduct(product = product, org=org)

**Comment by mraak** [comment]
Return org=org, or org=OrgNode(org), and what is the difference?

Obviously I would need to know what _DjangoObjectType_ does and what all powers does it have, but that is not very well documented. It would be great to see the complete reference for these basic types.

**Comment by picturedots** [comment]
Having also just stumbled on this just following the mutation example in the docs ( http://docs.graphene-python.org/en/latest/types/mutations/) , it seems that the exception message could be a bit more helpful.

**Comment by keeth** [comment]
This one tripped me up too!  Part of the confusion for me is the examples and docs using inconsistent naming for the various classes.  An explicit naming convention like OrgModel, OrgType and OrgNode (and not the ambiguous Org) would help here, as well as a more helpful error message.
