### ISSUE TITLE
Getting 405 error when calling graphql from JS

### ISSUE THREAD

**Issue by mraak** [graphql-python/graphene-django#168]
I installed [corsheaders](https://github.com/ottoyiu/django-cors-headers), and set to allow all. But I'm still getting the error. I'm using isomorphic-fetch but I guess the error would appear regardless. 

```
INSTALLED_APPS = [
...
'corsheaders',
]


CORS_ORIGIN_ALLOW_ALL = True
```

```
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
:8000/#/repos/facebook/react?_k=d4wsv1:1 

Fetch API cannot load http://localhost:8000/graphql. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by NSLS** [comment]
The error is in your corsheaders configuration, try setting 
```
CORS_ORIGIN_WHITELIST = (
    'front.local.com'
)
```
in your settings.py file

**Comment by mraak** [comment]
My frontend host is the same localhost:8000 where my Django app runs. It's just some javascript in one of the template files. 

Anyway I tried doing what you suggested but I still get the same error.

I tried with one and both of these lines, I tried with and without port numbers but I always get 405.
```
CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = (
    '127.0.0.1',
    'localhost',
)
```

**Comment by NSLS** [comment]
In your urls.py, where you include the GraphQL view, did you set graphiql=False?

**Comment by mraak** [comment]
No, should I? I want my graphiql to still work.

**Comment by mraak** [comment]
This SO answer solved it. http://stackoverflow.com/questions/43869303/django-returns-403-error-on-post-request-with-fetch/

**Comment by alireza2000sajedi** [comment]
`gfhfgh`
