### ISSUE TITLE
ValueError max() arg is an empty sequence on GET request batch url

### ISSUE THREAD

**Issue by mvdwaeter** [graphql-python/graphene-django#169]
ValueError exception occurs when you have a batch API url and do a GET request to it without any parameters:

        urlpatterns = [
            url(r'^graphql/batch/$', GraphQLView.as_view(batch=True)),
        ]

This issue has been reported earlier, with a fix, but it is not in master: #105

**Comment by spockNinja** [comment]
PR #117 is in master, and it fixes the problem for an empty JSON request.

I am curious as to how you are using that endpoint to generate that error. Is it just by visiting that url in a browser? Or do you have some dynamic query building that somehow results in a completely empty request?

#278 is attempting to solve this issue. However, with #117's precedent, we might want a solution that catches this empty request and provides a more helpful error message.

If there is some sort of dynamic query building that results in an empty query, I think it would be on the query builder to not issue the empty query at all, as it is a waste of network resources.

**Comment by ideallical** [comment]
hi @spockNinja, thanks for the reply. But as I no longer have access to the project were I found this issue, let's consider this issue closed.
