### ISSUE TITLE
Unable to parse FilePathField

### ISSUE THREAD

**Issue by wklm** [graphql-python/graphene-django#171]
Hey,

my model includes a property of type "FilePathField". While calling the /graphql endpoint i'm getting the following  error:

`Don't know how to convert the Django field certificate.Certificate.path (<class 'django.db.models.fields.FilePathField'>)`

I have the latest version of the pip package 

@syrusakbary you can assign me to this issue, i'll try to solve it and submit pr

cheers,
Wojtek

**Comment by funkjunky** [comment]
See https://github.com/graphql-python/graphene-django/issues/96
I created a merge request, but I didn't even look at the contributing guidelines, because it is a single line fix.

**Comment by mvanlonden** [comment]
Fixed here https://github.com/graphql-python/graphene-django/pull/366#issuecomment-394869564
