### ISSUE TITLE
DjangoFilterConnectionField filter_fields on date

### ISSUE THREAD

**Issue by khankuan** [graphql-python/graphene-django#176]
Hi, I am using filter_fields on date. It seems like dates are interpreted as strings but django-filters expects a date object. Anyone faced the same issue before? Cheers

**Comment by vladimir-chernenko** [comment]
Same here

**Comment by vladimir-chernenko** [comment]
Fix has been already added in master branch, you just need to build it from it

https://github.com/graphql-python/graphene-django/blob/master/graphene_django/converter.py#L124

**Comment by lucas-bremond** [comment]
@vladimir-chernenko This is totally the solution, thank you so much!

**Comment by brno32** [comment]
While this works for `exact`, I can't get it to working with other field lookups like `year` or `year__gt`. I'm on the latest version of everything as of day

**Comment by zbyte64** [comment]
#805 Should fix this but we should add a test
