### ISSUE TITLE
Enforcing filters over a filterset by default

### ISSUE THREAD

**Issue by LegoStormtroopr** [graphql-python/graphene-django#188]
This challenge is how can I enforce additional restrictions on a foreign key by default, based on known filters in a queryset manager on a model.

For example, a database has posts some which aren't published and aren't visible.

```
class ArticleQuerySet(models.QuerySet):
    def visible(self, user):
        if user.is_superuser:
            return self
        return self.filter(publish=True)

class Article(models.Model):
    objects = ArticleManager()
    title = fields.TextField()
    is_published = fields.BooleanField()

class Comment(models.Model):
    article = fields.ForeignKey(Article)
    comment = fields.TextField()
```

I know that I can properly resolve posts to keep these hidden:

```
class Query(graphene.AbstractType):
    all_articles = DjangoFilterConnectionField(ArticleType)
    all_comments = DjangoFilterConnectionField(CommentType)

    def all_posts (self, args, context, info):
        return Article.objects.visible(context.user)
```

But if I also want to query by comments, like so:

```
class Query(graphene.AbstractType):
    all_articles = DjangoFilterConnectionField(ArticleType)
    all_comments = DjangoFilterConnectionField(CommentType)

    def all_posts (self, args, context, info):
        return Article.objects.visible(context.user)
```

By default, I can actually see into the uncommented posts:
```
query {
  allComments {
    comment
    postSet {
      title 
      published
    }
  }
}
```

The above query allows me to access all articles, even if I'm not a superuser! So, is there some way (Django-, or Graphene-based) that allows me to prevent users from querying into objects they haven't got permission to?

**Comment by arianon** [comment]
```python
def all_comments(self, args, context, info):
    queryset = Comment.objects.all()
    if context.user.is_superuser:
        return queryset
    
    queryset = queryset.select_related('article')
    queryset = queryset.filter(article__is_published=True)
    return queryset
 ```

Untested, but should work.

**Comment by LegoStormtroopr** [comment]
Sorry, I should have been clearer, in my actual app, those models are deeply nested.

Is there some way I can limit the queryset, based on the user, no matter how deep in the graph I am?

I've got as far as using `@convert_django_field.register(ArticleManyToOneRel)`  to declare my own way to have an `ArticleForeignKey` recognised and limit the reversed queryset, but I can't limit it when its just accessing the original field.
