### ISSUE TITLE
Is there any working example with Interfaces and DjangoObjectType(s)?

### ISSUE THREAD

**Issue by alexche8** [graphql-python/graphene-django#191]
Didn't find any structured information about that. Only some mentions and discussion on github bug pages and some of them is out of date.
Is interface feature exists in graphene-django?
If not - can someone help me to figure out how to use python-graphe's Interface with graphene-django DjangoObjectType ?
Thanks.

**Comment by BossGrand** [comment]
@alexche8 
interfaces work just fine with graphene-django, just include your interface in your interfaces tuple under the meta class of your DjangoObjectType

http://docs.graphene-python.org/en/latest/types/interfaces/

I'll give you an example that I use in my project
```python
class FileNodeInterface(graphene.Interface):
    id = graphene.GlobalID()
    url = graphene.String()
    is_display = graphene.Boolean()
    is_pdf = graphene.Boolean()
     

class ImageNode(DjangoObjectType):
    def resolve_url(self, args, request, info):
        return self.image.url

    def resolve_is_pdf(*_):
        return False


    class Meta:
        interfaces = (Node, FileNodeInterface)
        model = MasterlistingImages


class FlyerNode(DjangoObjectType):

    def resolve_url(instance, args, request, info):
        return instance.file.url
    
    def resolve_is_pdf(*_):
        name = instance.file.name
        return name[-3:] == 'pdf'



    class Meta:
        interfaces = (Node, FileNodeInterface)
        model = MasterlistingFlyers
```

**Comment by alexche8** [comment]
@BossGrand , thank you very much for example!
My goal of using interfaces is provide request to basic class but handle different field names depends of classes that implement that interfaces. Like on this example:
http://graphql.org/learn/schema/#union-types

Are you able to get similar working query like?:
`{
  someQuery {
    id 
    url 
    isDisplay 
    isPdf 
    ... on ImageNode {
       someSpecialFieldForImage
    }
    ... on FlyerNode {
       someSpecialFieldForFlyer1
       someSpecialFieldForFlyer12
    }
  }
}`

**Comment by alexche8** [comment]
Just noticed, that for solving this problem I need to use Union instead of Interface.

**Comment by BossGrand** [comment]
Ah so there definitely is a union type in graphene, but i don't think its documented. I haven't used it but searching through the repo I found this test

https://github.com/graphql-python/graphene/blob/bb7976a75f2a86313b718f62db6ed624d00bf02d/graphene/tests/issues/test_356.py#L3


if you end up getting it to work it'd be great if you could either post here an example, or add the documentation to graphene! :)

**Comment by hyusetiawan** [comment]
@alexche8 
is this what you need? #182
