### ISSUE TITLE
Example of processing serverside graphql

### ISSUE THREAD

**Issue by gthieleb** [graphql-python/graphene-django#201]
I would like to get used to graphql in a context that queries are also stored on the serverside. No graphql endpoint will be used. 

The graphql queries should be editable for admins for abstracting permissions (e.g. restricting to form fields and choices), default values, business logic, form and table generation. 

Is it possible with graphene-django to process serverside stored queries?

**Comment by syrusakbary** [comment]
This case is not supported currently, but I think might be a great addition to the library!

**Comment by brunoprela** [comment]
@syrusakbary Is it possible to use Mutations in the serverside kind of like DRF ModelSerializers are used, so as to be able to create models from data that is being processed independently of the client? Say I was processing Orders from an excel file and had an OrderMutation, could I use it to produce Order objects on the serverside? Haven't seen an example of this yet, sorry if it seems like a trivial question.

**Comment by dopeboy** [comment]
Closing this down because it is out of scope for now. Happy to revisit in the future.
