### ISSUE TITLE
django_filters lookup_type vs lookup_exp

### ISSUE THREAD

**Issue by hyusetiawan** [graphql-python/graphene-django#204]
there is a mismatch between what is expected by django_filters (lookup_exp) and the one specified in django graphene docs (lookup_type) 
reference: http://docs.graphene-python.org/projects/django/en/latest/filtering/#custom-filtersets

most likely difference in versions?

**Comment by rpkilby** [comment]
Hi all. It looks like the docs have been partially updated. There is one example using `lookup_expr`, which is correct, and one using `lookup_type`, which is incorrect. 

For context, `lookup_type` was deprecated and renamed `lookup_expr` to reflect the newly supported [expression transforms](https://docs.djangoproject.com/en/2.0/ref/models/lookups/#module-django.db.models.lookups) (e.g., `my_datetime__year__gt=2010`).

**Comment by dopeboy** [comment]
Closing this down due to a resolution.
