### ISSUE TITLE
Graphene autentification with curl example?

### ISSUE THREAD

**Issue by misazr** [graphql-python/graphene-django#207]
I found this example for adding login on graphene view
https://github.com/graphql-python/graphene-django/blob/master/docs/authorization.rst#adding-login-required

Can somebody give me example how with curl to login on **LoginRequiredMixin** graphene view and get response?

I tried something like this:
`curl -H "Authorization: Token  2867936fff9d738ee5fc8a807c86a96e59ab648d" http://localhost:8003/graphql?query=query%7B%20types%20%7B%20edges%20%7B%20node%20%7B%20name%20%7D%20%7D%20%7D%20%7D`

and 

`curl -u admin:password -X GET http://localhost:8003/graphql?query=query%7B%20types%20%7B%20edges%20%7B%20node%20%7B%20name%20%7D%20%7D%20%7D%20%7D`

**Comment by dopeboy** [comment]
`LoginRequiredMixin` uses Django's standard authentication features. The rough steps would be:

1. Login using a standard REST endpoint. Get a cookie back. 
2. Parse out the CSRF out of the cookie.
3. Pass it as a header in curl probably like [so](https://stackoverflow.com/questions/42441717/how-can-i-make-authenticated-request-to-django-view-from-external-html-using-aja).

Does that help?

**Comment by dopeboy** [comment]
Closing this down due to inactivity.
