### ISSUE TITLE
Question: How can I add description

### ISSUE THREAD

**Issue by akshaybabloo** [graphql-python/graphene-django#208]
Should I be adding `description` to `meta` class of `DjangoObjectType`?

**Update:**

Adding `description` to `meta` class of `DjangoObjectType` did not do anything.

**Comment by NikosVlagoidis** [comment]
Can you provide a code snippet?
Here is a working example of mine : 

```
class ChannelNode(DjangoObjectType):
    class Meta:
        model = Channel
        filter_fields = {'name': ['exact', 'icontains', 'istartswith'],
                         'customer': ['exact', 'icontains', 'istartswith']}
        interfaces = (relay.Node,)
        description = "This is a Channel Node"
```

If you navigate on ChannelNode on the GraphiQl you will see the description.

**Comment by akshaybabloo** [comment]
Awesome that's what I wanted to know. Thanks for the help.

**Comment by itaied246** [comment]
What about description for model fields?  
How can I attach description for the fields of `ChannelNode` (`name`, `customer` etc...)?

**Comment by akshaybabloo** [comment]
@itaied246 Might want to open a new request

**Comment by gonardfreeman** [comment]
> What about description for model fields?
> How can I attach description for the fields of ChannelNode (name, customer etc...)?

just pass a parameter like this
`DjangoFilterConnectionField(PageNode, description='test')`

**Comment by joepuzzo** [comment]
So i just tried this with no luck. Am I doing somthing wrong or has something changed? 
```
from graphene_django import DjangoObjectType
from .models import Question as QuestionModel
import graphene

class Question(DjangoObjectType):
    class Meta:
        model = QuestionModel
        description = "This is a Question"
```
