### ISSUE TITLE
Reflection for mutation fields instead retyping them?

### ISSUE THREAD

**Issue by mraak** [graphql-python/graphene-django#221]
Is it possible to get the model fields automatically picked up?

The following example is from the tutorial about mutations and it seems it should be unnecessary to repeat all the fields you already have in your model. 

```python

class IntroduceShip(relay.ClientIDMutation):

    class Input:
        ship_name = graphene.String(required=True)
#ship_age
#ship_shape
#ship_length
#ship_weight
#ship_etc
#ship_etc

        faction_id = graphene.String(required=True)

    ship = graphene.Field(Ship)
    faction = graphene.Field(Faction)

    @classmethod
    def mutate_and_get_payload(cls, input, context, info):
        ship_name = input.get('ship_name')
#ship_age
#ship_shape
#ship_length
#ship_weight
#ship_etc
#ship_etc
        faction_id = input.get('faction_id')
        ship = create_ship(ship_name, faction_id)
        faction = get_faction(faction_id)
        return IntroduceShip(ship=ship, faction=faction)


```

**Comment by mraak** [comment]
Already covered here and here:

https://github.com/graphql-python/graphene-django/issues/121
https://github.com/graphql-python/graphene/issues/143

**Comment by JunjieW** [comment]
This might be the best solution and it's going to be integrated into graphene-django: https://github.com/graphql-python/graphene-django/issues/274
