### ISSUE TITLE
Filter fields in a nested API

### ISSUE THREAD

**Issue by itaied246** [graphql-python/graphene-django#223]
Using Django filters, is there a way to produce nested API?
For example, if my `Car` model has a `seats` field, `django-graphene` would expose its filters as

    car
        width_gt
        width_gte
        width_lt
        ...

Where I would like it to be

    Car
        width
            gt : 4
            gte : 3
            lt : 7
            ...

Is there a way to achieve this?

**Comment by dopeboy** [comment]
There isn't a way to achieve this right now.
