### ISSUE TITLE
Override name for choices in a model field

### ISSUE THREAD

**Issue by Waitak** [graphql-python/graphene-django#225]
I have a model with a locale field, something like:

    LANGUAGES = [('en-us', 'English (US)'), ('en-gb', 'English (UK)'), ('fr', 'Français')]

...

    class MyMode(models.Model):
        locale = models.CharField(..., choices=LANGUAGES)

This fails `assert_valid_name`, called from `define_enum_values`. I have no control over the choice values, as they are standard Django locale tags. What can I do? (A similar issue was raised in #3 and #67.)

**Comment by denis-ryzhkov** [comment]
Maybe someone adds `GRAPHENE_CONVERT_CHOICES_TO_ENUMS = False` setting to `graphene_django` once.
Until then, you can opt out with monkey-patch somewhere before schema is imported, for example in settings file.
Patch: https://gist.github.com/denis-ryzhkov/fcb944f6ebfad4775efb74848703f0d7
