### ISSUE TITLE
Memoize Validation results

### ISSUE THREAD

**Issue by matclayton** [graphql-python/graphene-django#226]
We see significant (~50%) of our page latency being taken up by query validation, it'd be nice to memoize this validation step to avoid recalculating it. This is mentioning in the GraphQL spec http://facebook.github.io/graphql/#sec-Validation, and would need some thought to ensure it is purged correctly on schema updates, but could lead to significant speed improvements in our use case.

**Comment by japrogramer** [comment]
I would add a dataloader to the context of each request to cache results in that specific request.

**Comment by HeyHugo** [comment]
Wild idea: `@functools.lru_cache` on validate function in graphql.validation.validation
