### ISSUE TITLE
Support uuid input field

### ISSUE THREAD

**Issue by quytang** [graphql-python/graphene-django#227]
Hi there,

I have the model book:

```
class User(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    ... 

class Book(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
   owner = models.foreignFeild(User)
    ...

class UserType(DjangoObjectType):
   model = User

class BookType(DjangoObjectType):
   model = Book

class BookInput(InputObjectType):
    id = graphene.String() # Could you support graphene.Uuid() 
    owner_id = graphene.String() # Could you support graphene.Uuid() 

class ChangeBookOwner(graphene.Mutation):
    class Input:
        book_input = graphene.Field(BookInput, required=True)
    
    @staticmethod
    def mutate(root, args, context, info):
       id = args.get('book_input').get('id')
       book = Book.objects.get(pk=id)
       if book.owner_id == args.get('book_input').get('owner_id'): # this is always false
          # notify to the new owner
```

The `book.owner_id == args.get('book_input').get('owner_id')` is always false because:
1. when querying the BookType it returns the owner_id with `aa-bb-cc-dd` format which includes dash symbol and I use this owner_id to set the owner_id of `BookInput`. 

2. book.owner_id is always in `aabbccdd` format which doesn't include dash symbol.

Could you help me figure out the best way to deal with it without hacks?

Thanks a lot.

**Comment by japrogramer** [comment]
I don't see you change the owner of the book in that code snippet.
but if your problem is the dashes you can strip them, or you could use the uuid module to the stuff you want.

**Comment by quytang** [comment]
@japrogramer `Could you help me figure out the best way to deal with it without hacks?`
That means I don't want to do that manually. Is It better done with graphene?

**Comment by japrogramer** [comment]
I just treat a uuid field like a string:
`user = graphene.Field(UserType, uuid=graphene.String())`
and in resolve
`return context.dataloaders.user.load(context.user.uuid)`

**Comment by quytang** [comment]
The problem is the comparison, not loading from DB.

Have you ever tried the comparision `args.get('uuid') === user.uuid`.
Let do that and you will see the comparison produce `False`.

I don't want to replace the `dashes` from the `args.get('uuid')` or do extra redundant work like load object from DB.

Do you know why `args.get('uuid')` contains `dashes`? Because the `uuid` field return from the graphql query contains `dashes`, but `user.uuid` has no dashes. I already mentioned them in the description of the issue.

**Comment by japrogramer** [comment]
@quytang args.get('uuid') is str(user.uuid)

**Comment by Eraldo** [comment]
Thus: `args.get('uuid') == str(user.uuid)` should probably work.

**Comment by quytang** [comment]
Why do I need to use str for all of those? Why not get it done naturally like args.get('uuid') = user.uuid?

For the case id, developers can switch from `uuid` to `auto-increase` int and vice versa.
Using str here will make it hard to refactor and maintenance for the field?

**Comment by zbyte64** [comment]
The converter does translate UUID frields to graphene UUID fields. So maybe this bug is no longer valid?

**Comment by dopeboy** [comment]
@zbyte64, is correct. So long as you've defined your argument to be of type `graphene.UUID()`, that equality test mentioned by @quytang will work. Closing this down.
