### ISSUE TITLE
Include a function on the ``info`` object of a resolver to get the fields

### ISSUE THREAD

**Issue by camd** [graphql-python/graphene-django#230]
In implementing support for ``prefetch_related`` on my project, it would have been handy to have a function to get the fields that are in the query to see where to add this optimization.  I created this function:

    def collect_fields(node):
        """Get all the unique field names that are eligible for optimization"""
        fields = set()
        for leaf in node:
            if leaf.get('kind', None) == "Field":
                fields.add(leaf["name"]["value"])
    
            if leaf.get("selection_set", None):
                fields = fields.union(collect_fields(leaf["selection_set"]["selections"]))
    
        return fields

Does it seem reasonable to add a function like this to the ``info`` object?  I'm happy to open a PR if so.

**Comment by mjtamlyn** [comment]
A function like this needs to be more complicated than your example in order to support fragments

**Comment by japrogramer** [comment]
you can take a peak at the 'info' argument by using pdb and doing dir(info)

**Comment by dopeboy** [comment]
Looks like this is more on the knowledge sharing so I'm closing this down. If you feel strongly about the PR, go for it.
