### ISSUE TITLE
DjangoFilterConnectionField ignores .using()

### ISSUE THREAD

**Issue by dmalisani** [graphql-python/graphene-django#238]
class ArticuloNode(DjangoObjectType):
    descripcion = graphene.String(source='descripcion')
    class Meta:
        model = Articulo
        filter_fields = {'nombre':['icontains', 'iexact'],
                        }
        interfaces = (graphene.Node, )

class Query(graphene.ObjectType):
    articulos = DjangoFilterConnectionField(ArticuloNode)

def resolve_articulos(self, args, context, info):
    **print(Articulo.objects.using("db").all())
    x=Articulo.objects.using("db").all()    <----- Output printer it's ok, but the def returns ignoring "db" and shows "default" db result. 
    return x**

**Comment by japrogramer** [comment]
You might want to check that the DjangoObjectType doesn't alter the queryset.

**Comment by dmalisani** [comment]
How? I'm newbie in graphene 
But I showed all code, there is no more my code between this code and requested for /graphql

**Comment by japrogramer** [comment]
I looked and couldn't find any change of the queryset that would change the queryset. Maybe the next person that sees this issue can be of more help.

**Comment by dmalisani** [comment]
if I only change 
this line:
**articulos = DjangoFilterConnectionField(ArticuloNode)**
for this:
**articulos = graphene.List(ArticuloNode)**
it works perfectly (but I can't use filters)
I don't touch in anywhere out of schema.py and it works, then I concluded that It was a bug.
But, I still searching... Thanks

**Comment by dmalisani** [comment]
I think there is a bug in connection_resolver, I paste since line 89 of fields.py

        iterable = maybe_queryset(iterable)
        print("before ---->>  ", repr(iterable))

        if isinstance(iterable, QuerySet):
            if iterable is not default_manager:
                default_queryset = maybe_queryset(default_manager)
                iterable = cls.merge_querysets(default_queryset, iterable)
                print("after ---->>", repr(iterable))
            _len = iterable.count()
        else:
            _len = len(iterable)

**Output shows:**
before ---->>   <QuerySet [<Articulo: Accesoriox Cable Canal()()()( - 14x7>, [...] 
after ---->> <QuerySet [<Articulo: Accesoriox Cable Canal - 14x7>, [...]

It function evidently override queryset.

**Comment by japrogramer** [comment]
try doing
`DjangoFilterConnectionField(ArticuloNode, on=True)`

**Comment by dmalisani** [comment]
Didn't work
----------------------------------------
  File "[...]/graphene_django/filter/fields.py", line 96, in get_resolver
    self.get_manager(),
  File "[...]/graphene_django/fields.py", line 54, in get_manager
    return getattr(self.model, self.on)
TypeError: getattr(): attribute name must be string
[10/Aug/2017 18:17:02] "POST /graphql? HTTP/1.1" 500 177859


2017-08-09 21:15 GMT-03:00 japrogramer <notifications@github.com>:

**Comment by dmalisani** [comment]
I commented that lines

```
        if iterable is not default_manager:
            default_queryset = maybe_queryset(default_manager)
            iterable = cls.merge_querysets(default_queryset, iterable)

```
And it works perfectly. I can't understand what is the use of that code.

**Comment by japrogramer** [comment]
Earlier i spoke incorrectly, see on should actually be the name of the attribute for the manager that you want to use, so if you are using a custom manager to construct the query and don't tell the filter field it replaces it with the default manager. however i don't know if by passing on='objects' to the field will clear the using statement set later In the query.
sorry about that, i quickly looked over the code when i gave you that answer.

**Comment by BossGrand** [comment]
I think theres actually a bug with DjangoFilterConnectionField.merge_querysets

the line ```queryset = default_queryset & queryset```

should be reverse to ```queryset =queryset &  default_queryset```
because default query set is overriding any attributes queryset would have. Such as order_by annotations ect. I'm about to push a pr to fix this issue
