### ISSUE TITLE
Access to generated enum for Django Choices

### ISSUE THREAD

**Issue by 0nkery** [graphql-python/graphene-django#240]
In my project I have models with Choice fields and I want to include generated enums in Input for mutations.

Currently I have to use something like

```python
    @classmethod
    def field_with_choices_enum(cls):
        return cls._meta.fields["field_with_choices"]._type._of_type
```

This approach looks like a hack (and it is). It there any other way to access generated enums?

**Comment by soosap** [comment]
Did anyone find a proper way to do this? @0nkery

**Comment by 0nkery** [comment]
@soosap Nope, I'm still using the way I described.

**Comment by dopeboy** [comment]
Closing this issue down because there is hard work (thanks @zbyte64 and @phalt) addressing it.

**Comment by dspacejs** [comment]
@dopeboy having trouble finding the official way to do this in those PRs. Do you know how to do it? Here's the hacky workaround I've been using:

```python
PrimaryGoalCategory = PrimaryGoalNode._meta.fields['category']._type._of_type
```

**Comment by thomas-at-perdoo** [comment]
In my case `SomeType._meta.fields['field']._type` is a `graphene.types.structures.NonNull` type (`SomeChoice!`). 

I seem to be unable to reach the inner enum type (`SomeChoice`). I've tried with `SomeType._meta.fields['field']._type._of_type` as suggested above but that yields a `graphene.types.enum.EnumMeta` which cannot be used as a GraphQL type.

Any idea on how to get the underlying nullable enum type?
