### ISSUE TITLE
BigIntegerField should convert to Float?

### ISSUE THREAD

**Issue by brianjp93** [graphql-python/graphene-django#241]
I'm not sure what the best solution to this would be, but converting `models.BigIntegerField()` to `graphene.Int()` will often give me the error.

```
{
  "errors": [
    {
      "message": "Int cannot represent non 32-bit signed integer value: 2554208328"
    }
  ],
  "data": {
    "match": null
  }
}
```

Maybe we would be better off converting it to a `graphene.Float()`?

**Comment by japrogramer** [comment]
you might want to create your own scalar for big integers.

**Comment by brianjp93** [comment]
@japrogramer Yes I think that would work, but still BigIntegerField should probably convert to something that won't throw an error when it is a big integer.

**Comment by japrogramer** [comment]
It should, if you make a scalar that works for you consider making a pull request.

**Comment by brianjp93** [comment]
I ended up creating a custom `BigInt` scalar.

```
from graphene.types import Scalar
from graphql.language import ast
from graphene.types.scalars import MIN_INT, MAX_INT

class BigInt(Scalar):
    """
    BigInt is an extension of the regular Int field
        that supports Integers bigger than a signed
        32-bit integer.
    """
    @staticmethod
    def big_to_float(value):
        num = int(value)
        if num > MAX_INT or num < MIN_INT:
            return float(int(num))
        return num

    serialize = big_to_float
    parse_value = big_to_float

    @staticmethod
    def parse_literal(node):
        if isinstance(node, ast.IntValue):
            num = int(node.value)
            if num > MAX_INT or num < MIN_INT:
                return float(int(num))
            return num
```

Then I just set the necessary fields to this scalar in my schema files.  I would create a pull request, but I'm not sure how to add this into graphene-django itself.  Maybe someone more knowledgeable than myself can give it a go.

**Comment by svengt** [comment]
Thanks @brianjp93, this is still an issue in 2021 😅 

You can register the custom field so it uses it automatically for every models.BigIntegerField. Run the following in an app -> ready method for example.

```
from django.apps import AppConfig
from django.db import models
from graphene import Field
from graphene_django.converter import convert_django_field

from .types import BigInt


class MainConfig(AppConfig):
    ...

    def ready(self):
        super().ready()

        @convert_django_field.register(models.BigIntegerField)
        def convert_field_to_big_int_field(field, registry=None):
            return Field(BigInt, description=field.help_text, required=not field.null)
```
