### ISSUE TITLE
Several 'RemovedInDjango20Warning's with Django 1.11 (field.rel, ForeignObjectRel.to)

### ISSUE THREAD

**Issue by edmorley** [graphql-python/graphene-django#242]
Hi!

When running our test suite with Python warnings enabled (eg `PYTHONWARNINGS=once pytest`), we get the following deprecation warnings:

```
  .../site-packages/graphene_django/utils.py:61: RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.
    if hasattr(field, 'rel'):
  .../site-packages/graphene_django/utils.py:63: RemovedInDjango20Warning: Usage of ForeignObjectRel.to attribute has been deprecated. Use the model attribute instead.
    return field.rel.to
```

These line numbers correspond to:
https://github.com/graphql-python/graphene-django/blob/v1.3/graphene_django/utils.py#L61
https://github.com/graphql-python/graphene-django/blob/v1.3/graphene_django/utils.py#L63

The deprecation docs for this are here:
https://docs.djangoproject.com/en/1.11/releases/1.9/#field-rel-changes

I'm presuming the solution would be to either:
1) Drop support for Django 1.6/1.7 entirely
2) Invert the conditional, such that it does `hasattr(field, 'related_model')` and if not found then falls back to `field.rel.to`.

Given Django <1.8 is EOL and has security vulnerabilities, I'd lean towards solution (1).

This was using:
* graphene-django 1.3
* graphene 1.4.1
* Django 1.11.4
* Python 2.7.13

**Comment by edmorley** [comment]
Given Django 1.6/1.7 aren't tested in the Travis run, I presume solution (1) from above is acceptable.

I'm happy to open a PR - should I target master or the 2.0 branch?

**Comment by japrogramer** [comment]
Since this effects deployments that are out there now, I would think to have this pushed to master since it has very little to do with new features. Users of django previous and up to 1.8 aren't going to be receiving support from the django team especially since 2.0 will only support 3.x python and 1.11 is the last version of django to support 2.x python.

**Comment by joeydebreuk** [comment]
With the versions:

Django==1.11
graphene==2.0
graphene-django==2.0.0
graphql-core==2.0

I get the same warning, and with the versions: 

Django==2.0
django-cors-headers==2.1.0
django-filter==1.1.0
django-filters==0.2.1
graphene==2.0
graphene-django==2.0.0
graphql-core==2.0

I get the error: Foreignkey has no attribute: 'rel'

**Comment by edmorley** [comment]
Oh it looks like there are more instances remaining:
https://github.com/graphql-python/graphene-django/blob/c60c1430a7f2e478910add2fd644a7d11d1cfdbc/graphene_django/filter/filterset.py#L60
https://github.com/graphql-python/graphene-django/blob/992fbf0c44bfc26271fe409a84b1918d6cbb6200/graphene_django/utils.py#L27
https://github.com/graphql-python/graphene-django/blob/1bea96b31e9e8e77593946b78ab39b93d6f2cfec/graphene_django/tests/test_converter.py#L231

**Comment by joeydebreuk** [comment]
Is it fixed? Should I open an Issue?
