### ISSUE TITLE
URL pattern in readme should end with $

### ISSUE THREAD

**Issue by camd** [graphql-python/graphene-django#248]
I think the url pattern listed in the README would be better if it ended with a ``$`` for less ambiguous matching.  Something like:

    urlpatterns = [
        # ...
        url(r'^graphql$', GraphQLView.as_view(graphiql=True)),
    ]

**Comment by edmorley** [comment]
Since currently eg `/graphql123` matches.

**Comment by dopeboy** [comment]
This was done thanks to the talented and esteemed @phalt; closing down.
