### ISSUE TITLE
How to parse ``` node(id:$id_0) {     ...F0   }  ``` type query in graphene-django? (created by invoking relay's setVariables or forceFetch APIs)

### ISSUE THREAD

**Issue by JasonShin** [graphql-python/graphene-django#254]
Hi,

I am using Relay classic and Graphene-Django for backend. On initial page load, Relay is generating a query that looks like:

```
"query ViewerQuery {
  viewer {
    ...F0
  }
}
fragment F0 on Viewer {
  _xxxl4VzbI:xxx(id:"XXX.28") @include(if:true) {
     attrs...
   }
  id
}"
```
and our graphene django implementation can read this without any issues. However, whenever we use Relay's "forceFetch" or "setVariables", we are getting following query structure:
query:
```
query BioPage_ViewerRelayQL($id_0:ID!) {
  node(id:$id_0) {
    ...F0
  }
}
```
variables:
```
{id_0: "3"}
```
id_0: 3 is viewer ID (viewer aka user ID. Automatically picked up by Relay.).

and our Django-Graphene is printing an error saying
```
not enough values to unpack (expected 2, got 1)
     node(id:$id_0) {
     ^^^
```

Here are some of our code structure.
models.py
-> just typical django models with relations to support RDBS (posgres)

Schema.py
we have implemented CustomNode so we can have a specific structure for grabbing database IDs

```
class CustomNode(Node):
    class Meta:
        name = 'Node'

    @staticmethod
    def to_global_id(type, id):
        return "{}.{}.{}".format(uuid.uuid4(), type, id)

    @staticmethod
    def get_node_from_global_id(id, context, info, only_type=None):
        print(f'checking id {id}')
        typez, idz = id.rsplit('.', 1)
        result = getattr(models, typez).objects.get(id=idz)
        result.check_permissions(user=context.user)
        return result
```
Remaining code is just very similar to typical Graphene Relay implementation (very similar to starwars-relay example).

not enough values to unpack... the error is happening in following section (screenshot of Sentry log)

![sentry log](https://user-images.githubusercontent.com/2525002/29695463-742b362c-8986-11e7-9b42-ca8a027b1d37.PNG)
above code is located inside "CustomNode" code block.

from ``` def get_node_from_global_id(id, context, info, only_type=None): ```

ID that we are getting is "5", which is just a user ID. What changes should I make so that we can make setVariables and forceFetch to work?

I am happy to give more information upon request.

**Comment by JasonShin** [comment]
I'd imagine once I resolve this issue, we will have fully Relay compatible Graphene server.

**Comment by JasonShin** [comment]
To put it simply, I think it's failing from parsing queries like
```
{
  node(id: "4") {
    id
    ... on User {
      name
    }
  }
```
Grabbed it from below specification link.
https://facebook.github.io/relay/graphql/objectidentification.htm

**Comment by JasonShin** [comment]
I just realised its due to global id. Correct me if I am wrong. Also I am not meant to implement "id" in viewer in my situation.

**Comment by JasonShin** [comment]
If I want viewer id. I must return viewer's global id.

**Comment by JasonShin** [comment]
Furthermore, we are handling auth outside of graphql. We dont even need viewer.

**Comment by varunarora** [comment]
+1

**Comment by 0xpsilocybe** [comment]
This is still an issue today

**Comment by varunarora** [comment]
Wakie wakie bot...

**Comment by jkimbo** [comment]
@varunarora the issue seems to be that the `node` field requires a global ID to be passed to it (rather than just a Django ID). If a global ID is passed then it should work fine. Is that right? Could you clarify what issue you are seeing?
