### ISSUE TITLE
Ordered dict results

### ISSUE THREAD

**Issue by gonardfreeman** [graphql-python/graphene-django#258]
Is there any way to get regular dict, after execution schema?

**Comment by gonardfreeman** [comment]
Already found solution, for those who wants do it to, here it is:

`import json #<-- dont forget import it`
`result = schema.execute(query)`
`prettified_data = json.dumps(result.data, sort_keys=False)`

**Comment by syrusakbary** [comment]
Great! Closing the issue :)
