### ISSUE TITLE
Docs out of date for recommended install version.

### ISSUE THREAD

**Issue by jeremytiki** [graphql-python/graphene-django#262]
The recommended install version (according to the README) is >=2.0.dev, however the docs have not been updated to reflect some breaking changes. Specifically http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/ still uses:
```python
def resolve_category(self, args, context, info):
```
This should be changed to 
```python
    def resolve_category(self, info, **args):
```
I would be glad to put a pull request in for this issue.

**Comment by spockNinja** [comment]
Closed by 84d063261e6b088acbcd1c95945564126775cfa7
