### ISSUE TITLE
Make graphiql work offline

### ISSUE THREAD

**Issue by matclayton** [graphql-python/graphene-django#271]
Currently graphiql depends on a cdn copy of react and other libraries, this makes graphiql useless in an offline situation.

Sorry if this isn’t specifically a graphene-django issue.

**Comment by clodal** [comment]
I don't think it is a graphen django issue though

**Comment by saschalalala** [comment]
I think it is, because the template is part of this project, see https://github.com/graphql-python/graphene-django/blob/master/graphene_django/templates/graphene/graphiql.html#L19

**Comment by zbyte64** [comment]
Duplicate of #69
