### ISSUE TITLE
Custom FilterSet not working in nested queries (on NodeTypes)

### ISSUE THREAD

**Issue by Eraldo** [graphql-python/graphene-django#273]
According to the docs this is how filtering works:
https://github.com/graphql-python/graphene-django/blob/master/docs/filtering.rst#custom-filtersets

However if I have a `ManyToMany` or `ForeignKey` related field.. it stops working!

This works:
```
query Tasks {
  tasks(search: "test") {
    edges {
      node {
        id
        ...Fields
      }
    }
  }
}
```

This does not work:
```
query ProjectTasks {
  projects {
    edges {
      node {
        id
        tasks(search: "test") {
          edges {
            node {
              id
              ...Fields
            }
          }
        }        
      }
    }
  }
}
```

Error message: `"message": "Unknown argument \"search\" on field \"tasks\" of type \"TaskNode\"."`

Possible reason:
The reason is that the related field gets resolved to a TaskNode and only `DjangoConnectionFields` currently allow custom FilterSets. Nodes only feature filter_fields. :|

**Comment by spiralsyzygy** [comment]
This problem is honestly making me want to drop using this package and just manually create schema object types/nodes. Is there a work around or solution for this?

**Comment by Eraldo** [comment]
@spiralsyzygy This problem is about to be fixed. :)
The reason was just that DjangoFilterConnection returned instances of it's NodeType and these did not have an option to specify filtersets.

I will personally take care that this will be extended soon. There are already great contributions that I want to take a close look and bring into the main code base.

As a workaround you can specify the involved filter resolvers to your NodeType that you handed over to the DjangoFilterConnection

**Comment by morinx** [comment]
@spiralsyzygy Is there any update on this issue? :)

**Comment by morinx** [comment]
@Eraldo Is there any update on this issue? :)

**Comment by Eraldo** [comment]
This is what I currently do:
```python
class UserNode(DjangoObjectType):
    my_models = DjangoFilterConnectionField(MyModelNode, filterset_class=MyModelFilter)
```

Does that work for you?

**Comment by morinx** [comment]
Thanks for the details @Eraldo , the filters (custom or not) works for me if applied individually on each `DjangoFilterConnectionField`. it's when I try to access the filters inside another Node that graphene doesn't recognize the filter fields sometimes. I'm guessing it's an issue with Nested filtering with `DjangoFilterConnection` regardless of whether it's Custom filter or not. 

I've open another issue (#410) since I believe this to be a separate topic :)

**Comment by Eraldo** [comment]
Yes, that is true and it is not optimal.
It is not a general fix, however you can add a line like that `my_models = DjangoFilterConnectionField(MyModelNode, filterset_class=MyModelFilter)` on all the other models that have relations to it thus also getting the nested filters to work again.

Does what I am saying make sense to you or would an example help?

**Comment by morinx** [comment]
I tried to implement your suggestion but still cannot resolve the connection filter. An example would definitely help. Thanks a lot.

**Comment by Eraldo** [comment]
```python
class AuhorNode(DjangoObjectType):
    class Meta:
        model = Author
        interfaces = [graphene.Node]    

class AuthorQuery(graphene.ObjectType):
    authors = DjangoFilterConnectionField(AuthorNode, filterset_class=AuthorFilter)

class BookNode(DjangoObjectType):
    class Meta:
        model = Book
        interfaces = [graphene.Node]

    authors = DjangoFilterConnectionField(AuthorNode, filterset_class=AuthorFilter)

class BookQuery(graphene.ObjectType):
    books = DjangoFilterConnectionField(BookNode, filterset_class=BookFilter)
```

Assuming that:
+ there is a many to many between `Book` and `Author`
+ Author has a filter named `name_Icontains`

I can now do both:
```gql
query AuthorSearch {
    authors( name_Icontains: "Eraldo") {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
```
```gql
query BookAuthorSearch {
  books {
    edges {
      node {
        id
        name
        authors(name_Icontains: "Eraldo") {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    }
  }
}
```

Not the most realistic example.. but I hope you get the idea. ;)

**Comment by morinx** [comment]
Interesting. My first inclination is to define a Base `AuthorNode` before the Connection without `connection_class` and extent it after the `relay.connection`. But I think it will only partially solve your problem.

**Comment by morinx** [comment]
To call a class that hasn't been defined yet, you can either pass the name of class as string `'AuthorNode'`, or use a `lambda: AuthorNode`

 An example I encountered that required referencing a class that wasn't defined yet:

```py
class AuthorNode(DjangoObjectType):

    class Meta:
        model = Author
        interfaces = (Node, )

    another_author = ConnectionField(lambda: AuthorConnection)
    def resolve_another_author(self, info, **kwargs):
       # ...

class AuthorConnection(Connection):

    class Meta:
        node = AuthorNode
```

Hope this helps.

**Comment by Eraldo** [comment]
@morinx I tried both suggestions, however it did not solve my issue.

How do I know that: When the custom Connection as the `connection_class` for my node, doing reverse queries like `book { authors(cannot filter here!) ... }` I am not able to use the filters defined in my filterset class.

**Comment by allfro** [comment]
The problem appears to exist in this code snippet:

```python
@convert_django_field.register(models.ManyToManyField)
@convert_django_field.register(models.ManyToManyRel)
@convert_django_field.register(models.ManyToOneRel)
def convert_field_to_list_or_connection(field, registry=None):
    model = field.related_model

    def dynamic_type():
        _type = registry.get_type_for_model(model)
        if not _type:
            return

        # If there is a connection, we should transform the field
        # into a DjangoConnectionField
        if _type._meta.connection:
            # Use a DjangoFilterConnectionField if there are
            # defined filter_fields in the DjangoObjectType Meta
            if _type._meta.filter_fields:
                from .filter.fields import DjangoFilterConnectionField

                return DjangoFilterConnectionField(_type)

            return DjangoConnectionField(_type)

        return DjangoListField(_type)

    return Dynamic(dynamic_type)
```

Relation connection fields are initialized just with the node type. I've monkey patched `DjangoFilterConnectionField`'s `connection_resolver` method to achieve the desired result:

```python
old_connection_resolver = DjangoFilterConnectionField.connection_resolver


def connection_resolver(cls, resolver, connection, default_manager, max_limit, enforce_first_or_last, filterset_class,
                        filtering_args, root, info, **kwargs):
    if issubclass(default_manager.model, ProtectedModel) and filterset_class.__name__ in globals():
        filterset_class = globals()[filterset_class.__name__]
    return old_connection_resolver(resolver, connection, default_manager, max_limit, enforce_first_or_last,
                                   filterset_class, filtering_args, root, info, **kwargs)


DjangoFilterConnectionField.connection_resolver = classmethod(connection_resolver)
```

It's not ideal, but it works. A global django setting that would allow users to specify the default base `FilterSet` class to be used when creating dynamic `FilterSet` instances would be nice as a feature. I noticed that `get_filterset_class` is used as a factory method for `FilterSet` classes and accepts a `filterset_base_class` option that gets passed down to `custom_filterset_factory`.
