### ISSUE TITLE
Execution object

### ISSUE THREAD

**Issue by gonardfreeman** [graphql-python/graphene-django#275]
I'm trying to execute query(in django view) and it returns Execution result, whats wrong?
```
from zruchna.schema import schema
result = schema.execute(query)
```

`graphql.execution.base.ExecutionResult object at 0x104c89388>`

**Comment by gonardfreeman** [comment]
Ooops) forgot to return result data)

**Comment by phalt** [comment]
By inspecting the exception you should be able to see your errors?
