### ISSUE TITLE
ImportError: cannot import name ObjectTypeMeta

### ISSUE THREAD

**Issue by GiancarlosIO** [graphql-python/graphene-django#277]
I'm building my first graphql-app with django using this tutorial:
http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/

My schema's code is exactly like that tutorial, but i'm getting this error:

![screenshot from 2017-09-23 21 05 10](https://user-images.githubusercontent.com/17274950/30778736-fec114f4-a0a2-11e7-945c-f538d3ad67a5.png)

Maybe this is related to the changes in version 2? or is the documentation outdated?
I'm using python 2.7 and django 1.11
Thanks.

**Comment by spockNinja** [comment]
@GiancarlosIO 

If you do a pip freeze, what versions of graphene and graphene-django are installed? From the traceback, it looks like you have a recent version of graphene, but an old version of graphene-django.

**Comment by GiancarlosIO** [comment]
@spockNinja 
Django==1.11.5
graphene-django==1.3
![screenshot from 2017-09-29 22 59 38](https://user-images.githubusercontent.com/17274950/31042286-ede07f96-a569-11e7-8058-ac8137cf4cb9.png)

**Comment by spockNinja** [comment]
Yup. You have graphene 2.0.dev and graphene-django 1.3, which are incompatible. If you update graphene-django to 2.0.dev as well, I think that should solve the import problem.

**Comment by ryanwilsonperkin** [comment]
@spockNinja in our case, we only have `graphene-django==1.3.0` in our `requirements.txt` file. That version has a loose specifier on `graphene>=1.4`, which is causing us to pull in Graphene 2.0 dev version and breaking our build.

Would you be willing to release a `graphene-django` patch (1.3.1) that would restrict Graphene to `>=1.4,<2`? I would be happy to submit a PR for this.

**Comment by syrusakbary** [comment]
@ryanwilsonperkin sorry for that, it was mainly caused because "unpinned" dependencies in graphene and graphene-django.

In future versions the dependencies will be "pinned" to a specific range of versions, so we assure the issue is no longer repeated.

**Comment by ryanwilsonperkin** [comment]
Wonderful, thank you @syrusakbary !
