### ISSUE TITLE
Lowercased choices getting uppercased in Graphene response

### ISSUE THREAD

**Issue by cristiangrojas** [graphql-python/graphene-django#280]
I've the following model:

```
class TripSuggestedGadget(models.Model):
    trip = models.ForeignKey(
        Trip,
        related_name='suggested_gadgets'
    )
    type = models.CharField(
        max_length=50,
        choices=SUGGESTED_GADGET_TYPES
    )
    description = models.TextField()
```

Here are the choices referred above:

```
SUGGESTED_GADGET_TYPES = (
    ('camera', u'Cámara'),
    ('flash', u'Flash'),
    ('tripod', u'Trípode'),
    ('umbrella', u'Sombrilla'),
)
``` 

In the graph response here's what I'm getting:

```
...
"edges": [
    {
        "node": {
            "id": "VHJpcFN1Z2dlc3RlZEdhZGdldE5vZGU6MQ==",
            "type": "CAMERA",
            "description": "Cámara de formato medio",
            "__typename": "TripSuggestedGadgetNode"
        },
        "__typename": "TripSuggestedGadgetNodeEdge"
    },
    {
        "node": {
            "id": "VHJpcFN1Z2dlc3RlZEdhZGdldE5vZGU6Mg==",
            "type": "FLASH",
            "description": "Flash",
            "__typename": "TripSuggestedGadgetNode"
        },
        "__typename": "TripSuggestedGadgetNodeEdge"
    },
    {
        "node": {
            "id": "VHJpcFN1Z2dlc3RlZEdhZGdldE5vZGU6Mw==",
            "type": "TRIPOD",
            "description": "Trípode liviano para poderlo llevar",
            "__typename": "TripSuggestedGadgetNode"
        },
        "__typename": "TripSuggestedGadgetNodeEdge"
    }
]
...
```

As you may notice my choices are lowercased, but response uppercased.

I've seen @BrianChapman comment in #67 regarding the same problem, but preferred to open this new one because #67 is not directly related.

**Comment by syrusakbary** [comment]
Hi @cristiangrojas,

The main reason choice enums are uppercase is because are following recommended styling in GraphQL (all Enums in the provided examples and demos are always uppercase).
As the Enum values are served as "strings" over the wire it helps to identify them.

See example: http://graphql.org/graphql-js/type/#example-4

**Comment by flesser** [comment]
Is there a way to change this behavior, if my application requires case-sensitive choices? (e.g. with `tripod`, `triPod` and `TRIPOD` having three different meanings in the Django model?)

**Comment by spockNinja** [comment]
Right now, your best bet is to override the type and make your own `graphene.Enum`.

```python

MyEnum = graphene.Enum(
    'MyEnum',
    [(value, value) for value, _ in SOME_DJANGO_MODEL_CHOICES]
)

class MyObject(DjangoObjectType):

    some_choices_field = MyEnum()
```

I have been thinking about how we can solve this problem without breaking backwards compatibility, and I have not yet found a clear answer. Especially after seeing your case of three different values that resolve to the same thing after going through `to_const`.

**Comment by denis-ryzhkov** [comment]
Maybe someone adds `GRAPHENE_CONVERT_CHOICES_TO_ENUMS = False` setting to `graphene_django` once.
Until then, you can opt out with monkey-patch somewhere before schema is imported, for example in settings file.
Patch: https://gist.github.com/denis-ryzhkov/fcb944f6ebfad4775efb74848703f0d7

**Comment by sliverc** [comment]
https://github.com/graphql-python/graphene-django/issues/133 seems to be related.

**Comment by Hispar** [comment]
Adding the field as a String, seems to be enough to solve the problem.

```
class MyObject(DjangoObjectType):
   type = graphene.String()
```

**Comment by yardensachs** [comment]
I'm surprised this is still not been addressed

**Comment by yardensachs** [comment]
@syrusakbary same as camel cased fields, this makes sense to turn into the GraphQL convention.

But like the field name, when translating back the request, you translate the fields back to snake case, you should al be mapping this enum value back to what it originally was before altering it.

I have my app with many many choices fields, and the use of enum is great and makes sense, but I can't use it while the value that comes back is altered and incorrect.

**Comment by jordanmkoncz** [comment]
Just ran into this issue too and was very confused that Graphene was forcing all my enum string values to uppercase. Given that Django itself treats enum strings used as `choices` as being case-sensitive, and does not force them to be uppercase, I think it's important that Graphene doesn't try to force them to be uppercase.

If GraphQL recommends string constants be uppercase, perhaps it's worth mentioning this as a suggestion in the Graphene docs somewhere, but I think the choice needs to be left to the developer.

In the meantime, @Hispar's fix of marking the field as being a `String()` is working for me.

**Comment by phalt** [comment]
Discussion is focusing on #67 so closing this to avoid duplicate conversations.
