### ISSUE TITLE
Docs instruct you to install *wrong* version leading to unnecessary confusion & broken code

### ISSUE THREAD

**Issue by elnygren** [graphql-python/graphene-django#284]
http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#setup-the-django-project

**Actual:**
> `pip install graphene_django`

**Shoulde be (like in the README):**
> `pip install "graphene-django>=2.0.dev"`

**Causes:**

Reader will install graphene_django 1.3 while the docs are about 2.0. Things like Mutations will break in non-obvious ways.

**FIX:**

The docs should (for now) tell people to use the `>=2.0.dev` postfix.

EDIT:

http://docs.graphene-python.org/en/latest/quickstart/
Main project's docs get it right with `pip install "graphene>=2.0.dev"` !

**Comment by dperetti** [comment]
Yeah. Was *really* annoying to figure out.

**Comment by dperetti** [comment]
And the code is poorly documented as well. Doesn't help either.

**Comment by crucialfelix** [comment]
2.0 dev is a development build. It isn't officially released yet. 1.3 is the current stable version (though it has some known bugs).

**Comment by FrankSalad** [comment]
```
              | Unhandled exception in thread started by <function wrapper at 0x7f2b59ae4848>
              | Traceback (most recent call last):
              |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
              |     fn(*args, **kwargs)
              |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
              |     autoreload.raise_last_exception()
              |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
              |     six.reraise(*_exception)
              |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
              |     fn(*args, **kwargs)
              |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
              |     apps.populate(settings.INSTALLED_APPS)
              |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
              |     app_config = AppConfig.create(entry)
              |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
              |     module = import_module(entry)
              |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
              |     __import__(name)
              | ImportError: No module named graphene_django
```

**Comment by elnygren** [comment]
@crucialfelix yes absolutely. Just that there's a bit of an inconsistency if the "default" docs are about a totally different version than the "default" installation :P 

But this is a pretty old issue already so I think maintainers can close this if they see fit

**Comment by syrusakbary** [comment]
Since we already launched Graphene 2.0 officially, this issue should be now solved.

The documentation should have warned about this, though. So I will make sure this is no longer repeated in any future releases.
