### ISSUE TITLE
getting '405 Method Not Allowed' when Apollo client sends OPTIONS method

### ISSUE THREAD

**Issue by slavugan** [graphql-python/graphene-django#288]
in response headers I see "Allow: GET, POST". How can I enable OPTIONS method on server?

**Comment by slavugan** [comment]
sorry, using corsheaders fixed my issue.

**Comment by Northshoot** [comment]
can you provide a usage sample?

**Comment by slavugan** [comment]
I've just used corsheaders and followed their documentation

**Comment by wiredots01** [comment]
im having the same issue

<img width="1291" alt="screen shot 2018-01-26 at 1 39 52 pm" src="https://user-images.githubusercontent.com/4254904/35426486-7603f128-029e-11e8-9244-90ed4536334b.png">

**Comment by wiredots01** [comment]
ive got it working by adding cors

`
import cors from 'cors';
...
server.use('/graphql', cors(), bodyParser.json(), graphqlExpress({schema}));`

**Comment by dsun-ge** [comment]
@slavugan I also followed django-cors-headers's instructions and set CORS_ORIGIN_ALLOW_ALL = True. 
And OPTIONS http://my-django-graphene-site/admin returns "access-control-allow-origin →*". However, OPTIONS http://my-django-graphene-site/graphql returns error saying "only POST and GET are allowed", and POST returned no "access-control-allow-origin" header. 
Could you show us how you enable OPTIONS method for graphql?

**Comment by a13xg0** [comment]
@dsun-ge 
With the same issue, I figured out that I forgot to add
`'corsheaders.middleware.CorsMiddleware',`
in the middleware section: 
```
MIDDLEWARE = [  # Or MIDDLEWARE_CLASSES on Django < 1.10
    ...
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    ...
]```

**Comment by talha-amir-fm** [comment]
> @slavugan I also followed django-cors-headers's instructions and set CORS_ORIGIN_ALLOW_ALL = True.
> 
> And
> 
> > OPTIONS http://my-django-graphene-site/admin
> 
> returns "access-control-allow-origin →*". This means the cors-header is working. However,
> 
> > OPTIONS http://my-django-graphene-site/graphql
> 
> returns error saying "`only POST and GET are allowed`", and POST returned no "access-control-allow-origin" header.
> 
> Could you show us how you enable OPTIONS method for graphql?

were you able to solve it ? 
I am facing the same issue

**Comment by slavugan** [comment]
@talha-amir-fm as I said before I've just followed lib installation instruction https://pypi.org/project/django-cors-headers/. As far as I remember, I didn't do anything special. It was quite a long time ago :)
