### ISSUE TITLE
Examples for bi-directional UUID support

### ISSUE THREAD

**Issue by imsickofmaps** [graphql-python/graphene-django#29]
It seems like UUID model fields get converted here:
 https://github.com/graphql-python/graphene-django/blob/master/graphene_django/converter.py#L78-L81

which means they show up as base64 encoded `SWRlbnRpdHlOb2RlOmMxYmZiNTFjLWUyYTItNGM3YS1hOWQ5LTNiMDA4ODA2YmFhOA==` in query responses. However, when sending them back in a mutation, it complains `badly formed hexadecimal UUID string` in the error field. Sending the hex instead (e.g. `c1bfb51c-e2a2-4c7a-a9d9-3b008806baa8` works but is annoying to not be able to turn it around.

At the moment I'm using a helper function to decode and strip the `IdentityNode:` from the front:

```
def uuid_hex_from_b64(encoded):
    decoded = base64.b64decode(encoded)
    return decoded.split(b":")[1]
```

and use it like: 

```
new_club = {
    "name": input.get('name'),
    "treasurer_id": uuid_hex_from_b64(input.get('treasurer_id'))
}
club = Club.objects.create(**new_club)
```

This works but I'm not sure if this is a terrible idea or if it's sane, but some documentation of its usage as ok would save others like me hours of poking around! Thanks!

**Comment by Fandekasp** [comment]
:+1:, same problem here. Is there a reason behind encoding uuid ?

**Comment by alexnitta** [comment]
I left a comment here that provides a working solution: https://github.com/graphql-python/graphene-django/issues/460#issuecomment-425959368

**Comment by mvanlonden** [comment]
Looks like we found a solution. Will leave https://github.com/graphql-python/graphene-django/issues/460 open to track the documentation need

**Comment by amzhang** [comment]
Why not make the mutation decode the base64 and extract the id. So exactly what @imsickofmaps is doing on the client but do it on the server.

I have a feeling the authors have a reason using the plain id in the mutations, wondering what the reasoning is.
