### ISSUE TITLE
Bug while upgrading to 2.0 with filterssets

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#302]
While trying to upgrade to 2.0 I've gotten this error

```
"'Meta.fields' or 'Meta.exclude' to the %s class." % cls.__name__
AssertionError: Setting 'Meta.model' without either 'Meta.fields' or 'Meta.exclude' 
has been deprecated since 0.15.0 and is now disallowed. 
Add an explicit 'Meta.fields' or 'Meta.exclude' to the DealroomListingsFilterSet class.

```

I'm not defining a custom filterset class

This is my node
```python
'''node for dealroom filters'''
from graphene.relay import Node
from graphene_django import DjangoObjectType

from graphene import String, Field


from apps.broker_dashboard.models import DealroomFilterSets

class DealroomFilterSetNode(DjangoObjectType):
    '''Node for DealroomFilterSets '''
    uuid = String(description='uuid')

    def resolve_uuid(self, args, request, info):
        return self.id

    class Meta:
        interfaces = (Node, )
        model = DealroomFilterSets
```

**Comment by BossGrand** [comment]
I ended up uninstall django-filters

**Comment by ChillyBwoy** [comment]
You can define field **filter_fields** as an empty list:
```python
class Category(DjangoObjectType):
    class Meta:
        model = CategoryModel
        filter_fields = []
        interfaces = (
            relay.Node,
        )
```

**Comment by BossGrand** [comment]
Ah gotcha thank you!

**Comment by AndreyMZ** [comment]
Why did you close this issue? This is a bug, and it is not fixed, although a workaround exists. Could you reopen this issue, please?

**Comment by Telofy** [comment]
+1

And the workaround doesn’t seem to work anymore: `TypeError: __init_subclass_with_meta__() got an unexpected keyword argument 'filter_fields'`.

**Comment by amreshprasad** [comment]
This is a problem for me as well. I have a situation where I need to do an OR operation on a few fields. I am doing that in the resolver method and through log messages in the resolver I can see I am getting the correct query set. But if there are any filter_fields defined in the DjangoObjectType wrapper class (around my model class), the filters are applied to my result set as an AND operation and I do not get the desired result set. Is there no way I can avoid setting a filter_field in my DjangoObjectType wrapper class?

Filter-fields and excludes are orthogonal to the model class. If I don't want to apply any filters or excludes, I should be able to get the entire table. Why is that not allowed?

If I set filter_fields to an empty list, i.e. [], I get the following error in my client:
```
{
  "errors": [
    {
      "message": "Unknown argument \"field1\" on field \"table1\" of type \"Query\".",
      "locations": [
        {
          "column": 30,
          "line": 2
        }
      ]
    },
    {
      "message": "Unknown argument \"field2\" on field \"table1\" of type \"Query\".",
      "locations": [
        {
          "column": 64,
          "line": 2
        }
      ]
    }
  ]
}

```
This is with 
graphene==2.0.1
graphene-django==2.0.0

**Comment by vladcalin** [comment]
I ran into the same issue even though I had both `Meta.model` and `Meta.fields` set on the FilterSet subclass. The issue was caused by the fact that I had a typo in the `DjangoFilterObjectType` definition (I had `fitlerset_class` instead of `filterset_class`) which for some reason, the reported error was completely misleading and confusing.
 
Just putting this here if somebody runs into the same issue and ends up on this closed issue from 2017 where it is stated that there is a bug in django_graphene but with no actual fix (just some workaround which might or might not work).

**Comment by austincollinpena** [comment]
For those struggling with filtering, but may be flexible for change in their code, this is what I used:
https://www.howtographql.com/graphql-python/7-filtering/

I was able to not have to use the Django Filter Object, but instead changed:

```
active_follow_ups_link = graphene.**Field**(FollowUpsToSendNode)
```
to
```
active_follow_ups_link = graphene.**List**(FollowUpsToSendNode)
```
And then I was able to call the filter on my object directly:
```
    @login_required
    def resolve_active_follow_ups_link(self, info):
        return FollowUpsToSend.objects.filter(user=info.context.user)
```
Is this ideal? Probably not. Does it work? For me, yes.
