### ISSUE TITLE
Don't know how to convert the Django class django_mysql.models.fields.json.JSONField

### ISSUE THREAD

**Issue by quytang** [graphql-python/graphene-django#303]
I've just added a [JSONField](http://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html) on my models and graphene said `Don't know how to convert the Django class django_mysql.models.fields.json.JSONField`.
I think it wasn't supported yet but are there any way to work around?

thanks

**Comment by quytang** [comment]
I end up with this snippet, thanks
```
import graphene
from graphene_django.converter import convert_django_field
from django_mysql.models import JSONField

@convert_django_field.register(JSONField)
def convert_json_field_to_string(field, registry=None):
    return graphene.String()
```

**Comment by spockNinja** [comment]
That's definitely the way to go for a quick way to add your own fields that graphene-django doesn't support.

We would also welcome an addition like that to `converter.py` that does something similar to the postgres `JSONField`.

I will also note that we personally overrode the graphene type to be a `graphene.GenericScalar`, and then the JSON flows through and you do not have to re-parse it on the client side.

**Comment by denis-ryzhkov** [comment]
I you found this issue looking for postgres-JSONField like me, maybe this patch will help you:
* Description: Ask `graphene_django` to convert `JSONField` to `GenericScalar` (JSON as is) instead of default `JSONString`
* Code: https://gist.github.com/denis-ryzhkov/59efc5be73eebd099a66cd549226fba9

**Comment by cb109** [comment]
`return graphene.GenericScalar()` did not work for me, I had to import like `from graphene.types.generic import GenericScalar` and then `return GenericScalar()` instead. It is a great workaround, the JSON is passed through as expected, thanks!

**Comment by dopeboy** [comment]
Adding some more color to this in case there are others who arrive from google:

Suppose you have a django model like so:

```
from django.contrib.postgres.fields import JSONField

class Rapper(models.Model):
    name = models.CharField()
    bars = JSONField()
```

Here's what the `Query` object and connecting type would look like:

```
from graphene.types import generic
from graphene_django.types import DjangoObjectType

from .models import Rapper

class RapperType(DjangoObjectType):
    bars = generic.GenericScalar()
    
    class Meta:
        model = Rapper
```

And here's what a sample GraphQL query and response end up looking like:

```
{
  rapper {
    name
    bars
  }
}
```

```
{
  "rapper": {
    "subject": {
      "name": "50 Cent",
      "bars": [
        "Joy wouldn't feel so good if it wasn't for pain",
        "It's your birthday"
      ]
    }
  }
}
```

**Comment by thongly** [comment]
@quytang and @spockNinja - Would it be helpful to add this to the docs?  I can make a PR.

Also, an issue I've come across is that I'm having to register separately for each and every schema.py file where a query utilizes the custom type.  I tried doing this at the the root schema.py, but it still errors out unless this is done at every single schema.py separately.
