### ISSUE TITLE
Custom Connection in 2.0

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#304]
What is the proper way to set a ModelNode Connection in 2.0?

The connection gets created by DjangoObjectType class. But I dont see how to overrride it with my own Connection

**Comment by BossGrand** [comment]
I have found the connection field on DjangoObjectType meta. How can I assign the attr without causing a circular import issue

```python

class MyConnection(Connection):
    count = graphene.Int()

    def resolve_count(self, info):
        return self.length

    class Meta:
        node = MyNode


class MyNode(DjangoObjectType):

    class Meta:
        interfaces = (Node, )
        model = MyModel

        connection = MyConnection


```

connection and node need to reference each other. But I get a not defined error trying to do it this way. I've also tried lambdas but that does not work either

**Comment by BossGrand** [comment]
I propose that we allow connection to be a lamda function similar to how Fields handle circular dependencies

**Comment by syrusakbary** [comment]
Sorry, just realized I closed this issue by mistake.

**Comment by BossGrand** [comment]
this was solved by the pull request

**Comment by helpse** [comment]
@BossGrand So what's the usage of connection_class on this scenario?

**Comment by helpse** [comment]
Answered here:
https://stackoverflow.com/questions/52746119/using-djangofilterconnectionfield-with-custom-connection-in-graphene-django/52746690#52746690
