### ISSUE TITLE
Call a model's method when querying for a field

### ISSUE THREAD

**Issue by jm2242** [graphql-python/graphene-django#305]
Let's say I have the following query:
```
query {
  spreadsheet(id: 50) {
    name, 
    user {
      id, username
    },
    rows {id} # this is the foreign key that I need to call a function on 
  }
}
```

and my spreadsheet Model looks like:
```
class Spreadsheet:
  objects = SpreadsheetManager()
  user = models.ForeignKey(User)
  name = models.CharField()
  rows = model.ForeignKey(RowGenerator)
  ...
```

currently my query class looks like:
```
class Query(graphene.ObjectType):

  spreadsheet = graphene.Field(SheetType,
        id=graphene.Int(),
        name=graphene.String()
    )

  resolve_sheet(self, info, **kwargs):
        sheet_id = kwargs.get('id')
        # name = kwargs.get('name')

        if sheet_id is not None:
            return Sheet.objects.select_related('user','rows').prefetch_related('projects').get(id=sheet_id)

        return None
```

rows is a foreign key to an object, that upon calling a function `generate_rows()`, generates row data. Currently, my query returns the id of the foreign key, but what I want to do is to call a function on that object, (`rows.generate_rows()`, for example). How would it be possible to tell graphene to call that function on the field, once we retrieve it from the database?

**Comment by jm2242** [comment]
would be happy to help contribute to this if this is currently not possible

**Comment by BossGrand** [comment]
This is definitely possible! 

Have you defined DjangoObjectNodes for your models?

I would put a field on Rows called generate_rows that returns whatever type you need it to. For the example i'll assume you want a list of strings

```python
class RowsNow(DjangoObjectType):
     class Meta:
           model = Rows

      generate_rows = graphene.List(graphene.String())
      def resolve_generate_rows(instance, info): 
           return instance.get_rows()
```

let me know if you have further questions!

**Comment by jm2242** [comment]
This is phenomenal! I'm ecstatic. Thanks so much for the post.

**Comment by Mhs-220** [comment]
@BossGrand Hey! 
is there any way to filter rows?
for example, if raw is a person table, and it has first name and last name... is there anyway to do this? :

```
class PersonNode ( DjangoObjectType ):
	class Meta:
		model = Person
		interfaces = ( graphene.relay.Node, )
		filter_fields = {
			'full_name': ['exact', 'icontains', 'istartswith'],
		}

	full_name = graphene.String()
	def resolve_full_name ( instance, info, **kwargs ):
		return " ".join([instance.first_name, instance.last_name])

```

**Comment by kneufeld** [comment]
@Mhs-220 did you ever figure out how to do this? I'm in the same boat.
