### ISSUE TITLE
GraphQLView fails when using session CSRF

### ISSUE THREAD

**Issue by nealedj** [graphql-python/graphene-django#307]
If `settings.CSRF_USE_SESSIONS == True` or using https://github.com/mozilla/django-session-csrf then Django rejects all AJAX POST requests made by the GraphQLView.

The GraphQLView reads the CSRF token from the cookie.

Perhaps it should be read from the DOM instead?

**Comment by dopeboy** [comment]
Because there's an attached PR here (thanks!), I'm going to close this one down.
