### ISSUE TITLE
How to match a resolver to a Node.Field

### ISSUE THREAD

**Issue by vinigfer** [graphql-python/graphene-django#312]
Not sure if the best place for this issue is here or at graphene repo (https://github.com/graphql-python/graphene), but here we go ...

I have a Node.Field that I want to match to a resolver in order to apply token authentication/authorization. But it seems the resolver is completely ignored. Here is a code sample:

```
from graphene_django.types import DjangoObjectType
from graphene_django.filter import DjangoFilterConnectionField
from graphene import ObjectType, Node, String

from core.utils import validate_token

from .models import Paciente


class PacienteType(DjangoObjectType):

    class Meta:
        model = Paciente
        interfaces = (Node, )
        filter_fields = ['id', 'nome']


class Query(ObjectType):

    paciente = Node.Field(PacienteType, id=String(), token=String())
    paciente_all = DjangoFilterConnectionField(PacienteType, token=String())

    def resolve_paciente(self, info, id=None, token=None):
        usuario_id = validate_token(token)
        if usuario_id is None:
            return None

        try:
            return Paciente.objects.get(pk=id)
        except:
            return None

    def resolve_paciente_all(self, info, token=None):
        usuario_id = validate_token(token)
        if usuario_id is None:
            return []
        return Paciente.objects.all()
```

Then I issue the following query
> 
```
{
    paciente(id: "UGFjaWVudGVUeXBlOjE=") {
      id
    }
}
```
> 

Which I expected to be blank, since I'm not supplying any auth token, but it does return with one result. Am I missing something here that I have not seem, or this may be a bug?

Thanks!

**Comment by BossGrand** [comment]
can you try printing in resolve_paciente to see if it is being ran?

**Comment by vinigfer** [comment]
I did place a ```pdb.set_trace()``` (python's debugger), and in fact it wasn't being called/stopped at all.

**Comment by mraak** [comment]
Try this, instead of:

`paciente = Node.Field(PacienteType, id=String(), token=String())`

do:

`paciente = graphene.Field(PacienteType, id=String(), token=String())`

or simply:

`paciente = graphene.Field(PacienteType)`

The documentation is non existent, and examples are very inconsistent, lack descriptions, lack the "why's", versions mixed, relay vs non-relay confused, etc. Looks like nobody is really in charge of this project so get ready for trial and error unfortunately.

**Comment by japrogramer** [comment]
to resolve a global id, inside a normal field do 
`relay.Node.get_node_from_global_id(info, id)`

**Comment by spockNinja** [comment]
@vinigfer 

If you want to implement something like token authentication, you probably want it outside of each individual resolver. I would suggest subclassing `GraphQLView` with django's `LoginRequiredMixin` (as seen [here](http://docs.graphene-python.org/projects/django/en/latest/authorization/#adding-login-required), and then adding the token authentication as one of your django authentication methods.

**Comment by Fire-Hound** [comment]
> to resolve a global id, inside a normal field do
> `relay.Node.get_node_from_global_id(info, id)`

I wish I knew how this worked, really is like magic to me

**Comment by JSv4** [comment]
Still an issue for me in 2021...
