### ISSUE TITLE
Feature Request: Use debug middleware to show number of queries executed?

### ISSUE THREAD

**Issue by mekhami** [graphql-python/graphene-django#317]
To more easily solve n+1 and related problems, can we add the 'total number of queries executed by this graphql query' to the debug middleware? Is this even possible?

**Comment by spockNinja** [comment]
It might be possible. However, there are some good tools that already do things like this. My team is using the [silk](https://github.com/jazzband/silk) profiling tool.

It is fantastic for modern django apps that utilize a lot of ajax queries. Just make sure to turn it off when you don't need it, as it can slow things down quite a bit with it's own queries.
