### ISSUE TITLE
Typo code error in Docs

### ISSUE THREAD

**Issue by kamranhossain** [graphql-python/graphene-django#321]
Thanks for your awesome work @syrusakbary. Here I find a typo code error in docs. In your 1st part of docs. Within **Getting single objects** section there is four error in last parts. It is typo mistake. Writing **kwargs as kargs**. May be this part need to modify. 
![graphene-django](https://user-images.githubusercontent.com/19626317/32668306-5e107eb0-c667-11e7-9119-296a5b4fec82.png)

**Comment by spockNinja** [comment]
Fixed in #311.
