### ISSUE TITLE
get_node() never called

### ISSUE THREAD

**Issue by gijs** [graphql-python/graphene-django#331]
Hi,

I'm trying to override `get_node()` but it never gets called... Am I doing it wrong?

(python 3.6, graphene-django 2.0)

```python
# some imports

@convert_django_field.register(PointField)
def convert_PointField(field, registry=None):
    return graphene.String()


class SomeNode(DjangoObjectType):
    class Meta:
        model = SomeModel
        filter_fields = ['code', 'title', ]
        interfaces = (relay.Node, )

    def resolve_geometry(self, *_):
        logger.error(self.geometry)
        return '{}'.format(str(self.geometry))

    @classmethod
    def get_node(cls, info, id):
        # node = SomeModel.object.filter(width=0)
        logger.error("get_node()")  # This never gets fired?
        return {}
```

Any ideas?

thx!

**Comment by japrogramer** [comment]
try this
` inst = relay.Node.get_node_from_global_id(info, input.get('id'))`

**Comment by spockNinja** [comment]
@gijs 

Overriding `get_node` should definitely be possible, but it's hard to tell where it's going wrong without a little more context. Could you also share the relevant parts of your root query schema, a sample query, and any other code/context that might play into reproducing the issue?

**Comment by gijs** [comment]
I'm sorry! I forgot to get back to this issue to report that it was due to my own misunderstanding.
I was under the impression that it would always be called but it only gets called for individual objects, if you know what I mean.
I'll close it now. Thanks for this library, it's really good!

**Comment by ardenn** [comment]
I am experiencing an issue similar to this. `get_node` doesn't seem to be called in my case.

This is a sample of my code

```
class DocumentGQL(DjangoObjectType):
    class Meta:
        model = Document
        interfaces = (graphene.relay.Node,)

    @classmethod
    def get_node(cls, info, id):
        logger.info(id)
        ...

class Query(graphene.ObjectType):
    document = graphene.relay.Node.Field(DocumentGQL)
```
And console output
`"POST /graphql/ HTTP/1.1" 200 26`

Graphql Query
```
{
  document(id:"e551a1e5-6fae-47c2-be87-3feeb802bf7f"){
    description
    id
  }
}
```
Graphql output
```
{
  "data": {
    "document": null
  }
}
```

**Comment by japrogramer** [comment]
Add this to your schema 
```
node = relay.Node.Field()
```

And query node not document

**Comment by ardenn** [comment]
> Add this to your schema
> 
> ```
> node = relay.Node.Field()
> ```
> 
> And query node not document

Isn't this exactly what I did, my model is called `Document`, so my node is `document`

**Comment by smac89** [comment]
I think I answered your question here: https://stackoverflow.com/a/68385814/2089675
