### ISSUE TITLE
In mutation, info.context.user returns AnonymousUser

### ISSUE THREAD

**Issue by Northshoot** [graphql-python/graphene-django#343]
When making queries, the info.context.user returns a correct user.
However, then making the mutation, the same call to the info.context.user return AnonymousUser

Any suggestions what is going on?

**Comment by spockNinja** [comment]
As far as I can tell, we do not handle Mutations and Queries differently when it comes to their context. It should be calling [get_context](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/views.py#L268) regardless.

Do you have more context you can share, or the minimum code it takes to reproduce the problem?

**Comment by Northshoot** [comment]
Hey,

It was my bad configuration of apollo-client and JWT middleware for authentication.

Thanks for great job guys!

L

**Comment by muelphil** [comment]
Could you please provide further information as to where the configuration issue was?
I'm currently running into the exact same issue.

**Comment by jordychetty** [comment]
I see that this question still seems to be popular given the number of likes from the previous comment.

To anyone experiencing a similar issue:

`graphql.error.located_error.GraphQLLocatedError: 'NoneType' object has no attribute 'context'`

it may be caused by the ordering of the parameters. 

Graphene always stores the mutation context, and hence the user transitively, in the second non-default parameter it receives. 

Using,

```python3
def mutate(root, info, **kwargs)
```

The `user` is retrieved by calling `info.context.user`.

Using,

```python3
def mutate(info, root, **kwargs)
```

You would retrieve the `user` using `root.context.user`.

Always ensure that your parameter ordering is consistent throughout your function definitions.

**Comment by chrisamow** [comment]
> Hey,
> 
> It was my bad configuration of apollo-client and JWT middleware for authentication.
> 
> Thanks for great job guys!
> 
> L

@Northshoot I'm having this problem, oddly enough in production code only - can you share what your config issue was?
(I am using vue/apollo/graphene)  Thx for any help you can remember from years ago :)

**Comment by axwalker** [comment]
@chrisamow continuing the chain here - but I'm in the same situation as you now! A problem only in production. Did you solve your issue?

**Comment by ddn-jacob** [comment]
In my case, It was logged in django admin user in domain.com/admin.

**Comment by HakanPuente** [comment]
> I see that this question still seems to be popular given the number of likes from the previous comment.
> 
> To anyone experiencing a similar issue:
> 
> `graphql.error.located_error.GraphQLLocatedError: 'NoneType' object has no attribute 'context'`
> 
> it may be caused by the ordering of the parameters.
> 
> Graphene always stores the mutation context, and hence the user transitively, in the second non-default parameter it receives.
> 
> Using,
> 
> ```python
> def mutate(root, info, **kwargs)
> ```
> 
> The `user` is retrieved by calling `info.context.user`.
> 
> Using,
> 
> ```python
> def mutate(info, root, **kwargs)
> ```
> 
> You would retrieve the `user` using `root.context.user`.
> 
> Always ensure that your parameter ordering is consistent throughout your function definitions.


root.context.user is also return anonymous user, any new solution?
