### ISSUE TITLE
Access Django Model primary key

### ISSUE THREAD

**Issue by rattrayalex** [graphql-python/graphene-django#35]
Hi, 

I would like to do something like this: 

``` graphql
allIngredients {
  edges {
    node {
      id
      pk
      name
    }
  }
}
```

where the result would be something like this:

``` json
{
  "id": "Q29tcGFueU5vZGU6MQ==",
  "pk": 42,
  "name": "carrots"
}
```

Is this possible? How could it be achieved?

Perhaps relatedly, how could I expose model properties?

Thanks!

**Comment by yen223** [comment]
I wrote an interface that exposes the model primary key:

```
import graphene


class DjangoPkInterface(graphene.Interface):
    """
    Exposes the Django model primary key
    """
    pk = graphene.ID(description="Primary key")

    def resolve_pk(self, args, context, info):
        return self.pk
```

You can expose model properties by defining resolvers, as I did above.

**Comment by bcb** [comment]
Looks like `id` is already the primary key?

https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py#L103

**Comment by yen223** [comment]
Did something change? The `id` field used to be reserved for the relay node id (which was the base64-encoding of the model name + instance primary key)

**Comment by bcb** [comment]
Yes that seems to have been added a couple of weeks ago (#20)

**Comment by syrusakbary** [comment]
The `id` retrieves automatically the Primary Key in the Django Model instance by default, as @bcb pointed.

You can expose model properties by creating a field for the property.
For example, if your Model looks something like:

```python
# Here the Django Model
class MyModel(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

# Here the Graphene Type
class MyModelType(graphene_django.DjangoObjectType):
    class Meta:
        # This will automatically convert the first_name and last_name fields to GraphQL fields
        model = MyModel
    
     full_name = graphene.String()
     # If we don't specify the resolver, it will try to resolve using the instance.full_name
```

**Comment by syrusakbary** [comment]
Closing this issue, but feel free to comment or reopen it if something is not clear! :)

**Comment by bcb** [comment]
Can I just clarify - so `id` retrieves the primary key, unless the `Node` interface is used in which case it's the relay node id?

Is it worthwhile adding `resolve_pk` to `DjangoObjectType` permanently?
