### ISSUE TITLE
Return a data without a model, more like a function.

### ISSUE THREAD

**Issue by joeydebreuk** [graphql-python/graphene-django#350]
I want to calculate a price of a total package, which depends on many factors and involves many models.
This results in a complex query that involves filtering and a lot of logic on the front-end. 

Is there any way I could write a custom resolver that returns an Int without returning it with a model? 

Maybe something like:

    class PackagePrice(DjangoObjectType):
        class Input:
            arg_1 = String()
            arg_2 = String()
    
        @classmethod
        def resolve_package_price(root, info, **input):
            arg1 = input.get("arg1")
            arg2 = input.get("arg2")
            #etc...
    
            get_needed_thing1 = Model.objects.get(
                arg=arg,
                #etc
            )
            get_needed_thing2 = Model.objects.get(
                arg=arg,
                #etc
            )
            #etc...
    
            package_price = "result of a lot of calculations and lookups done above"
    
                return PackagePrice(Int=package_price)

with a query like:

    query{
          packagePrice(
              input:{
                  arg1:"arg1",
                  arg2:"arg2",
                  etc:"etc"
                }){
            packagePrice
          }
        }

**Comment by nyejon** [comment]
Any luck finding a solution?

**Comment by Prince-Leto** [comment]
This is what `graphene` does. `graphene-django` basically _just_ add the `DjangoObjectType` class to wrap a django model into graphene.

Here is a bit of documentation on how to create a schema: http://docs.graphene-python.org/en/latest/quickstart/#creating-a-basic-schema

**Comment by joeydebreuk** [comment]
Yes! Sorry should have closed this. Apparently this is very simple, Just write `something` in your schema and define a function in your schema with the prefix resolve_, so: `resolve_something`. Easy pattern to return anything you want. 

More logic on back-end is more better.

Example:

Add this to Query in schema
```
package_prices = Field(
        PackagePriceNode,
        input=PackagePriceInput()
    )

    def resolve_package_prices(self,info,input):
        return create_package_prices(input)
```

The node and the input:
```
class PackagePriceFields(AbstractType):
    pass


class PackagePriceNode(ObjectType, PackagePriceFields):
    total_price = Int()
    ...


class PackagePricesInput(InputObjectType, PackagePriceFields):
    search = String()
    ...
```

And `create_package_prices(input)` is a function that takes the input and returns the node.

Access input params with: `input.search`

And return node like:
```
    return PackagePriceNode(
        total_price=total_price,
        ...
)
```

**Comment by fkromer** [comment]
This stackoverflow thread could be helpful as well: https://stackoverflow.com/questions/45789617/graphene-django-without-django-model
