### ISSUE TITLE
Allow_subscriptions argument is not supported by class GraphQLView

### ISSUE THREAD

**Issue by dionyself** [graphql-python/graphene-django#351]
hello,
I'm not able to implement subscriptions 
I get some error: `Subscriptions are not allowed. You will need to either use the subscribe function or pass allow_subscriptions=True`
even i am doing that
`url(r'^graphql', PrivateGraphQLView.as_view(graphiql=True, schema=tenant_schema, allow_subscriptions=True))`

i'm using graphene_django 2.0
ref:
https://github.com/graphql-python/graphene-django/blob/670437d756c6919f06348903fbe7007652fcd126/graphene_django/views.py#L67
https://github.com/graphql-python/graphene-django/blob/master/graphene_django/views.py#L270

Thank you for your help

**Comment by mlugowska** [comment]
Hi, 
I met the same error. Any news/updates?

**Comment by kavink** [comment]
@syrusakbary @hballard thoughts on how I can work around this ? mainly trying to make flask work.

**Comment by prokher** [comment]
As far as I understand, `GraphQLView` implements Django's view for GraphQL, how do you expect it to enable subscriptions? I mean, it is rather difficult (well, impossible) to enable GraphQL subscriptions over plain HTTP (w/o tricks like long polling) cause to work with subscriptions you need some kind of sever-side events. That is exact reason we started implementing GraphQL over WebSockets. You can take a look [here](https://github.com/datadvance/DjangoChannelsGraphqlWs).

**Comment by prokher** [comment]
@LukeVideo OK, the problem is clear. I will try to improve.

**Comment by dopeboy** [comment]
We're marshaling resources for tighter integration with channels in #120 - I'd redirect you all there.
