### ISSUE TITLE
AttributeError while getting results

### ISSUE THREAD

**Issue by dionyself** [graphql-python/graphene-django#353]
Hi,
https://github.com/graphql-python/graphene-django/blob/master/graphene_django/views.py#L158-L166
this block of code assumes that the response willbe always an instance of ExecutionResult(), but that's not always true.
I am getting something like:
`if execution_result.errors:
AttributeError: 'AnonymousObservable' object has no attribute 'errors'

Ref:
https://github.com/graphql-python/graphql-core/blob/caa42e8c6785a3db52eb0215813263e2bd8b64f8/graphql/execution/executor.py#L70-L76
`

**Comment by mlugowska** [comment]
Have you found any solution how to handle this error?

**Comment by ambientlight** [comment]
wonder if https://github.com/graphql-python/graphql-ws/issues/8#issuecomment-482062178 helps
