### ISSUE TITLE
creating a django-filter to allow for OR type searches

### ISSUE THREAD

**Issue by KaiserKarel** [graphql-python/graphene-django#355]
Looking for a way to allow for OR type searches, e.g.:

```
{
  allAccountTransactions(
    senderid: "Foo",
    recipientid:"Foo" ) {
    edges {
      node {
        senderid
        recipientid
        amount
      }
    }
  }
}
```
This currently returns a set where senderid == "Foo" AND recipient == "Foo". I'd like a way to query so that I get a set where  senderid == "Foo" OR recipient == "Foo".

I reckon I need to override a method in the Filterset, to instead of 
```python
class FilterFoo:
      def queryset():
          Mymodel.objecs.filter(condition_1).filter(condition_2)
```
do:
```python
from django.db.models import Q

class FilterFoo:
    def queryset():
          MyModel.objects.filter(Q(condition_1) | Q(condition_2))
```

However I found django-filter a bit abstract. Anyone here who can point me in the right direction?

**Comment by urbandove** [comment]
Personally, I leave django-filter as is and add an extra variable to the schema endpoint and use resolve_sechema_endpoint to do the OR search

eg:

```
all_items = DjangoFilterConnectionField(MyNode,searchTerm=graphene.String())
def resolve_all_items(self, info, **kwargs)):
    queryset = MyModel.objects.all()
    searchterm = kwargs.get('searchTerm', '')
    if searchterm:
        queryset = queryset.filter(Q(field1__icontains=searchterm) | Q(field2__icontains=searchterm))
    return queryset
```

but if there is a better way i'd love to hear

**Comment by phalt** [comment]
The best way is to overwrite the `resolve_*` method as @urbandove suggested. Closing as resolved.
