### ISSUE TITLE
graphene-django docs link to graphene repo instead

### ISSUE THREAD

**Issue by edmorley** [graphql-python/graphene-django#357]
Hi!

When on pages like http://docs.graphene-python.org/projects/django/en/latest/introspection/ , the GitHub logo top right of the page links not to this repository, but to https://github.com/graphql-python/graphene/ instead. This meant that I inadvertently filed an issue against that page against the graphene repo rather than here.

**Comment by jkimbo** [comment]
This is still an issue

**Comment by edmorley** [comment]
Not stale

**Comment by edmorley** [comment]
> Not stale

**Comment by edmorley** [comment]
Please can you reopen the issue?

I can still reproduce it.

Or if this is a "it's not possible to fix", then could you leave a comment saying that, and close the issue as wontfix instead (the new GitHub close status).

Or if this is pending a fix that's merged but not deployed, then could you mention that in a comment and link to the commit or PR that fixed it?

Thanks
