### ISSUE TITLE
Docs link to 'Babel Relay Plugin' 404s

### ISSUE THREAD

**Issue by edmorley** [graphql-python/graphene-django#358]
Hi!

On this page:
http://docs.graphene-python.org/projects/django/en/latest/introspection/

...the `Babel Relay Plugin` link (pointing at https://facebook.github.io/relay/docs/guides-babel-plugin.html) 404s.

I had a rummage to try and find the new location but didn't have much luck.

**Comment by changeling** [comment]
This should be fixed now with https://github.com/graphql-python/graphene-django/pull/641.
