### ISSUE TITLE
Nullable ForeignKey not supported

### ISSUE THREAD

**Issue by Audace** [graphql-python/graphene-django#374]
On a number of models, I need to have a nullable foreign key. For example, the Message model looks like this:
```
class Message(TimeStampedModel):
    text = models.TextField()
    session = models.ForeignKey(to=Session, on_delete=models.CASCADE)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    time = models.DateTimeField()
    slack_event = models.ForeignKey(to=SlackEvent, on_delete=models.CASCADE, related_name='message', null=True)
```

Unfortunately, I'm unable to query for slackEvent although I am able to drill down into both session and author.

For example, this works...
```
{
  messages {
    author {
      username
    }
  }
}
```
...while this does not.
```
{
  messages {
    slackEvent {
      timestamp
    }
  }
}
```

Has anyone run into this issue before? If so, would be grateful for any guidance on how to support querying a nullable foreign key relationship.

**Comment by hassanzadeh** [comment]
Hey did you solve this?
I have the same issue.

**Comment by hectorip** [comment]
@hassanzadeh @Audace I've found that for being able to query a foreign key you need to expose that model in the Query and creating the Graphene model, the resolver, etc.

**Comment by alehyen** [comment]
you just need to add the type for that model
`from graphene_django.types import DjangoObjectType
class SlackEventType(DjangoObjectType):
    class Meta:
        model = SlackEvent
`
