### ISSUE TITLE
I think the model converter is handling "null" incorrectly

### ISSUE THREAD

**Issue by Singletoned** [graphql-python/graphene-django#375]
I think that the converter code is generating the "required" param incorrectly.  It is basing it on Django's "null" attribute, rather than the "blank" attribute.

For example here: https://github.com/graphql-python/graphene-django/blob/master/graphene_django/converter.py#L121

[Documentation][1] for "blank" suggests that that is the one that should be used for validation, whereas "null" just refers to whether null values should be converted to empty strings or not.

[1]: https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.Field.blank

I have a patch for this that I can send if you are interested.

Thanks

Ed

**Comment by dopeboy** [comment]
Can you attach some sample code here that would generate this bug?

**Comment by Singletoned** [comment]
I'm not using GraphQL anymore I'm afraid and I'm working for a different company now and don't have access to my old code.  Sorry.
