### ISSUE TITLE
Update a model with a mutation doesn't return a Global ID

### ISSUE THREAD

**Issue by vied12** [graphql-python/graphene-django#376]
Hello and well done for this module !

I'm trying to update a model with a mutation, but the result include the django id instead of the expected `global id`. Did I miss something ?
Thanks a lot

```python
@classmethod
    def mutate_and_get_payload(cls, root, info, **input):
        ''' Add the context (request) to the serializer '''
        track = None
        if input.get('client_mutation_id'):
            instance = SomeModel.objects.get(
                pk=from_global_id(input['client_mutation_id'])[1],
                created_by=info.context.user,
            )
        serializer = cls._meta.serializer_class(instance=instance, data=input, context={'request': info.context})
        if serializer.is_valid():
            return cls.perform_mutate(serializer, info)
        else:
            errors = [
                ErrorType(field=key, messages=value)
                for key, value in serializer.errors.items()
            ]
            return cls(errors=errors)
```

**Comment by caonUlisses** [comment]
Hi,
Just to make sure I understand the issue: when you try to execute the mutation, you want to be able to get the global id back and it does not show up or you get the django model id instead?

**Comment by vied12** [comment]
Hi!
Yes I have now the Django model id  and  would prefer to have the Global id.

**Comment by annshress** [comment]
I recently went through the similar issue, this is what I have been doing.

https://medium.com/@anish.shrestha/graphene-clientmutationid-on-creation-60f82128e6f

**Comment by janosroden** [comment]
I faced with the same effect when I tried to use an interface which had an `id` property:

```python
class A(Interface):
    id = ID(required=True)

class BNode(DjangoObjectType):
    class Meta:
        model = BClass
        interfaces = (relay.Node, A)
```

When I removed the `id` from A then I got global id again
