### ISSUE TITLE
returned pk ids are string by default - how to serialize pks as int

### ISSUE THREAD

**Issue by codekiln** [graphql-python/graphene-django#383]
I was surprised to discover that by default, all `DjangoObjectType` schema nodes had primary key ids that were strings:

```python
class UserType(DjangoObjectType):
    id = graphene.Int(source='pk')
    is_current_user = graphene.Boolean()

    class Meta:
        model = User

    def resolve_is_current_user(self, info):
        current_user = info.context.get('current_user')
        if current_user:
            return self.id is current_user.id
        return False

class UsersQuery(graphene.ObjectType):
    users = graphene.List(UserType)
    def resolve_users(self, info, **kwargs):
        return User.objects.all()

schema = graphene.Schema(query=ChatQuery)

gql_to_execute = """
query {
  users {
    id
    username
    isCurrentUser
  }
}
"""

current_user = User.objects.get(id=1)
result = schema.execute(gql_to_execute, context_value={"current_user": current_user}

print(json.dumps(result.data, indent=4))
printed = {
    "users": [
        {
            "id": "3",
            "name": "User Three",
            "username": "user3",
            "isCurrentUser": false,
            "photoUrl": ""
        },
        {
            "id": "2",
            "name": "User Two",
            "username": "user2",
            "isCurrentUser": false,
            "photoUrl": ""
        },
        {
            "id": "1",
            "name": "User One",
            "username": "user1",
            "isCurrentUser": true,
            "photoUrl": ""
        }
    ]
}
```

After seeing [`test_should_auto_convert_id`](https://github.com/graphql-python/graphene-django/blob/1bea96b31e9e8e77593946b78ab39b93d6f2cfec/graphene_django/tests/test_converter.py#L82) asserted that `AutoField` instances were converted to `graphene.ID` types, I looked up the [graphene type definition](https://github.com/graphql-python/graphene/blob/master/graphene/types/scalars.py#L149) and noticed that the serializer for `graphene.ID` is `str`. This might make sense for graphene, but I don't think it makes sense for django-graphene, where most users will have integer primary keys from relational databases.

I was able to coerce the id to an int by explicitly marking the field type as an int:

```python
class UserType(DjangoObjectType):
    id = graphene.Int(source='pk')
    is_current_user = graphene.Boolean()
```

I ended up subclassing `DjangoObjectType` to make this customization for all of my Django Model nodes, but this won't help other users who wish to keep their primary key type intact.

Would `django-graphene` be open to a PR adding this directly to `DjangoObjectType`?

**Comment by rafalp** [comment]
Hiya @codekiln, fellow Django/React dev here.

Actually you want to serialize your identifiers to strings before passing them to frontend, because both JavaScript and JSON requires object keys to be strings, so normalizing them before passing them to frontend will save you edge bugs where object's id in map managed by your state library is a string, but value returned from DB is integer, failing `1 === '1'` test.

Here's quick test using chrome's console:
<img width="165" alt="zrzut ekranu 2018-01-29 o 17 06 37" src="https://user-images.githubusercontent.com/750553/35520261-d500ee36-0516-11e8-9eb4-d7c263deb2d6.png">

Different stacks cast id to string at different moment, eg. Ember-Data does it on client's side, but this is pattern is common in app development.

**Comment by dperetti** [comment]
I beg to differ. 
It's an int in Django, therefore I expect the frontend to get an int as well. Period.
What I don't expect: the fact that graphene-django assumes that my frontend state is managed with string ids (which is not).

**Comment by jkimbo** [comment]
@dperetti @codekiln in GraphQL all `ID` types are represented as strings: https://graphql.org/learn/schema/#scalar-types

> ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

graphene-django has made the decision that Django ID's should be mapped to the GraphQL concept of ID's and I think that is the right decision. You can always work around it like @codekiln has by explicitly mapping the Django field to a graphene Int field:

```python
class UserType(DjangoObjectType):
    id = graphene.Int(source='pk')
```

**Comment by dopeboy** [comment]
I think we've reached a resolution here. DM if you feel otherwise, happy to reopen if I think there's a case for it.

**Comment by zafaralam** [comment]
> @aj07mm I assume that's because you are implementing the relay `Node` interface on your `QuestionNode` type? The relay `Node` interface expects the `id` type to be of type `ID` so trying to set it to be an `Int` will fail.

Was there any solution to this?

**Comment by jedie** [comment]
> didn't worked with the last answer:
> 
> ```
> AssertionError at /graphql
> Node.id expects type "ID!" but QuestionNode.id provides type "Int".
> ```

```
class UserType(DjangoObjectType):
    id = graphene.ID(required=True)
```

isn't it?

**Comment by tcleonard** [comment]
I have added 2 PRs in the graphene repository that could solve this issue I think: https://github.com/graphql-python/graphene/issues/1276

**Comment by thomas-arun** [comment]
> > @aj07mm I assume that's because you are implementing the relay `Node` interface on your `QuestionNode` type? The relay `Node` interface expects the `id` type to be of type `ID` so trying to set it to be an `Int` will fail.
> 
> Was there any solution to this?

For anyone looking for a solution. This is how I did a workaround.

I created a Mixin as follows:

```
class InjectExtraFields():
    id = graphene.Int(source='pk')
```

and then used this Mixin in front of all my Nodes as follows:

```
class FooNode(InjectExtraFields, DjangoObjectType):
    class Meta:
        model = Foo
        ...
        use_connection = True
```
