### ISSUE TITLE
Allow to exclude output fields in SerializerMutation

### ISSUE THREAD

**Issue by patrick91** [graphql-python/graphene-django#386]
Hello, I was trying to customise the output of a SerializerMutation in order to have it nested[1]

For now I made a custom SerializerMutation that accepts a `return_output_fields` that when it is False it will not return any output fields other than the errors.

@syrusakbary @spockNinja what do you think? I can send a PR with this change 

```python
class CreateCompany(SerializerMutation):
    company = graphene.Field(CompanyType)

    class Meta:
        serializer_class = CompanySerializer
        return_output_fields = False

    @classmethod
    def perform_mutate(cls, serializer, info):
        obj = serializer.save()

        return CreateCompany(company=obj)
```

[1] I'm doing this because I want to reuse the same Type for a query and a Mutation, so that I can leverage the client cache better :)

**Comment by patrick91** [comment]
@spockNinja what do you think of this?

**Comment by sliverc** [comment]
I would also be interested in such a change (currently I use a custom mutation class to accomplish this)

The form mutation implementation uses name `return_field_name` to define how output field is named. Wouldn't be good to use the same? Maybe to be backwards compatible a slight difference would be that there is no default and return_field_name needs to be manually assigned for this to work.

I am also happy to work on this in case you won't get around. Let me know.

**Comment by editkid** [comment]
Would love this feature also. +1

**Comment by editkid** [comment]
Furthermore, if a ModelSerializer is used and any fields are added to the serializer that don't exist on the model then an `AttributeError` is thrown from `perform_mutate` on this line:
https://github.com/graphql-python/graphene-django/blob/923d8282c771244751d483553e173a15230a84b5/graphene_django/rest_framework/mutation.py#L141

It'd be good to be able to exclude some fields from the output therefore, then their attribute values wouldn't be requested at this stage.
