### ISSUE TITLE
Conrtol nested object types

### ISSUE THREAD

**Issue by trixden** [graphql-python/graphene-django#393]
For example i have a models
```python
class Projects(models.Model):
  title = model.CharField(...)

class Tasks(models.Model):
  title = model.CharField(...)
  user = model.ForeignKey(User, related_name="tasks" ...)
  project = model.ForeignKey(Projects, related_name='tasks' ...)
```

Queries:

```python
projects = graphene.List(ProjectsObjectType)
def resolve_projects(self, info, **kwargs):
  return Projects.objects.all()

tasks = graphene.List(TasksObjectType, projectId=graphene.Int())
def resolve_tasks(self.info, **kwargs):
  projectId = kwargs.get('projectId')
  if not info.context.user.is_authenticated():
    return Exception('Not Authenticated')
  objects = Tasks.objects
  if projectId is not None:
    objects = objects.filter(project=projectId)
  return objects.all()
```

If i tried to get tasks from query:

```
query {
  tasks (
    projectId: 1
  ) {
    title
    ...
  }
}
```
, i get all tasks for needed project for current user only. That's good. But, if i send this query:

```
query {
  projects {
    title
    ...
    tasks {
      id
      title
    }
  }
}
```
, i get all tasks for all users without any control. That's big hole! If i decide to exclude any foreign fields in ObjectTypes, i take same REST. Thats senselessly. How to control relations in django graphene?

**Comment by dopeboy** [comment]
Thanks for filing this issue @trixden. Per your code, graphene is behaving as expected. In your first code snippet, that will return all the tasks _for that project_, not for the current user. 

For your second snippet, you're asking graphene to fetch every project in the system and when doing so, every task within every project. 

What it seems like you're after is making sure when a user fetches all projects, they only see their own tasks within those projects. To achieve that, I imagine you'd need something like:

`return Task.objects.filter(owner=info.context.user)`.

Does that make sense?

**Comment by dopeboy** [comment]
Closing this down due to inactivity.
