### ISSUE TITLE
No request passed to custom filter as self.request

### ISSUE THREAD

**Issue by nyejon** [graphql-python/graphene-django#399]
Hi,

I could be doing something wrong or else this is a bug. 

When creating a custom filter and I override the queryset as per the Filtering docs:

```
   @property
    def qs(self):
        # The query context can be found in self.request.
        print(self.request.user)
        return super(CustomFilter, self)
```

self.request is always None

**Comment by jsep** [comment]
I have the same issue

**Comment by jsep** [comment]
It's working for me now, I just updated the version to 2.0

**Comment by nyejon** [comment]
I am on version 2. Could you please give an example of how you got it to work?

**Comment by codekiln** [comment]
In my case, I was using `DjangoFilterConnectionField`, and I could see that it's `connection_resolver` method wasn't supplying the `request` parameter. If you [look at the master branch](https://github.com/graphql-python/graphene-django/commits/master/graphene_django/filter/fields.py), you can see that the `request` object was just added as a parameter in 1db1cbdd9.

**Comment by nyejon** [comment]
Great thanks, yes it does seem like there has been a lot of work done since the last release. Looking forward to the update...

**Comment by nyejon** [comment]
Ok, using the master branch seems to fix things as stated,

**Comment by danpalmer** [comment]
Hey @syrusakbary any chance this could be released? It feels like a pretty major blocker (certainly is for our use case of filtering a list for a logged in user), and installing from master breaks a lot of Python packaging workflows, not to mention means that other unreleased and possibly untested code might be used in production.

**Comment by zbyte64** [comment]
Just experienced this .

django-filter == 2.2.0
django-graphene == 2.13.0

**Comment by zbyte64** [comment]
Nvm, user error, fix still applies.
