### ISSUE TITLE
Apollo upload client support

### ISSUE THREAD

**Issue by tvorogme** [graphql-python/graphene-django#404]
Hi! 

I'm trying to use default example from [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client). But it doesn't work with graphene. 

The problem is - the rquest headers contains ```content-type: multiform-data```,  [so ```parse_body``` from ```views.py``` returns ```request.POST```](https://github.com/graphql-python/graphene-django/blob/dbd3957a9f622573b2b106546f3accc48f5d5b41/graphene_django/views.py#L224), BUT [```get_graphql_params``` parse query only from GET request](https://github.com/graphql-python/graphene-django/blob/dbd3957a9f622573b2b106546f3accc48f5d5b41/graphene_django/views.py#L293)

And request contains query, but in POST...
----
![latest-screenshot](https://user-images.githubusercontent.com/19264196/36693999-f976da08-1b4d-11e8-9af9-a46349f5c611.png)
---
So, my solution for apollo-upload-client is:

```
    @staticmethod
    def get_graphql_params(request, data):
        query = request.GET.get('query') or data.get('query')
        variables = request.GET.get('variables') or data.get('variables')
        id = request.GET.get('id') or data.get('id')

        # try to get params from POST
        if not query:
            if request.POST.get("operations"):
                parsed_post = json.loads(request.POST.get("operations"))

                if 'query' in parsed_post:
                    query = parsed_post['query']

                if 'variables' in parsed_post:
                    variables = parsed_post['variables']


        if variables and isinstance(variables, six.text_type):
            try:
                variables = json.loads(variables)
            except Exception:
                raise HttpError(HttpResponseBadRequest(
                    'Variables are invalid JSON.'))

        operation_name = request.GET.get(
            'operationName') or data.get('operationName')
        if operation_name == "null":
            operation_name = None

        return query, variables, operation_name, id
```
After that, all appear to be ok:
----
![latest-screenshot](https://user-images.githubusercontent.com/19264196/36694415-67733af0-1b4f-11e8-8eb7-e1e92554f2a6.png)
----
![latest-screenshot](https://user-images.githubusercontent.com/19264196/36694435-7c4443ca-1b4f-11e8-9673-98264e7fbb7c.png)

**Comment by creimers** [comment]
@tvorogme Promising. Would you mind also sharing your Mutation class (or at least the gist of it) as well as how you execute the mutation in the client? Thanks!

**Comment by tvorogme** [comment]
@creimers, not a problem.
https://gist.github.com/tvorogme/1c0794e1455bf3fc61162e2915ec2462

**Comment by Eraldo** [comment]
I am also trying to get [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) to play together with `graphene-django`.
This issue seems related: https://stackoverflow.com/questions/48713911/apollo-upload-client-and-graphene-django

**Comment by dopeboy** [comment]
Based on the suggestion of temporary solutions here in this thread and a longterm solution proposed in #417, I'm closing this down.
