### ISSUE TITLE
Documentation: '.qs' missing in filtering.rst

### ISSUE THREAD

**Issue by gsvr** [graphql-python/graphene-django#408]
I think this sentence in the docs:
`return super(AnimalFilter, self).filter(owner=self.request.user)`
should contain an additional `.qs`, i.e.:
`return super(AnimalFilter, self).qs.filter(owner=self.request.user)`

File link:
https://github.com/graphql-python/graphene-django/blob/master/docs/filtering.rst

**Comment by phalt** [comment]
Fixed.
