### ISSUE TITLE
Dataloader and N+1 Issue

### ISSUE THREAD

**Issue by nyejon** [graphql-python/graphene-django#409]
I have seen various snippets and various solutions to using a dataloader to limit queries to the db but am struggling to piece together a example that works as I expect. 

Does anyone have a concrete example or project that implements prefetch_related, select_related, dataloaders etc? I would also like to use the FilterSet class in my resolver that implements a dataloader. How can I do this?

This is what I have implemented so far: 

```
class YearDataLoader(DataLoader):
    def batch_load_fn(self, keys):
        return Promise.resolve(YearDataModel.objects.filter(pk__in=keys))

class CompanyNode(DjangoObjectType):

    yeardata = DjangoFilterConnectionField(YearDataNode, filterset_class=YearDataFilter)

    class Meta:
        model = CompanyModel
        interfaces = (relay.Node, )

    def resolve_yeardata(self, info, *args, **kwargs):
        return year_data_loader.load_many(YearDataModel.objects.filter(company=self).values_list('id', flat=True))
```

If I can figure this out then I would gladly write an optimisation guide, as I feel like this is not covered at all in the current docs. All the pieces are there but someone needs to put them all together...

**Comment by vinayan3** [comment]
Note if you do this, like I have it ignores the `filterclass` set on the YearDataNode which the `DjangoFilterConnectField` handles.

**Comment by filipeximenes** [comment]
Here is how I got it working:

```
def get_sorter(ids):
    def order_by(items):
        items_dict = {i.id: i for i in items}
        return [items_dict[i] for i in ids]
    return order_by

class CompanyNode(DjangoObjectType):

    yeardata = DjangoConnectionField(
        YearDataNode, 
        filter1=graphene.String(),
        filter2=graphene.DateTime(),
    )

    class Meta:
        model = CompanyModel
        interfaces = (relay.Node, )

    def resolve_yeardata(self, info, *args, **kwargs):
        ids = YearDataFilter(
            kwargs, YearDataModel.objects.all()).qs.values_list('id', flat=True)
        return (year_data_loader
                .load_many(ids)
                .then(get_sorter(id)))
```
Not perfect nor the most optimized, but should be enough for a temporary solution

**Comment by filipeximenes** [comment]
A little note that I started seeing errors with this solution when querying a smaller subset of a previously resolved promise. It might be that I'm not handling it correctly (maybe someone with more experience on this can review my code) but clearing the data loader on every new request solves the problem: `year_data_loader.clear_all()`
