### ISSUE TITLE
Pypi still showing 2.0.0

### ISSUE THREAD

**Issue by imsickofmaps** [graphql-python/graphene-django#412]
Version was bumped to 2.0.1 in Feb but no release triggered. Can you tag a release so we can the fixes in production pretty please?

**Comment by syrusakbary** [comment]
I just published a new release candidate version: [2.1rc0](https://github.com/graphql-python/graphene-django/releases/tag/v2.1rc0)
If you can test it and let me know if you have any issue so we are able to fix it before the stable version `2.1` would be great.
Thanks!
