### ISSUE TITLE
Is Apollo supported?

### ISSUE THREAD

**Issue by rhymes** [graphql-python/graphene-django#414]
The documentation talks about the integration with Relay <http://docs.graphene-python.org/projects/django/en/latest/tutorial-relay/> but since Relay is React only I was wondering if Apollo is "officially" or unofficially supported as well.

**Comment by patrick91** [comment]
I've been using graphene with apollo without any issue :) AFAIK apollo doesn't specify anything special (ie, nothing like edges, nodes or clientMutationID)

**Comment by relwell** [comment]
Seems to work fine with most use cases, but [uploading via Apollo Client doesn't seem to be presently supported](https://github.com/graphql-python/graphene-django/issues/417).

**Comment by Eraldo** [comment]
I am facing the same challenge. Also using Apollo client's uploader.

**Comment by mvanlonden** [comment]
Apollo is supported. Tracking uploading issue in https://github.com/graphql-python/graphene-django/issues/417

**Comment by squarewave24** [comment]
> I've been using graphene with apollo without any issue :) AFAIK apollo doesn't specify anything special (ie, nothing like edges, nodes or clientMutationID)

code samples or it didn't happen 🔢 :]

**Comment by zero-shubham** [comment]
I found this article, this tutorial shows how django, graphene and apollo can be used together.  https://medium.com/davao-js/nuxt-apollo-graphql-django-c56d6911f4c4
