### ISSUE TITLE
why  cookbook.ingredients.schema everywhere instead of ingredients.schema?

### ISSUE THREAD

**Issue by audacioustux** [graphql-python/graphene-django#415]
maybe I'm missing something... but I'm following the docs exactly... ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌already sent a pull request... but now, as I continue, paths used like this everywhere... cookbook and ingredients are different apps right? why this nesting like path? i'm not sure if it's a mistake and needs to be fixed or i'm doing it wrong :stuck_out_tongue:

**Comment by saschalalala** [comment]
As far as I understood it, cookbook is the project with ingredients in it.
