### ISSUE TITLE
Documentation and actual code divergence

### ISSUE THREAD

**Issue by artemnesterenko** [graphql-python/graphene-django#419]
In the documentation on the following [page](http://docs.graphene-python.org/projects/django/en/latest/rest-framework/#create-update-operations), it is said that I can customize the `model_operations` attribute to allow or deny create and update operations. But when I try to use it, I get `TypeError: __init_subclass_with_meta__() got an unexpected keyword argument 'model_operations'`. There is no a single mention of `model_operations` in the source code of the graphene-django>=2.0.dev version but in the Github repository, it is. Did you forget to deploy changes?

**Comment by TheSaltman** [comment]
Noticing this too.

**Comment by annshress** [comment]
The documentation reflects the development version in the `master` branch, which is not released in PyPi yet. But the fact, that documentation does not reflect the current release version `2.0.0` is inexperienced.

**Comment by chason** [comment]
So how do we use Serializers? Its unclear from looking at the code how to restrict operations or change the kwargs passed to the serializer?
