### ISSUE TITLE
Node's in schema are active when not included in Query

### ISSUE THREAD

**Issue by chriscauley** [graphql-python/graphene-django#42]
I don't know if this is a bug or intentional, but I'm assuming it's a bug because it seems like it could open up vulnerabilities.

https://github.com/chriscauley/graphene-demo

The above repo is me working through the "filtering" and "authentication" sections of the docs. If you pull that (currently at commit 42146fb44ca69b7af6b561c50781aa48e0f7c808), migrate, run `python manage.py loaddata initial.json`, and start the dev server you'll have a set of initial data including a super user with username "admin" and password "password" (no quotes). Then go to /graphql in a browser and enter in the following query:

```
query {
  allAnimals {
    edges{
      node {
        name,
        id,
        user {
          id,
          username,
          password,
          lastName,
          lastLogin
        }
      }
    }
  }
}
```

The result should be the error message in this screenshot: an error message because there is no node to query users.

![screenshot 2016-11-03 at 17 10 26](https://cloud.githubusercontent.com/assets/379151/19985316/77dfeca8-a1e8-11e6-9115-2d2e85ceb0bf.png)

Next, go to graphene_demo/schema.py and uncomment the `CurrentUserNode` class. Re-run the query and you get the following screenshot, which has returned the queried user data.

![screenshot 2016-11-03 at 17 12 28](https://cloud.githubusercontent.com/assets/379151/19985372/cbc5bc80-a1e8-11e6-9f97-8b74bfe37cb4.png)

Even though I didn't change the query it still is exposing the User table. That seems like a bug to me because (I would assume) exposing a table should be explicit.

**Comment by syrusakbary** [comment]
Hi @chriscauley,

The user model should not be exposed if is not done directly.
I've executed the following and can't reproduce the issue:

```bash
git clone git@github.com:chriscauley/graphene-demo.git
cd graphene-demo
python manage.py migrate
python manage.py loaddata initial.json
python manage.py runserver
```

Could you check again that this is not working as expected?

**Comment by syrusakbary** [comment]
@chriscauley let me know if this is still an issue, so we can focus on fixing it :)
