### ISSUE TITLE
Unable to subclass or emulate DjangoObjectType

### ISSUE THREAD

**Issue by techdragon** [graphql-python/graphene-django#423]
Subclassing DjangoObjectType so as to customise it for use in derived objects in the schema causes the execution of:
```python
assert is_valid_django_model(model)
```
which fails the assertion due to`class MyNewClass(DjangoObjectType):` not having a meta class, as it meant to be a subclass of `DjangoObjectType` for reuse later on, not and thus does not have a Meta class of its own.

Its also not possible to emulate DjangoObjectType by copying DjangoObjectType, subclassing the new class from ObjectType, this gets past `assert is_valid_django_model(model)` but then things run into trouble in `graphene_django.registry.Registry` which runs:
```python
assert issubclass(cls, DjangoObjectType), 'Only DjangoObjectTypes can be registered, received "{}"'.format(cls.__name__)
```
Which fails due to the explicit check for `DjangoObjectType`.

It shouldn't require a fork of the entirety of `graphene-django` just to create a subclass of `DjangoObjectType`, either the Registry should be more flexible, or `DjangoObjectType` should be more flexible. 

One option might be to use of Abstract Base Classes to enable a specific set of checks via https://docs.python.org/3/reference/datamodel.html?highlight=__subclass#class.__subclasscheck__

Another way would be to just drop these assertions and throw appropriate exceptions when we reach the situations they were designed to guard against. If we check that its a Django model to ensure that Meta exists, why not just throw a "Not A Django Model" exception when we try to do something later on that actually needs the Django model Meta information instead of asserting something way up the call stack that gets in the way of other things.

**Comment by roddds** [comment]
I just hit a similar issue. That check in DjangoObjectType essentially forbids subclasses, and I was depending on that to implement authorization. I'm open to suggestions on how to implement filtering per user in a straightforward way.

**Comment by techdragon** [comment]
@roddds At the moment, I've been forced to fork the entire graphene-django package to build on the features that I needed. I've built a solution for https://github.com/graphql-python/graphene/issues/572 which wasn't too hard once I worked out how everything was put together under the hood by django-parler and a little bit about how graphene-django inspects the model, but after working this out, I ran face first into this unable to extend/emulate issue. 

Unfortunately, I haven't had the time to spend fully investigating how graphene and graphene-django work so that I can propose concrete changes to the code to resolve this. So for now I've stuck with the less than ideal, fork + branch with changes approach.

**Comment by taut-and-yare** [comment]
@techdragon Hi, could you please point out how you dealt with the specific django-parler issue (or share your fork). Thanks!

**Comment by danpalmer** [comment]
Ping on this, I've just hit this as a bit of a showstopper bug in our GraphQL implementation.

**Comment by borsden** [comment]
Is there any progress?

**Comment by miguel550** [comment]
Any progress?

**Comment by nwaxiomatic** [comment]
Also just ran into this issue trying to create an AutocompleteType that only allows two fields ("id" and "display"). Basically had to create a mixin I include with every Type that is supposed to be for the autocomplete query. Hopefully this gives another use case for this being useful.

**Comment by cobalamin** [comment]
Pretty ugly hack, but: personally I ~fixed~ worked around this by (in the subclass that's supposed to be a parent) referencing `django.contrib.auth.models.User` with a local registry that's never used again:

```python
from graphene_django.registry import Registry
from django.contrib.auth.models import User

class MyDOTSubclass(DjangoObjectType):
    class Meta:
        model = User
        registry = Registry()

    additional_magic = ...

class SomeModelObjectType(MyDOTSubclass):
    class Meta:
        model = SomeModel
```

Why this works:
- `User` is always a valid Django model
- the metaclass being overridden makes `SomeModelObjectType` use the global registry again
- having a throwaway registry doesn't mess with ever possibly having registered another object type for the `User` model, or an object type with just the identical name "User"

Obviously this isn't nice in a number of ways, but if it's a showstopper for you otherwise :)

**Comment by danpalmer** [comment]
@cobalamin thanks for this! I've just applied this technique on our codebase it it worked perfectly. Our previous hack was to use a dynamic base class which mypy then couldn't inspect, so we've now got more idiomatic Python, simpler code, better linting and better typechecking!

**Comment by defiler** [comment]
But who stops you from using

```python
class Meta:
    abstract = True
```

in a subclass ?

**Comment by techdragon** [comment]
I think this should probably stay open since it represents a rather significant limitation that deserves some kind of solution.

**Comment by techdragon** [comment]
This should probably be reopened unless it's been fixed.

**Comment by nmanumr** [comment]
As mentioned by @techdragon this thing works for me:

```python
class DjangoDynamicLoaderObjectType(DjangoObjectType):
    # ...
    class Meta:
        abstract = True
    
    #...
```
