### ISSUE TITLE
Cannot return null for non-nullable field FooType.barType [Enum]

### ISSUE THREAD

**Issue by globophobe** [graphql-python/graphene-django#424]
The error occurs with graphene-django==2.0.0 with a field with choices, for example:
```
class Foo(models.Model):
    ONE = 1
    TWO = 2
  
    BAR_TYPES = (
        (ONE, _('one'),
        (TWO, _('two'),
    )

    bar_type = models.PositiveIntegerField(_('type'), choices=BAR_TYPES)


class FooType(DjangoObjectType):                                    
    class Meta:
        model = Foo
```
This error can be resolved with an explicit graphene.Field declaration: 
```
class FooEnum(graphene.Enum):
    ONE = 1
    TWO = 2                       


class FooType(DjangoObjectType):                                    
    bar_type = graphene.Field(FooEnum)
    class Meta:
        model = Foo
```
Is it really necessary to duplicate the choices, though?

**Comment by DanWilkerson** [comment]
What is the return value for bar_type with version 2 and what is your expected return value? I thought I was having the same issue and then realized I was providing the human-readable value instead of the expected value; using the docs example:

```python
class Student(models.Model):
    YEAR_IN_SCHOOL_CHOICES = (
        ('FR', 'Freshman'),
        ('SO', 'Sophomore'),
        ('JR', 'Junior'),
        ('SR', 'Senior'),
    )
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )

# in schema.py
class StudentGQL(DjangoObjectType):
    class Meta:
        model = models.Student
        interfaces = (relay.Node,)

class AddStudent(relay.ClientIDMutation):
    class Input:
        year_in_school = graphene.Field(required=True)

    student = graphene.Field(StudentGQL)
    
    @classmethod
    def mutate_and_get_payload(cls, input, context, info):
        year_in_school = input.get('year_in_school')
        student = models.Student.objects.create(year_in_school=year_in_school)
        return AddStudent(student=student)
```

and my payload:

```graphql
mutation {
  addStudent(input: { 
    year_in_school: 'Freshman'   // <-- Wrong!
    year_in_school: 'FR'  // Correct!
  }) {
    student {
      year_in_school
    }
  }
}
```
Hope this helps.

**Comment by DanWilkerson** [comment]
It does feel like the query should know to use the human-readable name instead of the value, though.

**Comment by globophobe** [comment]
I was just doing a query, not a mutation. I'm also not using relay. Not sure if that means anything, though.

**Comment by prokher** [comment]
I had the same issue until I applied the following:

```python

import django.db.models as dj_models
from enum import Enum

class MyEnum(Enum):
    VAL1 = 'Value 1'
    VAL2 = 'Value 2'
    VAL3 = 'Value 3'

class MyModel(dj_models.Model):
    state = dj_models.CharField(choices=[(tag.name, tag.value) for tag in MyEnum],
                                max_length=64)
```

this fixed an issues for me.

I've got the recipe from here: http://anthonyfox.io/2017/02/choices-for-choices-in-django-charfields/

Also there are useful comments under this article: https://hackernoon.com/using-enum-as-model-field-choice-in-django-92d8b97aaa63

**Comment by Keats** [comment]
@prokher this doesn't solve the issue in my case.

I have this request: 

```graphql
query {
  allUsers {
    id
    name
    email
    
    orgMembers {
      id
      email
      role
    }
  }
}
```
where some users don't have org memberships and I get `graphql.error.base.GraphQLError: Cannot return null for non-nullable field OrganizationMemberType.role` which is defined:

```python
class Roles(Enum):
    MEMBER = "member"
    MANAGER = "manager"
    ADMIN = "admin"
    OWNER = "owner"
```
I can fix it by adding `role = graphene.Field(graphene.Enum.from_enum(Roles))` to the org member `DjangoObjectType`  but ideally it should work automatically: why is it return a null value for a specific field when the queryset is empty?
