### ISSUE TITLE
cookbook example queries fail

### ISSUE THREAD

**Issue by brianmay** [graphql-python/graphene-django#428]
I setup the example as per:

https://github.com/graphql-python/graphene-django/tree/master/examples/cookbook

I tried to run the first example query:

```graphql
query {
  allIngredients {
    id
    name
  }
}
```

I get the following response:

```
{
  "errors": [
    {
      "message": "Cannot query field \"id\" on type \"IngredientNodeConnection\".",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    },
    {
      "message": "Cannot query field \"name\" on type \"IngredientNodeConnection\".",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    }
```

**Comment by chason** [comment]
It looks like you are running the example from: http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#testing-our-graphql-schema

But that github repository is from the example using Relay, so your query should be:
```
query {
  allIngredients {
    edges {
      node {
        id,
        name
      }
    }
  }
}
```
as seen here: http://docs.graphene-python.org/projects/django/en/latest/tutorial-relay/#testing-our-graphql-schema

**Comment by brianmay** [comment]
Thanks. I hadn't noticed that this example used relay. Closing.

**Comment by alecz20** [comment]
FWIW, the repository: https://github.com/graphql-python/graphene-django/tree/master/examples/cookbook
refers to examples at:
http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#testing-our-graphql-schema
not:
http://docs.graphene-python.org/projects/django/en/latest/tutorial-relay/#testing-our-graphql-schema

This surely causes confusion.
I also don't see where in this that example is relay mentioned.
