### ISSUE TITLE
Annotated field not resolving into type field

### ISSUE THREAD

**Issue by s1104373** [graphql-python/graphene-django#434]
Hi,

I have a query class with a custom resolver it returns:
`Foo.object.all().extra(select={"date": "strftime('%%Y-%%m-%%d %%H:%%M',datetime)"}).values('date', 'name').annotate(avg_value=Avg('value', output_field=FloatField())).order_by('date')`

In my type I added the following field:
`avg_value = graphene.Float(description='The avg value connected to that Foo')`

When I log at the end of the resolver it has an average. When i recieve the data in my frontend it is gone. Maybe I'am doing something wrong but there are no examples to be found about annotated fields.

The extra date field does work btw.

**Comment by bendog** [comment]
did this ever get resolved?
