### ISSUE TITLE
Best practice for DjangoDebug

### ISSUE THREAD

**Issue by Fohlen** [graphql-python/graphene-django#440]
Hello there. I was wondering how would I write a `Query` containing `DjangoDebug` that will be conditionally enabled or disabled depending on the `settings.DEBUG` flag.
Currently I do it like this:

```
if not settings.DEBUG:
    DjangoDebug = object # monkey patch DjangoDebug handler if DEBUG is not enabled. Why don't you do this by default graphene?
```
because monkey patching does save you from using mixins or abstract base classes. What is considered the best practice here?

**Comment by saschalalala** [comment]
I do it like this in my project's schema.py:


```python
class Query(BundledQuery, graphene.ObjectType):
    if settings.DEBUG:
        debug = graphene.Field(DjangoDebug, name='__debug')
```

**Comment by Fohlen** [comment]
Seems reasonable and works for me. Closing it! ❤️
