### ISSUE TITLE
Neomodel's models are not recognized

### ISSUE THREAD

**Issue by avadhanij** [graphql-python/graphene-django#442]
Not sure whose issue this is, but I just wanted to put it out here because the integration isn't working. [Neomodel](https://github.com/neo4j-contrib/neomodel) is the OGM driver for the Neo4j database, and its _node structure types_ are not being recognized as models. Basically - 

lib/python3.6/site-packages/graphene_django/types.py", line 51, in __init_subclass_with_meta__
    ).format(cls.__name__, model)
AssertionError: You need to pass a valid Django Model

This happens when I try to pass a neomodel _node_ as 

```
Class Meta:
    model  = myneomodel
```

Any thoughts?

**Comment by jkimbo** [comment]
@avadhanij graphene-django checks for Django models using the following code:

https://github.com/graphql-python/graphene-django/blob/a480a39713d3392dc3a7cee9565989a713d05856/graphene_django/utils.py#L59

**Comment by avadhanij** [comment]
Thanks, yeah, I came to the same conclusion. I filed a similar issue in that repo, and I am waiting for their response.

**Comment by reverland** [comment]
I came across the same Exception when I try to inherit from a DjangoObjectType class, and not provide Meta class.

```
class A(DjangoObjectType):
    class Meta:
        model = model_a

class B(A):
    pass
```

this way, B will not work, and need a Meta class.

I may check this later if I have time on this.

**Comment by HashRocketSyntax** [comment]
Has anyone solved this graphene-neomodel compatibility? I'm refactoring from scratch and would not like to implement REST.

**Comment by ProjectCheshire** [comment]
I use graphene neomodel in an aiohttp app perfectly fine and have been for the past year+ in production , I believe neomodel does hsve a neomodel django variant https://github.com/neo4j-contrib/django-neomodel
