### ISSUE TITLE
Rest framework mutation (get_serializer_kwargs)

### ISSUE THREAD

**Issue by marcelombc** [graphql-python/graphene-django#444]
Hi, is there any plans to release a new version with the `get_serializer_kwargs` method on the `SerializerMutation` class? Version `2.0.0` does not reflect the [documentation](http://docs.graphene-python.org/projects/django/en/latest/rest-framework/#overriding-update-queries)

**Comment by chason** [comment]
I agree, though I was able to fix it by installing from github, I'd rather use the pypi package.

**Comment by phalt** [comment]
Hey @marcelombc - can you give an example of what isn't working? We can update the docs to reflect the correct changes.

**Comment by dopeboy** [comment]
Closing this down due to inactivity.
