### ISSUE TITLE
Force models to be clean before being saved

### ISSUE THREAD

**Issue by saschalalala** [graphql-python/graphene-django#447]
I am not sure if this is a good idea in general, but for me it looks like graphene-django should validate the input before creating database queries. An easy solution is adding something like:

```python
class ModelName(Whatever, models.Model):
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
```

 to your models but for me it seems like something the library should take care of.

This ticket is more of a reminder, I'll look closer into it the next days as I am not even sure if something like that is doable on that level.

If not, it should go into the docs, though.

**Comment by patrick91** [comment]
@saschalalala can you also show the mutation that you have?

**Comment by saschalalala** [comment]
@patrick91 Yes, I created a gist that shows my model and the mutation ([direct link](https://gist.github.com/saschalalala/97e1f2a146854a31a45dde139a4d4026#file-user_management-schema-py-L40)). I basically implemented it the same way it is done in the howtographl tutorials. Find the links below.

[Link to the tutorial](https://www.howtographql.com/graphql-python/4-authentication/)
[Link to the gist](https://gist.github.com/saschalalala/97e1f2a146854a31a45dde139a4d4026 )

**Comment by saschalalala** [comment]
Well, perhaps it is a good idea to just call `object.full_clean()` inside the mutation …

**Comment by Fohlen** [comment]
I am currently using `escape` manually to get this done. Big + if it would be done by graphene automatically!

**Comment by saschalalala** [comment]
@Fohlen What exactly do you mean with "using `escape`"?

**Comment by Fohlen** [comment]
```
from django.utils.html import escape

self.field = escape(self.field)
```

More practically, loop over all `self.items()` to do this.

**Comment by patrick91** [comment]
@saschalalala ok, not it is a bit more clear, I think this is not in the scope of graphene per-se, this is how django works when you call the save method. Graphene isn't doing anything Django related here. I think when we will have full form support you wouldn't need to worry about this detail since it will come with the form validation.

**Comment by zbyte64** [comment]
I think there is a valuable discussion over at stackoverflow on why DRF does not call `full_clean`: https://stackoverflow.com/questions/32834026/why-does-django-rest-framework-discourage-model-level-validation

**Comment by dopeboy** [comment]
Going to defer to @patrick91's judgement here - closing this one down.
