### ISSUE TITLE
Async schema does not return observable

### ISSUE THREAD

**Issue by japrogramer** [graphql-python/graphene-django#452]
Here i am trying to run an async schema
```
            # stream is an rx.Subject
            result = graphql(schema,
                    payload['query'],
                    variable_values=payload['variables'],
                    root_value=stream.share(),
                    allow_subscriptions=True,
                    executor=AsyncioExecutor(loop=asyncio.get_event_loop()),
                    **{'context_value': message})
```

Here is the schema

```
class ProductSubscritption(object):

    """test"""
    sub_product = graphene.Field(
        ProductType,
        description='subscribe to updated product',
        product=graphene.ID())

    async def resolve_sub_product(self, info, **input):
        def next(message, info, **input):
            # here the message comes from the stream but the info and **input come frome
            # subscribing to the next method to the stream
            __import__('pdb').set_trace()
            inst = relay.Node.get_node_from_global_id(info, input.get('product'))
            return inst

        await make_sub(info, input.get('product'))
        name = ProductType._meta.model.__class__.__name__

        stream = info.root_value
        obv = stream.map(lambda message: next(message, info, **input))
        register = info.context['register']
        if register:
            __import__('pdb').set_trace()
            register(obv)
        return obv

```

And here is the value of result

```
(Pdb) result
<graphql.execution.base.ExecutionResult object at 0x7f1f08114168>
(Pdb) result.errors
[RuntimeError('This event loop is already running',)]
(Pdb) result.data
(Pdb)
```

I know that despite the error in result the schema continues in the background because of the brake points I have set.

**Comment by colanconnon** [comment]
Are you using the django channels backend for subscriptions? If so what version of django channel sare you using?

**Comment by japrogramer** [comment]
yes I am, 
channels==2.1.1
channels-redis==2.2.1


Django==2.1a1
django-allauth==0.32.0
django-appconf==1.0.2
django-braces==1.11.0
django-channels-panel==0.0.5
django-coverage-plugin==1.5.0
django-crispy-forms==1.7.2
django-debug-toolbar==1.8
django-extensions==1.7.9
django-model-utils==3.0.0
django-redis==4.9.0
django-test-plus==1.0.22
graphene-django==2.1rc1
pytest-django==3.1.2

**Comment by japrogramer** [comment]
I don't think it's channels related, I believe that the async await section raizes a non fatal error that graphene captures than return that as a result while the query continues to execute in the background

**Comment by japrogramer** [comment]
I managed to hack my way around it .. its not ideal since i don't actually get back the fields I queried .. but at least i get a response back to the browser, which Im planning on pairing with a regular query that actually gets the fields I want ..

**Comment by japrogramer** [comment]
@syrusakbary any ideas?

**Comment by dopeboy** [comment]
@japrogramer, I'm going to close this down since you found a solution. I'd also turn you to #120.
