### ISSUE TITLE
example's settings.py redfines GRAPHENE

### ISSUE THREAD

**Issue by ericfrederich** [graphql-python/graphene-django#455]
Both of these files define GRAPHENE twice.

* [examples/cookbook-plain/cookbook/settings.py](https://github.com/graphql-python/graphene-django/blob/175594876828f647ba6aa83538486f1838b2ff45/examples/cookbook-plain/cookbook/settings.py)
* [examples/cookbook/cookbook/settings.py](https://github.com/graphql-python/graphene-django/blob/175594876828f647ba6aa83538486f1838b2ff45/examples/cookbook/cookbook/settings.py)

Once as:
```python
GRAPHENE = {
    'SCHEMA': 'cookbook.schema.schema',
    'MIDDLEWARE': (
        'graphene_django.debug.DjangoDebugMiddleware',
    )
}
```

The second time as:
```python
GRAPHENE = {
    'SCHEMA': 'cookbook.schema.schema',
    'SCHEMA_INDENT': 2,
}
```

Please clean up.  I'd submit a pull request but I'm just learning graphene myself (hence why I'm looking at examples) and don't understand these implications.

**Comment by dopeboy** [comment]
Agreed, this is a little sloppy. We're doing a docs refresh and this will be get looked at again. Keeping it open for now so we don't forget.

**Comment by changeling** [comment]
I believe this can be closed now, due to the above PR being merged.
