### ISSUE TITLE
SerializerMutation nested serializer with many=True

### ISSUE THREAD

**Issue by sks-keo** [graphql-python/graphene-django#458]
I have a DRF Serializer with a field using a custom nested serializer, something like this:

class FirstSerializer(serializers.ModelSerializer):
    class Meta:
        model = FirstModel
        fields = "__all__"

class SecondSerializer(serializers.ModelSerializer):
    class Meta:
        model = SecondModel
        fields = ('field_a', 'field_b')
    field_b = FirstSerializer(many=True)

I'm trying to create a mutation on the FirstSerializer like this:

class MyMutation(SerializerMutation):
    class Meta:
        serializer_class = SecondSerializer

djangorestframework==3.8.2

graphene&gt;=2.1.2
graphene-django==2.1rc1
graphql-core&gt;=2.1rc1

![screen shot 2018-06-21 at 10 36 15 am](https://user-images.githubusercontent.com/5140078/41696611-1a62e270-753f-11e8-8204-b23179bc24a5.png)

**Comment by trixn86** [comment]
I observed the same problem when trying to use nested Serializers in a `SerializerMutation`.

djangorestframework==3.8.2
graphene==2.1.3
graphene-django==2.1.0
graphql-core>=2.1

**Comment by trixn86** [comment]
After debugging for a while I found that reason was there was no type defined for the model of the serializers. 

The `SerializerMutation` tries to define an output type from the model of a serializer. If no `DjangoObjectType` exists for that model it will silently return `None` as the type. This will later lead to an error.

Actually I would like to see a `SerializerMutation` that does not require model types to be defined. I don't overall like very much, that the whole library is very tightly coupled with the django ORM. There is also a need for not exposing every model field to the outside world.

**Comment by p02diada** [comment]
I have the same problem but without using many=true. How did you solve your problem? I have defined an DjangoObjectType for my model but it does not work yet.

**Comment by zbyte64** [comment]
Trying to construct a unit test to reproduce this, here is what I got:

```
def test_construct_mutate_nested_model():
    class ChildSerializer(serializers.ModelSerializer):
        class Meta:
            model = MyFakeModel
            fields = "__all__"

    class ParentSerializer(serializers.ModelSerializer):
        child = ChildSerializer(many=True)

        class Meta:
            model = MyFakeModel
            fields = "__all__"

    class MyMutation(SerializerMutation):
        class Meta:
            serializer_class = ParentSerializer
```

This seems to work fine though.

**Comment by dopeboy** [comment]
@sks-keo, did you reach a solution?

**Comment by coler-j** [comment]
@dopeboy can you please re-open this? I am currently encountering a variation of it. The error I am getting is:

```
File "/...../graphql/execution/executor.py", line 590, in complete_list_value
    assert isinstance(result, Iterable), (
AssertionError: User Error: expected iterable, but did not find one for field MyFieldMutationPayload.mappings.
```
