### ISSUE TITLE
Using a specified database

### ISSUE THREAD

**Issue by danpalmer** [graphql-python/graphene-django#461]
Django provides the ability to query a particular database. For example, these are equivalent:

```python
User.objects.all()
User.objects.using('default')
```

For performance/scalability, we direct our reads to a secondary database. In this case we do `User.objects.using('secondary')` to read.

We'd like to be able to specify a default database to be used for queries.

Second to this, we'd also like to preserve the ["read your writes"](https://en.wikipedia.org/wiki/Consistency_model#Read-your-writes_Consistency) property as much as we can by, in mutations, writing to and then reading from the primary/default database.

Essentially, something like this would be ideal:

```python
schema = graphene.Schema(
    query=Query,
    query_database='secondary',
    mutation_database='primary',
)
```

I'm not sure where is best to put this API, or whether it already exists (I can't find it in the docs or source), but the above would satisfy the requirements. There could well be a nicer place to specify this.

Ideally whatever the option is, it would allow for setting a global default per operation type, along with overrides per type, rather than needing to be explicitly specified per type.

Thoughts?

**Comment by syrusakbary** [comment]
I think this makes sense, but probably living on the graphene-django configuration and Graphene mappings rather than the schema itself.

Probably something like this:

In settings.py
```python
GRAPHENE = {
    # ...
    "DEFAULT_QUERY_DATABASE": "secondary",
    "DEFAULT_MUTATION_DATABASE": "primary",
}
```

And then, when using `DjangoObjectType` (if we want to customize without touching the settings file)

```python
class MyType(DjangoObjectType):
    class Meta:
        db_using = "secondary-other" # Will be settings.GRAPHENE['DEFAULT_QUERY_DATABASE'] otherwise by default

class MyMutation(DjangoModelFormMutation):
    class Meta:
        db_using = "primary-other" # Will be settings.GRAPHENE['DEFAULT_MUTATION_DATABASE'] otherwise by default
```

Thoughts @danpalmer?

**Comment by danpalmer** [comment]
This looks good. One thing I'd be unsure about though is: when I have a mutation that returns a `DjangoObjectType`, is it the mutation database or the object type's database that gets used?

I think it's most useful for the _mutation's_ database to be used, because I would expect that one execution would happen against 1 database by default, because otherwise there are many race conditions and consistency issues that would come up under regular use. However, it is unexpected that an object type with `db_using = 'foo'` would under some circumstances not use that.

I'm not sure how to solve this. Documentation is one way, but if we can come up with code that makes it obvious, I think that would be a better API.

**Comment by phalt** [comment]
Could we use the `get_queryset` method that has now been added to DjangoObjectTypes?
