### ISSUE TITLE
Graphene Django is incompatible with django-filters 2.0.0

### ISSUE THREAD

**Issue by synasius** [graphql-python/graphene-django#464]
When using graphene-django along with `django-filter` 2.0.0 I get an error trying to use the graphql endpoint.

A brief example:

```
class Query(object):
    projects = DjangoFilterConnectionField(
        MyProjectNode, filterset_class=MyProjectFilterSet)
```

This is the error:
```
`GrapheneMyProjectFilterSet.filter_for_reverse_field` has been removed. `GrapheneMyProjectFilterSet.filter_for_field` now generates filters for reverse fields. See: https://django-filter.readthedocs.io/en/master/guide/migration.html
```

**Comment by javiercp** [comment]
I'm hitting this too after installing latest "Django REST framework JWT" in my project.

**Comment by ramonsaraiva** [comment]
Same thing here.

**Comment by magdyksaleh** [comment]
Same thing here!

**Comment by Boyu1997** [comment]
Same thing here.

**Comment by phalt** [comment]
This actually prevents a django 2.1 upgrade, as Django 2.1 requires `django-filters` to be bumped to 2.0:
```
  File "/Users/paul.hallet/Envs/pgm-models/lib/python3.6/site-packages/django_filters/__init__.py", line 7, in <module>
    from .filterset import FilterSet
  File "/Users/paul.hallet/Envs/pgm-models/lib/python3.6/site-packages/django_filters/filterset.py", line 15, in <module>
    from .filters import (
  File "/Users/paul.hallet/Envs/pgm-models/lib/python3.6/site-packages/django_filters/filters.py", line 9, in <module>
    from django.db.models.sql.constants import QUERY_TERMS
ImportError: cannot import name 'QUERY_TERMS'
```
```

**Comment by gvizquel** [comment]
In its portal clarify the compatibility...
http://docs.graphene-python.org/projects/django/en/latest/filtering/

**Comment by sanketsaurav** [comment]
I've run into the same issue: I want to use `graphene-django` with filtering capabilities in `django==2.1.1` (the latest as of today).

Could someone please let me know if this is an immediate concern in the pipeline? If not, I would be happy to take this up and pitch in!
