### ISSUE TITLE
It does not support Django Rest Framework token authentication backend

### ISSUE THREAD

**Issue by mohamedrez** [graphql-python/graphene-django#476]
when I try to access  info.context.user it all the time returns anonymous user, my same code works fine with django-graphql-jwt

Debugging gives me this : 
```
-> return self.middleware
(Pdb) self.middleware
[<graphene_django.debug.middleware.DjangoDebugMiddleware object at 0x7fb93ac8d590>]
(Pdb)
```

Means that no auth middleware has been set to the graphql view

**Comment by vinayan3** [comment]
To support DRF Token Authentication Backend I wrote a class which derives from GraphQLVIew.
```
class AuthenticatedGraphQLView(GraphQLView):
  authentication_classes = [GraphQlSessionAuth, BearerTokenAuthentication]
  permission_classes = [IsAuthenticated]

  def authenticate_request(self, request):
    for auth_class in self.authentication_classes:
      auth_tuple = auth_class().authenticate(request)
      if auth_tuple:
        request.user, request.token = auth_tuple
        break

  def check_permissions(self, request):
    for permission_class in self.permission_classes:
      if not permission_class().has_permission(request, self):
        return False
    return True

  @method_decorator(csrf_exempt)
  def dispatch(self, request, *args, **kwargs):
    try:
      self.authenticate_request(request)
      has_permission = self.check_permissions(request)
      if not has_permission:
        return HttpResponse(
            json.dumps({'errors': ['permission denied']}),
            status=status.HTTP_403_FORBIDDEN,
            content_type='application/json')
    except AuthenticationFailed as auth_failed_error:
      return HttpResponse(
          json.dumps({
            'errors': [str(auth_failed_error)]
          }),
          status=status.HTTP_401_UNAUTHORIZED,
          content_type='application/json')
    return super(AuthenticatedGraphQLView, self).dispatch(request, *args, **kwargs)
```

**Comment by mohamedrez** [comment]
Thanks for the code you shared.

In my opinion, we should have a setting like : 
```
GRAPHENE = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'profile.authentications.SomeAuthenticationClass',
    ),
}
```

**Comment by danielmcquillen** [comment]
@vinayan3 Thanks for code. Question: did you ever try adding SessionAuthentication to your `authentication_classes` ?

Doing so is helpful if you want logged in users to be able to access the GraphiQL UI. However, when I tried adjusting the code you posted like so:

`authentication_classes = [TokenAuthentication, SessionAuthentication]`

It fails when DRF tries looking for request._request as part of the sessions auth check.

`'WSGIRequest' object has no attribute '_request'`

Curious if anyone else has attempted to use DRF tokens *and* session authentication such that the GraphiQL UI is available to logged in users.

**Comment by Frank5000** [comment]
bump, I've resorted to a separate view for a DRF REST endpoint and another for graphiql
