### ISSUE TITLE
Have a `Bad request 400` error when `batch=True` in urls.py

### ISSUE THREAD

**Issue by koddr** [graphql-python/graphene-django#480]
Hello.

> Django 2.0.7, Python 3.6.1

I have a `Bad request 400` error when I set `batch=True` in urls.py.

```python
# core/urls.py

from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from graphene_django.views import GraphQLView

urlpatterns = [
    # ...
    path('graphiql/', GraphQLView.as_view(graphiql=True)),
    path('api/', csrf_exempt(GraphQLView.as_view(batch=True))),
]

# core/schema.py

import graphene
from projects.schema import Query as ProjectQuery

class Query(ProjectQuery, graphene.ObjectType):
    pass

schema = graphene.Schema(query=Query)

# projects/schema.py

import graphene
from graphene_django.types import DjangoObjectType
from .models import Project

class ProjectType(DjangoObjectType):
    class Meta:
        model = Project
        interfaces = (graphene.Node,)

class Query(graphene.ObjectType):
    all_projects = graphene.List(ProjectType)

    def resolve_all_projects(self, info, **kwargs):
        return Project.objects.all()
```

If I make requests to `graphiql/` url (Graph*i*QL) everything is okay. But if I make request to `api/` from my frontend (React + Apollo), I see error on Chrome console: 

> POST http://localhost:8000/api/ 400 (Bad Request)

When I delete `batch=True` from `core/urls.py` — it works!

Can somebody help me? Please..

**Comment by jayhale** [comment]
Can you create a repo to replicate the issue?  Thanks!

**Comment by Moataz-E** [comment]
Hi,

I had the exact same issue as OP. I've created a repository to replicate the issue [here](https://github.com/Moataz-E/graphene_django_bug).

You will need to populate your GraphQL database with some Message objects.

**Comment by Moataz-E** [comment]
I've managed to trace the error using the browser console:

`"Batch requests should receive a list, but received {'variables': {}, 'query': '{\\n allMessages {\\n id\\n message\\n __typename\\n }\\n}\\n'}." }`

The fix should be obvious after reading the above error. For future reference in case someone else stumbles into this same issue.
