### ISSUE TITLE
How to use global_id with django forms integration ? 

### ISSUE THREAD

**Issue by wsantos** [graphql-python/graphene-django#481]
Hi,

I'm using Django forms but it's not accepting global_id, what I am missing?

**Comment by zbyte64** [comment]
I am also experiencing this issue. To clarify I am using `DjangoModelFormMutation` with a form that has a foreignkey. Sending the base64 id causes a "not a valid choice" validation error.

**Comment by wsantos** [comment]
For future reference, I've done this code to convert global_id on mutations, it's not complete and I'll create a PR as soon I cover all scenarios and finish my project.

```python
class DjangoModelFormRelayMutation(DjangoModelFormMutation):
    class Meta:
        abstract = True

    @classmethod
    def mutate_and_get_payload(cls, root, info, **input):
        model = cls._meta.form_class._meta.model

        for field, value in input.items():
            if not hasattr(model, field):
                continue

            model_field = model._meta.get_field(field)
            #TODO: Convert to singledispatch
            if isinstance(model_field, (AutoField, ForeignKey)):
                _, input[field] = from_global_id(value)

    return super().mutate_and_get_payload(root, info, **input)
```

Hope it helps you @zbyte64 in the mean time.

**Comment by amzhang** [comment]
@wsantos Good stuff. Also, nice work with the option to exclude id for mutation operations!
