### ISSUE TITLE
Django 2.1 BooleanField(null=True) syntax not supported by DjangoObjectType

### ISSUE THREAD

**Issue by picturedots** [graphql-python/graphene-django#486]
[As of Django 2.1,](https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.BooleanField) the syntax `BooleanField(null=True)` is now supported by Django (in addition to the syntax NullBooleanField() but the `null=True` is ignored by `DjangoObjectType`.

This only a problem with Django 2.1.

The bug can be reproduced like

    import graphene
    from graphene_django import DjangoObjectType
    from django.db import models
    
    class Car(models.Model):
        class Meta:
            app_label = 'app'
        is_fast = models.BooleanField(null=True)
    
    class CarNode(DjangoObjectType, model=Car):
        pass
    
    class Query(graphene.ObjectType):
        car = graphene.Field(CarNode)
    
        def resolve_car(self, info):
            return Car(is_fast=None)
        
    schema = graphene.Schema(query=Query)
    result = schema.execute('{ car { isFast } }')
    
    print(result.data, result.errors)

**Comment by jckw** [comment]
A workaround for the moment is to use a `NullBooleanField` instead.

**Comment by jakubste** [comment]
I believe that's still an issue.
