### ISSUE TITLE
Requiring filter parameters on all connections

### ISSUE THREAD

**Issue by SaltyQuetzals** [graphql-python/graphene-django#497]
I'm hoping to achieve something similar to how [GitHub requires you to paginate](https://developer.github.com/v4/explorer/) connections in their GraphQL API, in a clean way.

In other words, requiring queries to supply a `first` or `last` parameter to paginate data.

How could I go about doing this?

**Comment by jayhale** [comment]
Can you create a repo replicating the issue? What trouble are you having implementing?

`first`, `last`, `before`, and `after` work out of the box: 

E.g., with schema definition:
```python
from graphene import relay, ObjectType, Schema
from graphene_django import DjangoConnectionField, DjangoObjectType
from .models import Turtle

class TurtleNode(DjangoObjectType):
   class Meta:
      name = 'Turtle'
      model = Turtle
      interfaces = (relay.Node,)

class Query(ObjectType):
   turtles = DjangoConnectionField(TurtleNode)

schema = Schema(query=Query)
```

You can execute queries like:
```graphql
{
   turtles (first: 5, after: "VGVhbToy") {
      id
   }
}
```

**Comment by SaltyQuetzals** [comment]
I don't believe that there's a way to enforce custom arguments when using connections like `RELAY_ENFORCE_FIRST_LAST`, is there?

**Comment by dopeboy** [comment]
Did you reach a resolution here @SaltyQuetzals?

**Comment by changeling** [comment]
@SaltyQuetzals, can you provide an example of showing roughly what you wish to do?

Does this help?:
https://github.com/graphql-python/graphene/wiki/FAQ
