### ISSUE TITLE
graphiql default query doesn't show up

### ISSUE THREAD

**Issue by benblippar** [graphql-python/graphene-django#5]
Note how the setting for default query doesn't show after the 1.0 upgrade. http://swapi.graphene-python.org/graphql

**Comment by syrusakbary** [comment]
Hi @benblippar,

When you plug in the GraphQLView do it with `graphiql=True`.
```python
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
]
```

Docs: http://docs.graphene-python.org/projects/django/en/latest/tutorial.html#creating-graphql-and-graphiql-views
