### ISSUE TITLE
DjangoDebugMiddleware prevents exceptions from being logged

### ISSUE THREAD

**Issue by toolness** [graphql-python/graphene-django#504]
Hmm, I'm not sure what's going on, but I spent a very long time trying to figure out why exceptions in my GraphQL endpoint weren't making their way to my logging subsystem.

Note that by default, Graphene/graphql-core logs exceptions that occur to the logging subsystem:

```python
import graphene


class MyThing(graphene.ObjectType):
    foo = graphene.String()
    bar = graphene.String()

    def resolve_foo(self, info):
        return "hi"

    def resolve_bar(self, info):
        raise Exception('some weird unexpected error happened!')


schema = graphene.Schema(query=MyThing)

# This prints 'hi'.
print(schema.execute('query { foo }').data['foo'])

# This prints 'None' but first logs a helpful traceback.
print(schema.execute('query { bar }').data['bar'])
```

The second query logs the following:

```pytb
An error occurred while resolving field MyThing.bar
Traceback (most recent call last):
...
graphql.error.located_error.GraphQLLocatedError: some weird unexpected error happened!
```

However, no such logging message occurred when I bound my schema to a Graphene-Django `GraphQLView`, despite configuring my Django log settings properly.

I eventually figured out that if I sent my `settings.GRAPHENE["MIDDLEWARE"]` to `None`, the errors started being logged again.

It seems the default middleware used if I don't force it to `None` is `DjangoDebugMiddleware`, so perhaps this is doing something to prevent the errors from being logged?

**Comment by phalt** [comment]
The small plugin [graphene-django-sentry](https://github.com/phalt/graphene-django-sentry/blob/master/graphene_django_sentry/views.py) has an example where it captures errors before returning, I'd suggest looking at that and adapting it for your needs.
