### ISSUE TITLE
serializer_class is required for the SerializerMutation

### ISSUE THREAD

**Issue by hellpirat** [graphql-python/graphene-django#509]
```
class PriceSerializer(serializers.ModelSerializer):
    class Meta:
        model = Price
        fields = '__all__'

class PriceMutation(SerializerMutation):
    class Meta:
        serializer_class = PriceSerializer

```
django==2.0.8
graphene_django==2.1.0
python 3.7

**Comment by gvbkr** [comment]
@hellpirat  how did you resolve this issue? I am facing the same issue. When I follow the example https://docs.graphene-python.org/projects/django/en/latest/rest-framework/ here I get this error.

File "/root/Envs/venv/lib/python3.6/site-packages/graphene/utils/subclass_with_meta.py", line 52, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/root/Envs/venv/lib/python3.6/site-packages/graphene_django/rest_framework/mutation.py", line 60, in __init_subclass_with_meta__
    raise Exception("serializer_class is required for the SerializerMutation")

**Comment by gotexis** [comment]
+1 facing this issue...
