### ISSUE TITLE
Type errors in DRF serializer mutation

### ISSUE THREAD

**Issue by patrick91** [graphql-python/graphene-django#515]
Right now we return a list of errors like this:

```json
[{
  "field": "x",
  "errors": ["a"]
}]
```

it might be nicer to type them like this:

```json
{
  "errors": {
    "x": ["a"]
  }
}
```

I'll send a PR in the next few weeks :)

See also: #514

**Comment by kalekseev** [comment]
@patrick91  what about error type in your example? I assume it will be GenericScalar?

Right now ErrorType:
```
type ErrorType {
  field: String!
  messages: [String!]!
}
```

To support nested errors we could extend it like this:
```
type ErrorType {
  field: String!
  messages: [String!]
  errors: ErrorType
}
```

**Comment by kalekseev** [comment]
@patrick91 
> I'll rewrite the implementation of the errors for the serializer mutation

I assume you will need to rewrite django forms errors too to make error type consistent across the project.
