### ISSUE TITLE
Improvement: keep only_fields in _meta

### ISSUE THREAD

**Issue by camgunz** [graphql-python/graphene-django#516]
This is a little related to #97.  Because `ObjectType` is "all fields by default", I wanted to setup a mechanism whereby we required `only_fields` on all our `ObjectType` subclasses.  But `only_fields` isn't in the options, thus it isn't preserved in the conversion from `Meta` to `_meta`.  It would be cool if either `ObjectType` default to "no fields by default", or if we could enforce that manually by checking for `only_fields` ourselves.

**Comment by camgunz** [comment]
I should say I'm happy to look into making a PR for this; dunno if I can commit to getting one together but I don't want to demand stuff :)

**Comment by mvanlonden** [comment]
Closing in favor of https://github.com/graphql-python/graphene-django/issues/516

**Comment by reverie** [comment]
@mvanlonden But this is ticket #516. As it stands, there's no way to enforce only_fields in graphene. Defaulting to insecure is one thing; preventing people from even making their app secure is another. A simple solution might be to remove the line `delattr(cls, "Meta")` from `SubclassWithMeta`, but I don't know if that would have other unintended consequences.
