### ISSUE TITLE
Recursive Node Relationships 

### ISSUE THREAD

**Issue by BossGrand** [graphql-python/graphene-django#52]
Is something like this possible

    class UserNode(DjangoObjectType):
    
         friends = graphene.List(UserNode)

         class Meta:
             interfaces = (Node, )
             model = UserModel

if there currently isn't a way to do this, I propose doing something similar to how django models resolve strings to reference models

**Comment by BossGrand** [comment]
This is solved by using a lambda, thanks @syrusakbary for pointing this out!

    class UserNode(DjangoObjectType):
    
        friends = graphene.List(lambda: UserNode)
        class Meta:
             interfaces = (Node, )
             model = UserModel

**Comment by reverie** [comment]
Thanks! Note that the string method works elsewhere in graphene but not here, you have to use lambda.
