### ISSUE TITLE
Duplicate defined ErrorType(s) causes an error

### ISSUE THREAD

**Issue by zbyte64** [graphql-python/graphene-django#520]
When using both form mutations, and DRF mutations there arises an error:
`AssertionError: Found different types with the same name in the schema: ErrorType, ErrorType.`

It seems we have two classes `ErrorType` defined by each integration.

**Comment by charlex** [comment]
I belive this is related to #478

**Comment by zbyte64** [comment]
That depends... Should graphene support duplicate class names? I think not.

What is going on here is that **two** explicitly defined `ErrorType` exist in the code base and if they are both imported then we get the following assertion error.

**Comment by zbyte64** [comment]
If anything I think this is loosely related to #515 which seeks to create a more specific `ErrorType` for DRF; with support for nested errors.

There are two ways to address this problem as I see it:

- Define `ErrorType` as a root type and have both forms and DRF integrations use that single error class
- Define separate `ErrorType`s but with different names

If #515 adopts features that don't make sense in the form based mutations then we should go with the latter option and have `FormErrorType` and `NestedErrorType` or some more appropriate names.

**Comment by charlex** [comment]
Oh I see what you mean. This is specific to ErrorType, #478 is related to Input types.
