### ISSUE TITLE
Numeric in filter on custom filterset_class

### ISSUE THREAD

**Issue by timothyjlaurent** [graphql-python/graphene-django#53]
I am trying to set up a `in` filter for a DjangoFilterConnectionField so that I can make a query looking for any of a list of Ids.

I am following the recommendataion on the django_filter docuemntation : https://django-filter.readthedocs.io/en/latest/ref/filters.html#baseinfilter

here is my factory function for creating these classes:
```
class NumberInFilter(django_filters.filters.BaseInFilter, django_filters.filters.NumberFilter):
    pass

def create_model_id_filter(model):
    model_name = model.__name__
    filter_class = type(
        '{model_name}IdFilter'.format(model_name=model_name),
        (django_filters.FilterSet,),
        dict(
            id__in=NumberInFilter(name='id', lookup_expr='in'),
            Meta=type('Meta', (object,), dict(model=model))
        )
    )
    return filter_class
```

but the type of the query is showing up as a Float type so won't let me pass in strings arguments to the `id__In` filter. 
![image](https://cloud.githubusercontent.com/assets/2000204/20231431/a1d98da0-a816-11e6-958f-f131546f4716.png)

Is there a good way to accomplish this?

**Comment by timothyjlaurent** [comment]
Ok I was able to get this working by changing the `NumberInFilter` to:

```
class NumberInFilter(django_filters.filters.BaseInFilter, django_filters.filters.CharFilter):
    pass
```

This works as expected to get filter on ids.

I guess it should just be called `InFilter`. I'm gonna close this one.

**Comment by Doctor-God** [comment]
I know this is really late. But the above inheritance seems to not work anymore on the more recent versions. What is the correct way to adapt it?
