### ISSUE TITLE
Can't use GlobalIDFilter as FilterSet field

### ISSUE THREAD

**Issue by SN9NV** [graphql-python/graphene-django#542]
I noticed that when I was trying to use a `GlobalIDFilter` as a FilterSet field, it doesn't call the filter method (both my custom method `filter_table_id` and `GlobalIDFilter.filter` is not called) and returns all of the records in the table. If I use a CharFilter instead of a GlobalIDFilter, it works and filters as expected.

This works. But type is `String` in queries.
```python
class ModelFilter(FilterSet):
    def filter_table_id(self, queryset, name, value):
        _, _id = from_global_id(value)
        return queryset.filter(table1__table2__table3__id=_id)

    table_id = CharFilter(method='filter_table_id')

    class Meta:
        model = DBModel
        fields = {
            'name': ['exact', 'icontains'],
            'table_id': ['exact'],
        }
```

But if I replace the `CharFilter` with `GlobalIDFilter`, the type is `ID` in the query, but all the records are returned, none are filtered out.
```python
class ModelFilter(FilterSet):
    def filter_table_id(self, queryset, name, value):
        _, _id = from_global_id(value)
        return queryset.filter(table1__table2__table3__id=_id)

    table_id = GlobalIDFilter(method='filter_table_id')

    class Meta:
        model = DBModel
        fields = {
            'name': ['exact', 'icontains'],
            'table_id': ['exact'],
        }
```

I tried to see why it was not working, but I could not find out why the filter function nor my `filter_table_id` was being called.
Am I using the wrong thing for filtering?
Is there a better way to do what I want?

I am using venv with:
 * Python 3.7.0 (default, Sep 12 2018, 18:30:08), the default Python3.7 Ubuntu 18.04 package.
 * graphene-django==2.2.0
 * django-filter==2.0.0
 * graphene==2.1.3

**Comment by Somtom** [comment]
I have a similar problem with `MultipleChoiceFilter`.
In my case it returns an empty queryset as soon as I use the `MultipleChoiceFilter` field in the query. If I don't use it or use a `CharFilter` or `NumberFilter` it works again.
Also if I change `MultipleChoiceFilter` to `CharFilter` it also works.

**Comment by amarkezic** [comment]
@SN9NV I found the source of the problem
https://github.com/carltongibson/django-filter/issues/1078

**Comment by phalt** [comment]
I believe this is an issue with django-filter and not graphene-django. Can we close this?

**Comment by rpkilby** [comment]
This is an issue in graphene-django, although django-filter's docs should be updated to discuss error handling. The short version is that the view should determine how to handle errors, checking whether the `filterset.is_valid()` and then what to do with the `filterset.errors`. Note that this is basically the same API as Django forms, which are used internally.

**Comment by phalt** [comment]
@rpkilby can you point me to the area in the code that is causing this bug so we can triage this issue?

**Comment by rpkilby** [comment]
I'm not that familiar with graphene-django, but the below is where the filterset is created and called:
https://github.com/graphql-python/graphene-django/blob/dc561c68c49d1a91637503f765857d819c36769a/graphene_django/filter/fields.py#L92-L96

Does it make sense for `DjangoFilterConnectionField.connection_resolver` to raise validation errors?

**Comment by zbyte64** [comment]
@rpkilby I think it makes sense.
