### ISSUE TITLE
Is there a way to pass Meta.filter_overrides to  DjangoFilterConnectionField ?

### ISSUE THREAD

**Issue by dionyself** [graphql-python/graphene-django#544]
Hello,  Django_filter supports the option `filter_overrides`.
 Is there a way to pass that atribute just like we do with  filterset_class?   `DjangoFilterConnectionField(CurrentNode, filterset_class=CuntomFilter)`  
I need to do something like this:
`DjangoFilterConnectionField(CurrentNode, filter_overrides=DataDict)`

**Comment by hypnotic-frog** [comment]
Hi! Currently I don't think there is.
Can't you just set the "filter_overrides" meta to your custom FilterSet and pass it?
