### ISSUE TITLE
Retrieve object primary keys with Relay

### ISSUE THREAD

**Issue by JBPressac** [graphql-python/graphene-django#547]
Hello,
Using Relay, the `id` field is not the primary key of the ingredients objects in the database. Is there a way to get it back ?

```
query {
  allIngredients {
    edges {
      node {
        id,
        name
      }
    }
  }
}
```

Thanks,

**Comment by mattychen** [comment]
In your class definition:

```python
class IngredientsType(DjangoObjectType):
   pk = graphene.Int(source='pk')
```

https://github.com/graphql-python/graphene-django/issues/349
