### ISSUE TITLE
How to customise mutation validation error messages

### ISSUE THREAD

**Issue by sultaniman** [graphql-python/graphene-django#548]
Hi,

I've been trying to customise mutation validation errors but so far didn't succeed in doing so, having the following query I would like to be able to return `errors` if different shape

```gql
mutation CreateProject($projectName: String!, $description: String!) {
  createProject(projectName: $projectName, description: $description) {
    id
    projectName
    description
  }
}
```

Standard errors look like
```json
{
  "errors": [
    {
      "message": "Variable \"$description\" of required type \"String!\" was not provided.",
      "locations": [
        {
          "line": 1,
          "column": 47
        }
      ]
    }
  ]
}
```

What I would like to have is

```json
{
  "errors": [
    {
        "$description": "Error message...",
        "locations": [...]
    }
}
```

So is it possible to adjust error response format?

Thanks.

**Comment by patrick91** [comment]
Yup, it is possible, I haven't tried but it should be here: https://github.com/graphql-python/graphene-django/blob/master/graphene_django/views.py#L176-L179

Let me know if that works!

**Comment by imanhodjaev** [comment]
@patrick91 thanks for information. I tried to look into tests to see some examples but didn't find one.
Does the [logic](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/views.py#L176-L179) mean that I have to manually validate or override `GraphQLView`?

Thanks.

**Comment by patrick91** [comment]
Yes, I think so :)

I would do:

```python
from graphene_django.views import GraphQLView

class MyGraphQLView(GraphQLView):
    def format_error(self, error):
        return 'ABC'
```

That should work, sorry I can't test this right now!

**Comment by imanhodjaev** [comment]
@patrick91 no worries, thank you very much for your time! I will definitely try it out.

**Comment by patrick91** [comment]
Let me know, might be worth to add something to the docs about this :)

**Comment by imanhodjaev** [comment]
@patrick91 I've been thinking about making a PR which documents this feature.

**Comment by imanhodjaev** [comment]
So I managed to make it and here is my solution

### Custom view
```python
from typing import Any, Dict

from graphene_django.views import GraphQLView
from graphql.error import GraphQLError

from graph.format_error import format_error


class MyGraphQLView(GraphQLView):
    @staticmethod
    def format_error(error) -> Dict[str, Any]:
        if isinstance(error, GraphQLError):
            return format_error(error)

        return GraphQLView.format_error(error)
```

### Error formatter

```python
from typing import Dict, Any

from graphql import GraphQLError


def format_error(error: GraphQLError) -> Dict[str, Any]:
    """Extract field from ``error`` and return formatted error
    :param error: GraphQLError
    :return: mapping of fieldName -> error message
    """
    [node_error] = error.nodes
    field_name = node_error.variable.name.value

    formatted_error = {
        field_name: str(error)
    }

    if error.path:
        formatted_error["path"] = error.path

    return formatted_error
```

**Comment by imanhodjaev** [comment]
@patrick91 documentation related question is where to add notion about custom error formatting? By the way is it planned to use `gettext` in `graphql-core` to have localised error messages?

Thanks.

**Comment by patrick91** [comment]
@imanhodjaev not sure, maybe we could create another page just for that :)

> By the way is it planned to use gettext in graphql-core to have localised error messages?

Good question, @syrusakbary I think this one is for you ;)

**Comment by imanhodjaev** [comment]
@patrick91 cool then I will create a page for it.

**Comment by phalt** [comment]
Closing as resolved, adding as a potential docs enhancement

**Comment by KingDarBoja** [comment]
Looking forward for the doc section regarding customization of error messages.

**Comment by mcabrams** [comment]
> Closing as resolved, adding as a potential docs enhancement

Is this closed because there is a new issue?
