### ISSUE TITLE
GraphQL Compression for query and response

### ISSUE THREAD

**Issue by StefanoSega** [graphql-python/graphene-django#554]
I would like to ask if gzip/zlib compression is already enabled for Graphene-Django endpoints and if it needs for the client to send the header `Accept-Encoding: gzip` to enable it.

Also is there a method or a library to compress GraphQL queries in Python?

Thanks a lot

**Comment by EverWinter23** [comment]
Any updates?

**Comment by topbloc-beiswenger** [comment]
Would also like some more information on this

**Comment by mwcbrent** [comment]
I found that enabling the Django gzip middleware `django.middleware.gzip.GZipMiddleware` works well.  Pass the `Accept-Encoding: gzip` header and it works like a charm.
