### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by thevaleriemack** [graphql-python/graphene-django#561]
Would like to know because I just got started with this on a new project and already running into loads of trouble. @syrusakbary 

Looks like issues are piling up so just interested to know the status on this?

Thx

**Comment by patrick91** [comment]
@thevaleriemack hopefully soon we'll get some maintainers here :)

See: https://github.com/graphql-python/graphene-django/pull/508#issuecomment-444208767

**Comment by maarcingebala** [comment]
Indeed, this project may look abandoned, especially when taking into account the list of open PRs - so many of them seem so useful and should be merged on a regular basis. It worries me a lot as this is still the most mature framework for GraphQL in Django and a lot of projects rely on it (including mine).

There is already a community around Graphene with quite many good contributors who do advanced stuff with it. There would be at least a few people who'd be able to do the code reviews and merging. What may be missing is a clear roadmap and agreement on what direction should the project go and what problems should do community focus on to make it better.

**Comment by syrusakbary** [comment]
I've created an issue in Graphene to define a full maintenance plan for Graphene and it's sub-projects:

https://github.com/graphql-python/graphene/issues/884

**Comment by BossGrand** [comment]
Closing as this has been answered
