### ISSUE TITLE
GraphiQL to version v0.11.11?

### ISSUE THREAD

**Issue by brubbel** [graphql-python/graphene-django#572]
Proposal to move to GraphiQL v0.11.11 to solve a markdown issue in the documentation:
cfr. https://github.com/graphql/graphiql/issues/575

Scanning over the code, the main difference between v0.11.10 and v0.11.11 is a switch from 'marked' to 'markdown-it' for rendering the documentation.

Affected lines:
https://github.com/graphql-python/graphene-django/blob/f76f38ef30b88d921df243b09c4970528b1a4007/graphene_django/views.py#L54

**Comment by dopeboy** [comment]
I don't see we can't update this given that 0.11.10 came out close to 1.5 years ago. Adjusting the labels.

**Comment by phalt** [comment]
Adding to our current project
