### ISSUE TITLE
Support FTS Queries

### ISSUE THREAD

**Issue by jakeseaton** [graphql-python/graphene-django#575]
I have a full text search field using `pg_fts`. Using the ORM I can query it using the Django search lookup e.g. `Model.objects.filter(fts_index__search="query")`. When I try to do this via grapgene, I set it up like this:

```python
class Model:
    fts_index = TSVectorField()

class Node(DjangoObjectType):

    class Meta:
        model = Model
        interfaces = (Node,)
        filter_fields = {
            'fts_index': ['search']
        }
```

However, I get this error: `FilterSet resolved field 'fts_index' with 'search' lookup to an unrecognized field type TSVectorField. Try adding an override to 'Meta.filter_overrides'. See: https://django-filter.readthedocs.io/en/master/ref/filterset.html#customise-filter-generation-with-filter-overrides`. Ideally, graphene would identify TSVectorField as a subclass of CharField and enable me to use the __search lookup normally. Is there a better way of doing this?

**Comment by gotexis** [comment]
+1 for FTS.

Have you tried using FTS with django-filters tho?

I remember calling for help there, and some1 did gave me an example, but too bad I haven't got time to test it.

Would you care to take a look @jakeseaton 

[#103](https://github.com/carltongibson/django-filter/issues/1039)
