### ISSUE TITLE
Get global ID from a model object

### ISSUE THREAD

**Issue by samkit-jain** [graphql-python/graphene-django#578]
Say, I query an object like `obj = Person.objects.get(first_name='John', last_name='Lennon')`. How can I get the global ID that would be created for this object? Is there a method where I can pass in the object and in response get the global ID?

How the node looks in schema
```python
class PersonNode(DjangoObjectType):
    class Meta:
        model = Person
        filter_fields = ['first_name', 'last_name']
        interfaces = (graphene.relay.Node, )
```

**Comment by hilmarh** [comment]
This should work

```python
from graphql_relay import to_global_id

to_global_id(PersonNode._meta.name, object.pk)
```

Source: https://github.com/graphql-python/graphene/blob/v2.1.3/graphene/relay/tests/test_global_id.py

**Comment by samkit-jain** [comment]
@hilmarh Thanks, this works.
