### ISSUE TITLE
Building mutations from scratch - django form or DRF better?

### ISSUE THREAD

**Issue by gotexis** [graphql-python/graphene-django#594]
I have a project from total stratch. In terms of simplicity which will be easier?

**Comment by zbyte64** [comment]
I tend to use the DRF mutations for when I already have DRF serializers, otherwise I tend to reach for django forms. There are more rough edges with the django form mutations but it feels like your going through one less abstraction and have more direct control of behavior.

**Comment by gotexis** [comment]
@zbyte64 Thanks for your input.

Actually, I have one question for access control.

We know in DRF, access control could be attained through mixins in a generic and composable way.

Surely we need some kind of access control, I wonder if SerializerMutation inherits that access control? Or do we have to define access control logic elsewhere?

(side note: surprisingly, I have never actually used DRF since the first time I build an API, GraphQL is already "the thing")

**Comment by zbyte64** [comment]
I don't think the access control carries over, unless you have custom logic implemented in the serializer class. Most of the DRF permissions appear to be hooked in at the view level before it is handed off to the serializer.

**Comment by phalt** [comment]
@zbyte64 @zbyte64 can we close this? Archived issues can still be searched.
