### ISSUE TITLE
multiple frontend calling the same API - how to distinguish which is calling?

### ISSUE THREAD

**Issue by gotexis** [graphql-python/graphene-django#597]
I have a use case where 1 backend will serve an unlimited amount of frontends.

The frontends will be serverless/static Web apps (Vue).

Every frontend calls the same API.

Each frontend **do not share** info.

Now how to distinguish which is calling, in order to serve the correct content? I have some ideas:

1. check the HTTP-REFERER header, but this can be spoofed or blocked from sending by certain clients.

2. make a custom header. Concerns same as above.

3. Include site information (ID or a hash) in queries, but if the client modifies the query, he/she could see info from another scope...

4. Couple a mini-backend (Express?) into the VueApp and use server-2-server communication, despite a lot of work this seem to be promising?

Thanks for any share of thoughts

**Comment by zbyte64** [comment]
This question is not specific to this project. I would recommend asking this on stackoverflow.

**Comment by gotexis** [comment]
Yeah, given that there are already 221 open issues now, really this is the very least priority,

sure buddy
