### ISSUE TITLE
"Expected value of type \"Visit\" but got: Visit."

### ISSUE THREAD

**Issue by threewordphrase** [graphql-python/graphene-django#599]
Hello, I have a very strange issue. Just playing around with GraphQL in an existing project.  Here is my schema:

```
import graphene
from graphene_django.types import DjangoObjectType

from ops.models import Visit as VisitModel

class Visit(DjangoObjectType):
    class Meta:
        model = VisitModel

class Query(graphene.ObjectType):
    visits = graphene.List(Visit)

    def resolve_visits(self, info):
        return VisitModel.objects.all()

schema = graphene.Schema(query=Query)
```

Query:
```
{
  visits {
  	createdAt
  }
}
```

Output:
```
{
  "errors": [
    {
      "message": "Expected value of type \"Visit\" but got: Visit.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "Expected value of type \"Visit\" but got: Visit.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "Expected value of type \"Visit\" but got: Visit.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
```

FWIW, these are Proxy Models, not sure if that matters.

**Comment by zbyte64** [comment]
Possibly a recreation of #319 ; Right now basic proxy models are suppose to work, but expects VisitModel to be the base proxy. The test is also using the relay interface and some other params, perhaps we should duplicate the test without those extra params as you did here.

**Comment by abettke** [comment]
To add to this, we are finding this same behavior as well with the following library versions. It only seems to occur on Types that are using a proxy model.

graphql-core==2.1
graphene==2.1.3
graphene-django==2.2.0

**Comment by abettke** [comment]
https://github.com/graphql-python/graphene-django/pull/603 addresses this issue.
