### ISSUE TITLE
Adding DjangoModelFormMutation to schema raises import error

### ISSUE THREAD

**Issue by GitRon** [graphql-python/graphene-django#602]
Hi there!

I try to use the awesome `DjangoModelFormMutation` but when I add the mutation to the schema I always get this error:

`Could not import 'project.config.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'NoneType' object has no attribute '_meta'.`

Here's my setup:

```
class Pet(models.Model):
    name = models.CharField()

class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ('name',)

class PetMutation(DjangoModelFormMutation):
    class Meta:
        form_class = PetForm

class PetMutations(graphene.ObjectType):
    pet = PetMutation.Field(description="Pets!")


class Mutation(PetMutations,
               graphene.ObjectType):
    pass

schema = graphene.Schema(query=Query, mutation=Mutation)
```

Any ideas what I might be doing wrong?

Thanks!
Ron

**Comment by GitRon** [comment]
Ok, this seems to be a bug! When I copy all my types above my mutation class, I don't get this error. Took me about 5h to find this out... 😱 

I added the types manually to the schema like this:

```
types = [PetType]
schema = graphene.Schema(query=Query, types=types, mutation=Mutation)
```

But no effect.

**Comment by zbyte64** [comment]
django-graphene is trying to import your schema file and is encountering another error along the way. I would recommend doing a `manage.py shell` and attempt manually importing the schema. This way you can see the import error without other code eating the message.

**Comment by GitRon** [comment]
@zbyte64 Thanks for the reply! I know that it's exactly this Mutation that's causing the problem. But if you know about a good way to inspect this with the `shell` I'd be happy to know about it.

But as I said I'm pretty sure that it is a bug. I'm going to dive a little deeper in the source code today and see if I can find out something.

But I wonder that I seem to be the first guy having issues like this... 🤔

**Comment by GitRon** [comment]
Update: The error comes from the part where I register the mutation:

```
class PetMutation(graphene.ObjectType):
    spaces = PetMutation.Field()
```

Any idea why the `Field()` does not have a type and how I solve this?

**Comment by GitRon** [comment]
Apparently I have to name the mutation:

```
class PetMutation(graphene.ObjectType):
    spaces = PetMutation.Field('pets')
```

Might be nice to have this in the docs?

**Comment by GitRon** [comment]
Ok, now I found the issue!

I need to import above my mutation the `PetType`! Without a usage...

```
from project.schemes.schematypes import PetType

class PetCrudMutation(DjangoModelFormMutation):
    class Meta:
        form_class = PetForm

class PetMutation(graphene.ObjectType):
    pets= PetCrudMutation.Field("pets")
```

So this is really a bug.

**Comment by vojto** [comment]
For me, this was occurring when I created a `CreatePersonMutation` without having created a `PersonType`:

```python
class CreatePersonMutation(DjangoModelFormMutation):
    class Meta:
        form_class = PersonForm

    ok = graphene.Boolean(required=True)
```

I was able to fix it just be defining a `PersonType` above the mutation:

```python
class PersonType(DjangoObjectType):
    class Meta:
        model = Person
```
