### ISSUE TITLE
Custom Graphql Template

### ISSUE THREAD

**Issue by x9sheikh** [graphql-python/graphene-django#606]
I want to get this type of custom screen which is following below:
![image](https://user-images.githubusercontent.com/45112750/55131692-848bf680-5141-11e9-9240-efcb48a36192.png)
but I have this 
![image](https://user-images.githubusercontent.com/45112750/55131741-b1d8a480-5141-11e9-82e0-2ddec45c94aa.png)
Due to this I'm getting an authentication issue. Can you resolve it. Respected Thankx in advance for all of my Professional Programmers!

**Comment by x9sheikh** [comment]
Unfortunately, the GraphiQL web interface that we use (that looks like a white interface) does not accept  custom HTTP headers or more advanced settings.So, to getting a advanced GraphiQL web interface we have to install Insomnia desktop app. You can download and install it from `[here](https://insomnia.rest/download/)`.
So, If you have fresh beginner just like me. Then, [here](https://www.youtube.com/watch?v=ErDCN_oU9a8) is a YouTube tutorial for better understanding that "Why we use **INSOMNIA DESKTOP APP**

**Comment by jbovenschen** [comment]
As pointed out by @x9sheikh the GraphiQL is a really bare bones graphql interface. 

I think the best way forward is to replace the GraphiQL web interface with [graphql-playground](https://github.com/prisma/graphql-playground) which does support more configuration options.

**Comment by dopeboy** [comment]
@phalt Are we OK to close this? I think we should - there's easy to install alternatives and it's critical to the project. Maybe we can make a mental note to comb this in the future when we're ready to take on nice-to-have's?

**Comment by phalt** [comment]
@dopeboy yep.
