### ISSUE TITLE
`exclude_fields` doesn't actually assign anything to `_meta.exclude`

### ISSUE THREAD

**Issue by monokrome** [graphql-python/graphene-django#607]
Yo! I am trying to use `exclude_fields` after installing the latest version of *graphene_django*, but `exclude_fields` doesn't get assigned to `_meta`. 🙀 

I'm trying to debug this, and I thought that adding it here may fix the issue - but it doesn't seem to? https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py#L107-L112

Any ideas, let me know! Happy to pop over a PR, will be looking into it as well 😺

**Comment by monokrome** [comment]
Just realized that this may be a bug in graphene specifically, hard to tell from my end. Hopefully someone here has an idea. ❤️

**Comment by zbyte64** [comment]
I believe the class consults `exclude_fields` to construct `django_fields` (stored as `fields`) and doesn't store the actual field params.

**Comment by jvmaia** [comment]
did you open the PR?
I got the same error while trying to use that

**Comment by phalt** [comment]
Hey @monokrome - are you able to provide us with some code examples to help debug the issue better?

**Comment by defiler** [comment]
Bump. Still an issue.

**Comment by monokrome** [comment]
Unfortunately I ran into a few issues similar to this one and decided to not use this library for now - so I don't know how to reproduce. Whenever I tried to supply `exclude=`, it was just ignored. When inspecting the Model, it wasn't there 🤷‍♀
