### ISSUE TITLE
how to login to graphql page(localhost:8000/graphql) with django

### ISSUE THREAD

**Issue by liamstory** [graphql-python/graphene-django#612]
I want to use @login_required function like below code. and I want to check the query correctly works.

import graphene 
from graphql_jwt.decorators import login_required

class Query(graphene.ObjectType):
    user = graphene.Field(UserType)

    @login_required
    def resolve_me(self, info):
        user=info.context.user
        return types.UserProfileResponse(user=user)
i put the code into graphql(localhost:8000/graphql)

query{me{user{id}}}}

the message is you do not have permission to perform this action

I think maybe I have to give token to graphql. but i don't know how to give token. could you teach me?

**Comment by phalt** [comment]
You will need to use token authentication to log the user in.
graphene does have this support, but the popular Django-Rest-Framework has a nice plugin for this, see https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

**Comment by phalt** [comment]
I noticed you're using django-graphql-jwt, have you read the documentation on how to do that? https://github.com/flavors/django-graphql-jwt/

**Comment by liamstory** [comment]
@phalt thank you it is reduce my time!!
