### ISSUE TITLE
Is it possible to use AsyncExecutor?

### ISSUE THREAD

**Issue by artinnok** [graphql-python/graphene-django#616]
Hello!

How can I use AsyncExecutor with **graphene-django?**

I try this setup:
```
# types.py
class Source(graphene.ObjectType):
    value = graphene.String()

# queries.py
class SourcesQuery(graphene.ObjectType):
    sources = graphene.List(
        of_type=Source
    )

    async def resolve_sources(self, info):
        await asyncio.sleep(0.0001)
        return [Source(value='foo'), Source(value='bar')]

# backend.py
class CustomBackend(GraphQLCoreBackend):
    def __init__(self, *args, **kwargs):
        self.execute_params = {
            "executor": AsyncioExecutor(),
            "return_promise": False,
        }

# urls.py
path("graphql", GraphQLView.as_view(
        backend=CustomBackend(),
        schema=graphene.Schema(query=SourcesQuery),
    )),
```
But this didn't work.
What is wrong?

**Comment by jbovenschen** [comment]
If I understand this question correctly, you are trying to implement asynchronous code within the default Django resolver. This is not supported within Django itself as far as I know. 

What we did to resolve asynchronous execution of graphql resolvers / subscriptions is to use the django-channels package in combination with apollo-client.

More info can be found here https://github.com/graphql-python/graphene/issues/430, and this gist https://gist.github.com/tricoder42/af3d0337c1b33d82c1b32d12bd0265ec

**Comment by artinnok** [comment]
@jbovenschen thanks!

Do you have working example with **AsyncExecutor**?

**Comment by japrogramer** [comment]
@artinnok  like @jbovenschen  said in the link to the issue i have this example
https://github.com/graphql-python/graphene/issues/430#issuecomment-479364746

**Comment by dopeboy** [comment]
Closing this down since it looks like it reached resolution. Thanks @jbovenschen for your help here.

**Comment by Suor** [comment]
Why is this closed? There is still no way to use async executor nor resolvers. At least not with provided GraphQLView.
