### ISSUE TITLE
Not compatible with django-filters 1.0.0

### ISSUE THREAD

**Issue by mattmccormick** [graphql-python/graphene-django#62]
graphene_django.filter.utils line 22 is expected order_by to be present in the _meta object but it is not available in django-filters 1.0 due to breaking changes.

https://django-filter.readthedocs.io/en/develop/guide/migration.html#move-filterset-options-to-meta-class

**Comment by syrusakbary** [comment]
This should be fixed by 48993ddca0a7fa16dfb0888a808eea88accb3d4c (graphene-django version 1.2.0). Please reopen if the issue persists.
