### ISSUE TITLE
404 on GraphiQL static file

### ISSUE THREAD

**Issue by kimbriancanavan** [graphql-python/graphene-django#620]
`static/` doesn't appear to be included in the `MANIFEST.in` file. This is causing my graphiql page to not load due to a 404 on `graphiql.js`. Am I missing something here?  I'd be happy to put together a PR with this line added to `MANIFEST.in`:
```
recursive-include graphene_django/static *
```

**Comment by phalt** [comment]
Hey @kimbriancanavan - thanks for bringing attention to this.

We already have a PR for this - https://github.com/graphql-python/graphene-django/pull/601

So closing this ticket.
