### ISSUE TITLE
Generic relationship type

### ISSUE THREAD

**Issue by vsoch** [graphql-python/graphene-django#625]
I've used django quite a bit, and am hoping to check out graphene-django as an introduction to using Graphene. The graph I'm starting with is based on schema.org, which means that a relationship can be of one or more types. I looked quickly through some of the example models but I didn't see how to easily do this. Does graphene-django have some integration / something that looks like the [django generic relation](https://docs.djangoproject.com/en/2.2/ref/contrib/contenttypes/#generic-relations)?

Many thanks!

**Comment by phalt** [comment]
Hi @vsoch thanks for the question. I am not sure graphene-django currently supports something like this out of the box, but you can use a resolver to get the same effect:

```python

class BookType(DjangoObjectType):
    class Meta:
        model = Book

    my_generic_relation_field = graphene.Field(GenericType)

    def resolve_my_generic_relation_field(self, info):
        # Get the object you want however you want to

```

Hope that leads you in the right direction.

**Comment by vsoch** [comment]
Thanks @phalt - is the resolved linked to the field just by way of the name? E.g., `resolve_<name>` as a function of class BootType will automatically be use for resolution to the field `<name>`? Would this work for any kind of field, and what is provided by "info" ?

Thanks for your speedy response!

**Comment by phalt** [comment]
The resolver method maps to the name of the attribute you set on the class, so for example:

```python
class MyModelType(DjangoObjectType):
    class Meta:
        model = MyModel
    foo = graphene.String()

    def resolve_foo(self, info):
```
