### ISSUE TITLE
Cannot import graphene_django.tests.base_test.GraphQLTestCase

### ISSUE THREAD

**Issue by Timmerop** [graphql-python/graphene-django#628]
when I pip install or download it directly here https://pypi.org/project/graphene-django/2.2.0/ 
base_test.py is missing.

**Comment by phalt** [comment]
@Timmerop just that one file or all tests?

Why are you looking for tests in the pip-installable version of the package?

**Comment by Timmerop** [comment]
I'm trying to use `from graphene_django.tests.base_test import GraphQLTestCase` in my tests

**Comment by phalt** [comment]
@Timmerop there is a fix in #631 for this now, we will publish the fix in release 2.3 - if you need it sooner then download this commit directly :)

**Comment by Timmerop** [comment]
Thanks for making the fix!

**Comment by ZikDead** [comment]
why i cant install 2.3.0 version? ...

**Comment by robertpro** [comment]
@ZikDead You can do it now, it wasn't released on pypi yet
