### ISSUE TITLE
`ManyToOneRel` fields are wrongly named, causing the field resolver to return every single record.

### ISSUE THREAD

**Issue by yen223** [graphql-python/graphene-django#63]
<This is on Django 1.8.16>

A foreign key on model `Article` to model `Reporter` will automatically create a reverse field called `article_set` on the `Reporter` model. However for some reason, the corresponding related field name does not contain the `_set` suffix:

```
>> Reporter.article_set.related.name
'article'
```

This causes the constructed field on the ReporterObjectType to be wrongly named `article` at https://github.com/graphql-python/graphene-django/blob/master/graphene_django/types.py#L25, which in turn causes the `Reporter.article` field to be unresolvable, as the Reporter instance lacks the `article` attribute. 

That in turn causes https://github.com/graphql-python/graphene-django/blob/master/graphene_django/fields.py#L49 to default to the `Article` model's manager, which results in every Article instance being returned.

**Comment by nickhudkins** [comment]
@yen223 just ran into this with User Models, where a ManyToManyRel results in a field called "user" being created on "user", returning all users. Have you tried to address this?

**Comment by yen223** [comment]
@nickhudkins My workaround was to exclude all m2m fields, and redefine the m2m fields with explicit resolvers.

**Comment by nickhudkins** [comment]
@yen223 same here 👍  thanks for the feedback.
