### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphene-django#632]
There seem to be quite a few issues in the docs. Just ran into these:

In http://docs.graphene-python.org/projects/django/en/latest/queries/, under `Full example` at the top:

```
    questions = graphene.List(QuestionType)
    question = graphene.Field(Question, question_id=graphene.String())
```

Should read:
```
    questions = graphene.List(QuestionType)
    question = graphene.Field(QuestionType, question_id=graphene.String())
```

At the bottom, again under `Full Example` in the `Relay` section:

```
class QuestionType(DjangoObjectType):
    class Meta:
        model = Question
        interaces = (relay.Node,)
```

Should read:
```
class QuestionType(DjangoObjectType):
    class Meta:
        model = Question
        interfaces = (relay.Node,)
```

Perhaps this issue (or does one exist already?) would be a good place to encourage folks to post specific issues in the Documentation?

If these are still present when I have more time, I'll fix these two in a PR, but that might be several days.

**Comment by changeling** [comment]
Additionally, the `Relay` section `Full example` seems to indicate that resolvers are not necessary. Is that correct, and I'm completely missing something?

In any case, the example doesn't seem to work unless something like the following, at least, is added:

```
    def resolve_questions(self, info, **kwargs):
        return Question.objects.all()
```

The Full example currently reads:
```
from graphene import relay
from graphene_django import DjangoObjectType
from .models import Question


class QuestionType(DjangoObjectType):
    class Meta:
        model = Question
        interaces = (relay.Node,)


class QuestionConnection(relay.Connection):
    class Meta:
        node = QuestionType


class Query:
    question = graphene.Field(QuestionType)
    questions = relay.ConnectionField(QuestionConnection)
```

**Comment by phalt** [comment]
Hey @changeling thanks for finding these. I am re-writing the docs currently, and the parts you've highlighted are new and clearly missed a thorough review. I'll make a PR when I get back next week (unless you want to!) and we can merge the fixes.

**Comment by changeling** [comment]
Hey, @phalt, glad to help out. I've submitted a PR with these fixes, with a note regarding the Relay Full example. My resolvers are rudimentary, and should probably be extended a little to implement filtering.

**Comment by changeling** [comment]
I've added a simple beginning for a FAQ on the graphene page. Se if you think this might be valuable:

https://github.com/graphql-python/graphene/wiki/FAQ

**Comment by phalt** [comment]
@changeling are you able to edit this now?

https://github.com/graphql-python/graphene-django/wiki

**Comment by changeling** [comment]
@phalt, yep! Thanks! Any thoughts on this approach?

**Comment by phalt** [comment]
@changeling organically adding stuff there that can't be added to docs is something I'm okay with. Wikis are meant to be fluid. And anything we really like we can solidify into the official docs.

**Comment by changeling** [comment]
> @changeling organically adding stuff there that can't be added to docs is something I'm okay with. Wikis are meant to be fluid.

Great. I'm a fan of 'em. It also allows a broader community to point out issues they struggle with, and solutions found. In my experience, this tends to evolve them towards best practices.

> And anything we really like we can solidify into the official docs.

That's exactly my thinking.

**Comment by changeling** [comment]
Though I spoke to soon. I had checked that the wiki was now active, but didn't check for open editing. I see your initial page, but editing is still disabled. Apologies for the incomplete test, as it were.

**Comment by phalt** [comment]
@changeling working on it, I _should_ have admin rights for the project so let me try sort it.

**Comment by phalt** [comment]
@changeling sorted, go wild! (with moderation 😆 )

**Comment by changeling** [comment]
Great! Going wild(-ish)!
