### ISSUE TITLE
Sharing DjangoObjectType fields with Mutation

### ISSUE THREAD

**Issue by jsangilve** [graphql-python/graphene-django#64]
I have this Django Person model which create mutation looks like this:
```
mutation  {
    createPerson(first_name:"Peter", last_name:"Smith", age:27) {
        person {
            first_name, last_name, age
        }
    }
}
# Result
{
    "createPerson": {
        "person" : {
            "first_name": "Peter",
            "last_name": "Smith",
            "age": 27
        },
    }
}
```

Is there any way I could transform that to (using alias for `createPerson`):
```
mutation  {
    person:createPerson(first_name:"Peter", last_name:"Smith", age:27) {
       first_name,
       last_name,
       age
    }
}
# Result
{
        "person" : {
            "first_name": "Peter",
            "last_name": "Smith",
            "age": 27
        },
}
```
I know how can I do this using Graphene's `AbstractType` and `ObjectType` ([Docs' example](http://docs.graphene-python.org/en/latest/types/abstracttypes/#quick-example)), but cannot make it work using `DjangoObjectType`.

Basically, the class `CreatePerson` should have PersonNode's fields instead of this `person` field wrapping PersonNode's fields. Is there any way I can do this using `PersonNode` (`DjangoObjectType`)?

Please, find the code below:
```python

# Model
class Person(models.Model):
    first_name = models.CharField()
    last_name = models.CharField()
    age = models.IntegerField()

# DjangoObjectType
class PersonNode(DjangoObjectType):
    class Meta:
        model = Person
        interfaces = (Node, )

# CreatePersonMutation
class CreatePerson(graphene.Mutation):
    class Input:
        first_name = graphene.String()
        last_name = graphene.Float()
        age = graphene.Integer()

    person = graphene.Field(PersonNode)

    def mutate(self, args, context, info):
        # do the model mutation...
        return CreatePerson(person=person)

# Creating Schema
class MyMutations(graphene.ObjectType):
    create_person = CreatePerson.Field()

schema = graphene.Schema(mutation=MyMutations)
```

**Comment by zbyte64** [comment]
I guess you could define all the person fields in the CreatePerson:

```
class CreatePerson(graphene.Mutation):
    class Input:
        first_name = graphene.String()
        last_name = graphene.Float()
        age = graphene.Integer()

    id = graphene.ID()
    first_name = graphene.String()
    last_name = graphene.Float()
    age = graphene.Integer()

    def mutate(self, args, context, info):
        # do the model mutation...
        return CreatePerson(**person)
```

I'm thinking the reason this is frowned upon is due to error handling and possibly caching. With the above mutation error is just another field of a CreatePerson result. On top of that, some clients like to add `__typename` but in the above case the result would be of a different type from `PersonNode` and would likely be cached differently (global ID can be used instead to resolve the type though)
