### ISSUE TITLE
Name "__debug" must not begin with "__", In a future release of graphql this will become a hard error.

### ISSUE THREAD

**Issue by Zorig** [graphql-python/graphene-django#640]
it's popped from graphiql `graphiql.min.js:1 Name "__debug" must not begin with "__", which is reserved by GraphQL introspection. In a future release of graphql this will become a hard error.`

**Comment by phalt** [comment]
Adding to the current project so we can resolve this.

**Comment by dulmandakh** [comment]
@phalt what is your proposition about solution? _debug or anything else?

**Comment by phalt** [comment]
@dulmandakh I don't have a solution yet myself, I'm moving it to the improvements project so we can focus on it. Do you have a suggestion?

**Comment by dulmandakh** [comment]
@phalt create a PR, please see https://github.com/graphql-python/graphene-django/pull/646

**Comment by portedison** [comment]
I'm trying to integrate graphene==2.1.9 with graphql-code-generator, and had this same issue.

Error: Name "__debug" must not begin with "__", which is reserved by GraphQL introspection.
at assertValidSchema (/Users/Code/app/node_modules/graphql/type/validate.js:59:11)

path('graphql', csrf_exempt(GraphQLView.as_view())),

GRAPHENE['MIDDLEWARE'] = GRAPHENE['MIDDLEWARE'] +\
        ["graphene_django.debug.DjangoDebugMiddleware", ]

overwrite: true
schema: "http://127.0.0.1:8000/graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"
