### ISSUE TITLE
release 2.3.0

### ISSUE THREAD

**Issue by dulmandakh** [graphql-python/graphene-django#648]
it's been a while since v2.2.0, and how about releasing v2.3.0 soon. Are there any blocking issues or planned features?

I've installed graphene-django from pip, and most documentations didn't work due to version difference. Now I use it from master, and it works quite well for me. Also looking at releases I got an impression that the project is dead or abandoned. So it might be time for another release.

@syrusakbary @phalt

**Comment by phalt** [comment]
Hey @dulmandakh - I don't have the necessary permissions to do a pypi release, but I have drafted the release notes here: https://github.com/graphql-python/graphene-django/releases/tag/untagged-1a312685cdd9b5b277f8

The Graphene community is having a meeting on 31st May to discuss the organisation of the project, I hope we can automate releases or get an outcome on giving projects a bit more autonomy.

**Comment by dulmandakh** [comment]
Thank you for the response. I would like to see more automation and frequent releases as a graphene-django user, and I think most users will agree with me. Also I plan to be active in the community doing reviews and PRs when possible.

So it might be best to publish a version to pypi for each version tag, and tag is handled by you or community members.

FYI, release notes link is not working.

**Comment by anudeepsamaiya** [comment]
@dulmandakh https://github.com/graphql-python/graphene-django/releases/tag/v2.3.0

**Comment by robertpro** [comment]
Looks like it is now on [pypi](https://pypi.org/project/graphene-django/) :)

**Comment by jkimbo** [comment]
Can confirm that v2.3.0 has been released and is available on PyPi.
