### ISSUE TITLE
Add autodoc-style API reference.

### ISSUE THREAD

**Issue by changeling** [graphql-python/graphene-django#650]
It would be a tremendous boon for this and for all projects within the ecosystem here to add an autodoc API reference to the documentation. For other python libraries, this is, at least for me, the _most_ frequentlly used component of the docs. A PR for this has been submitted in the `graphene` repo, and should be duplicated, IMHO, here.

See https://github.com/graphql-python/graphene/pull/971

**Comment by jkimbo** [comment]
Closing this as a duplicate of #679
