### ISSUE TITLE
Using a different graphiql.html

### ISSUE THREAD

**Issue by cowlicks** [graphql-python/graphene-django#659]
Hi I had a need to use a different graphiql.html document. So I did this:
```python
# urls.py
from graphene_django.views import GraphQLView

GraphQLView.graphiql_template = 'my_own_project/graphiql.html'
urlpatterns = [
    ...
    re_path(r'^graphql/?$', GraphQLView.as_view(graphiql=True)),
]
```

It'd be nice if there was an "official" way to do this, so I don't have to worry about my code breaking later.

I suspect other people might need a way to do this too. I needed it to support subscriptions with `subscriptions-transport-ws` and to add some js to refresh auth tokens on the client.

Thanks,

**Comment by jkimbo** [comment]
@cowlicks that seems like a fine way to do that! The alternative would be to subclass `GraphQLView` to override the variable or the `render_graphiql` method. Subclassing is a pretty common practice to override behaviours and you shouldn't have to worry about your code breaking. Did you have another suggestion as to how to do it?

**Comment by robertpro** [comment]
I would vote for the Subclassing way, maybe in a views.py file at the same folder as schema.py?

**Comment by jkimbo** [comment]
I'm going to close this issue now because there are multiple ways to achieve this.
