### ISSUE TITLE
Feature request: way to require only_fields

### ISSUE THREAD

**Issue by reverie** [graphql-python/graphene-django#671]
There doesn't seem to be a way to enforce `only_fields` on `DjangoObjectType`s. This is a serious security issue, since fields all default to accessible, including Django's automatically created reverse relation fields.

I tried to introspect this value, but it gets erased at class creation time. We only end up with `MyType._meta.fields`, which is a value computed from several inputs including `only_fields`. Possible solutions:
- Copy `only_fields` onto `_meta`
- Don't delete the `Meta` attribute from the class in `SubclassWithMeta`
- Official support for requiring `only_fields`, in the form of a configuration setting

Related: #516

**Comment by jkimbo** [comment]
@reverie sorry I'm not sure I understand what you are suggesting. You can define `only_fields` on the Meta class of a `DjangoObjectType` which will limit which model fields get exposed to the schema: http://docs.graphene-python.org/projects/django/en/latest/queries/#only-fields

How would keeping `only_fields` on the meta object mean that you could require it?

**Comment by reverie** [comment]
@jkimbo I'd like to have something like this at the end of my schema.py:
```
def enforce_only_fields(objects):
    import inspect
    for o in objects:
        if inspect.isclass(o) and issubclass(o, DjangoObjectType):
            # assert o._meta.only_fields

enforce_only_fields(locals().values())
```

**Comment by reverie** [comment]
I don't claim to understand the reasoning behind graphene's metaclass code, but I'm especially curious about why Meta gets deleted. Is there a good reason for that?

**Comment by jkimbo** [comment]
Right I get you now. I'm not 100% sure why the Meta class gets deleted either to be honest. I'll raise a PR in the Graphene repo and see if it gets anywhere.

**Comment by jkimbo** [comment]
@reverie https://github.com/graphql-python/graphene/pull/1007

Also your code above can be a bit cleaner by using the typemap from the schema directly (when the above PR has been merged):

```python
def enforce_only_fields(schema):
	types = schema.get_type_map()
	for _, t in types.items():
		if issubclass(t.graphene_type, DjangoObjectType):
			assert t.graphene_type.Meta.only_fields
```

**Comment by tony** [comment]
@jkimbo 

I'm wondering, what happened with `only_fields`? https://github.com/graphql-python/graphene-django/issues/97


Can this and #97 be reopened? Or is there another way to make sure only the fields declared show in an object?

**Comment by tony** [comment]
@jkimbo I stand corrected - maybe!

Am I to understand that `only_fields` was removed in 2.4.0 in favor of `fields`?

https://github.com/graphql-python/graphene-django/releases/tag/v2.4.0

**Comment by jkimbo** [comment]
@tony correct: `only_fields` has been renamed to `fields` (defining `only_fields` still works btw). We made this change so that it's more inline with Django Rest Framework. We'll also be warning if neither `fields` or `exclude` have been defined (again like DRF) so that people don't accidentally expose all fields on a model.
