### ISSUE TITLE
Release 2.3.1 not bump the version

### ISSUE THREAD

**Issue by hiroaki-yamamoto** [graphql-python/graphene-django#672]
Hi,

graphene-django 2.3.1 doesn't seem to bump the version (i.e. it's still 2.3.0 on setup.py).
Can you re-make a new release with the bumped version on [graphene_django/__init__.py](https://github.com/graphql-python/graphene-django/blob/ab551f4a15e787fafed8e050cb066b311daae5ed/graphene_django/__init__.py#L4)?

**Comment by phalt** [comment]
I don't believe 2.3.1 is an official release, I think it was done to fix our publishing mechanism. @mvanlonden might know more.

**Comment by hiroaki-yamamoto** [comment]
Ok, I see, but (as fyi,) that release has wrong version that should be fixed.

Close this issue if it's not needed...

**Comment by phalt** [comment]
I'll wait for confirmation from @mvanlonden

**Comment by imsickofmaps** [comment]
2.3.1 fixes real production breaking issues: https://github.com/graphql-python/graphene-django/releases/tag/v2.3.1

At the moment pypi (https://pypi.org/project/graphene-django/#history) is behind as a result of https://github.com/graphql-python/graphene-django/blob/v2.3.1/graphene_django/__init__.py#L4 not being `2.3.1`.

**Comment by phalt** [comment]
okay cool, @mvanlonden can you help us get this version out?

**Comment by phalt** [comment]
We will be doing a `2.3.2` release to fix this issue see #686

**Comment by jkimbo** [comment]
v2.3.2 (exactly the same as v2.3.1) has now been released to PyPi
