### ISSUE TITLE
Django integer fields gets transformed to Float?

### ISSUE THREAD

**Issue by crazyscientist** [graphql-python/graphene-django#678]
On a project of mine I noticed this unexpected behavior:

Using `graphene_django` with `graphene.relay` converts `IntegrierField`s of my models to `graphene.Float` properties in the API, e.g.:

```python
class Incident(models.Model):
    incident_id = models.IntegerField(unique=True)

class IncidentType(graphene_django.types.DjangoObjectType):
    class Meta:
        model = Incident
        interfaces = (graphene.relay.Node,)
        filter_fields = {
            'incident_id': ['exact'],
    }

class Query:
    incident = graphene.relay.Node.Field(IncidentType)
    incidents = DjangoFilterConnectionField(IncidentType)
```

To be precise, using the `incident` attribute shows the `incidentId` to be of type `Int`. But using the `incidents` attribute suggests that `incidentId` is of type `Float`.

I'd like to point out, that there is no error occurring, but it strikes me as weird.

I observed this with:
* Django 2.2
* django-filter 2.1.0
* graphene 2.1.3
* graphene-django 2.2.0
* graphql-core 2.1
* graphql-relay 0.4.5

**Comment by jkimbo** [comment]
@crazyscientist I can't reproduce your issue. If I setup my schema in the following way:

```python
from django.db import models

import graphene

from graphene_django.types import DjangoObjectType
from graphene_django.filter import DjangoFilterConnectionField


class Incident(models.Model):
    incident_id = models.IntegerField(unique=True)


class IncidentType(DjangoObjectType):
    class Meta:
        model = Incident
        interfaces = (graphene.relay.Node,)
        filter_fields = {"incident_id": ["exact"]}


class Query(graphene.ObjectType):
    incident = graphene.relay.Node.Field(IncidentType)
    incidents = DjangoFilterConnectionField(IncidentType)

schema = graphene.Schema(query=Query)
print(str(schema))
```

I get the following schema:

```
schema {
  query: Query
}

type IncidentType implements Node {
  id: ID!
  incidentId: Int!
}

type IncidentTypeConnection {
  pageInfo: PageInfo!
  edges: [IncidentTypeEdge]!
}

type IncidentTypeEdge {
  node: IncidentType
  cursor: String!
}

interface Node {
  id: ID!
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  incident(id: ID!): IncidentType
  incidents(before: String, after: String, first: Int, last: Int, incidentId: Float): IncidentTypeConnection
}
```

Where `IncidentType` has the field `incidentId` of type `Int` which is what I would expect.

The only difference I can see with your code is that you should make sure that `Query` inherits from `graphene.ObjectType` (it doesn't in your example).

Can you make a small reproducible example of the issue you are seeing?

**Comment by crazyscientist** [comment]
@jkimbo thanks for the reply, but you actually reproduced it:

```
# as expected an Int
type IncidentType implements Node {
  id: ID!
  incidentId: Int!
}

# here incidentId has become a Float?!
type Query {
  incident(id: ID!): IncidentType
  incidents(
    before: String, 
    after: String, 
    first: Int, last: Int, 
    incidentId: Float 
  ): IncidentTypeConnection
}
```

Don't get me wrong, the API is working as expected. I was just suprised that the type is `Float`

**Comment by jkimbo** [comment]
Huh I didn't notice that! Very strange, I'll look into why that's happening.

**Comment by jkimbo** [comment]
Ok so I've figured out what is going on but I'm not sure how to fix it. Basically Django-filter converts an IntegerField into a [NumberFilter](https://django-filter.readthedocs.io/en/master/ref/filters.html#numberfilter) and a NumberFilter defines it's Django form field as a [`DecimalField`](https://github.com/carltongibson/django-filter/blob/master/django_filters/filters.py#L361-L362). Graphene-Django uses that form field to determine the GraphQL type to use for the filter: https://github.com/graphql-python/graphene-django/blob/612ba5a4eaea0336a5dffcba3dbe7909b9d94646/graphene_django/forms/converter.py#L54-L57

I'm trying to figure out a way for the argument conversion to look at the actual underlying model field rather than the filter field but it's proving to be tricky. The relevant code is here: https://github.com/graphql-python/graphene-django/blob/612ba5a4eaea0336a5dffcba3dbe7909b9d94646/graphene_django/filter/utils.py#L6

**Comment by crazyscientist** [comment]
Thanks for the investigation @jkimbo .

To me this sounds more like an issue for Django-filter :thinking:

**Comment by jkimbo** [comment]
Possibly though from their perspective the NumberField makes sense, it's just that Graphene needs more accurate type information. I think I have a fix that could work, just doing some testing on it now.

**Comment by jkimbo** [comment]
@crazyscientist I've created a PR that should fix the issue: https://github.com/graphql-python/graphene-django/pull/682

**Comment by Gamsake** [comment]
I have the exact same issue on 2.4.0 the latest.
May i ask that you will apply the fix in v3?
Thanks.

**Comment by jkimbo** [comment]
@Gamsake this issue should be fixed in v2.4.0. Can you create a reproduction of the issue you are having?

**Comment by Gamsake** [comment]
@jkimbo Yes. I'm using 2.4.0 the latest now and 'id' the field of my model has Int type, but it is converted into Float type. Exactly same issue as above first post. I've done triple checks but i never solve this problem. any clue plz.

**Comment by djmaze** [comment]
Same problem as @Gamsake here, with 2.15.0. The problem seems to occur when using `filter_fields` on a django model's `id` column.

Our workaround is to define and set an explicit filterset class:

```python
class Country(models.Model):
    name = models.CharField(max_length=255, unique=True)


class CountryFilter(django_filters.FilterSet):
    id = django_filters.ModelChoiceFilter(queryset=Country.objects.all().values_list("id", flat=True))

    class Meta:
        model = Country
        fields = {
            "id": ["exact"],
            "name": ["exact"],
        }


class CountryType(DjangoObjectType):
    # ...

    class Meta:
        model = Country
        # filter_fields = ["id", "name"]
        filterset_class = CountryFilter
```

**Comment by hiporox** [comment]
I am having the same issue, @djmaze's solution works for me, but does not feel idea. Can we reopen this issue @zbyte64?

**Comment by jawang94** [comment]
Bump. The issue is still unresolved.

**Comment by Hornobster** [comment]
Same. Strange thing is that the graphene type for "id__in" is correct, `List[ID]`.
