### ISSUE TITLE
asserting status code before decoding json in assertResponseNoErrors 

### ISSUE THREAD

**Issue by dan-klasson** [graphql-python/graphene-django#684]
On a 404 with debug set to True the json decode will fail. `self.assertEqual(resp.status_code, 200)` should come before `json.loads(resp.content)`.

```
    def assertResponseNoErrors(self, resp):
        content = json.loads(resp.content)
        self.assertEqual(resp.status_code, 200)
        self.assertNotIn("errors", list(content.keys()))
```

**Comment by jkimbo** [comment]
@dan-klasson this is in the testing utils right? Seems like a reasonable change. Do you have time to make a pull request?

**Comment by dan-klasson** [comment]
@jkimbo Sorry, I just stumbled across this now by chance. Going to check my Github notification settings now.
