### ISSUE TITLE
404 Not Found after upgrade to 2.3

### ISSUE THREAD

**Issue by danielcwj16** [graphql-python/graphene-django#685]
Just upgraded to 2.3. Then cannot open `graphql` site anymore.  It shows `graphiql.js` file not found.

<img width="520" alt="Screen Shot 2019-06-19 at 11 10 41 PM" src="https://user-images.githubusercontent.com/22938626/59825159-155d1300-92e8-11e9-8cf7-3542a1a4a4dd.png">

<img width="358" alt="Screen Shot 2019-06-19 at 11 14 18 PM" src="https://user-images.githubusercontent.com/22938626/59825166-1db54e00-92e8-11e9-8675-e5397b7b5e18.png">

#683 looks similar to my issue, but I can't pull up the site with what @brandonmbanks did.

**Comment by phalt** [comment]
Have you ran `python manage.py collectstatic` ?

**Comment by shoof1072** [comment]
Could this be related to #508? 

Our project pulled in 2.3.0 and we observed the same 404, both FF and Chrome render a blank page at the /graphql/ path, and observed the following printed to our service log:
```
WARNING:django.request:Not Found: /static/graphene_django/graphiql.js
```
We've rolled back and pinned to 2.2.0 for now.

**Comment by danielcwj16** [comment]
> Have you ran `python manage.py collectstatic` ?

I tried this and it created a `static` folder with that `graphene_django/graphiql.js` in it. But still can not open the page, console gave the same error message.

**Comment by phalt** [comment]
We've just pushed out 2.3.2, can you check this is still occurring in that version? I am running 2.3 locally on my machine and I'm having no issues.

**Comment by danielcwj16** [comment]
> We've just pushed out 2.3.2, can you check this is still occurring in that version? I am running 2.3 locally on my machine and I'm having no issues.

Still not works

**Comment by jkimbo** [comment]
@danielcwj16 have you added `graphene_django` to your `INSTALLED_APPS` list in `settings.py`? `django.contrib.staticfiles` also needs to be in that list.

**Comment by evanheckert** [comment]
@jkimbo I have both of those in place, and have run collectstatic and am experiencing the same issue. Rollback to 2.2 solves it for now.

**Comment by jkimbo** [comment]
@evanheckert can you share your static file settings in `settings.py`? Or even better if you could create a reproduction of the issue that would be very helpful.

**Comment by dacevedo12** [comment]
@jkimbo We're experiencing the same problem. Here's what our static settings look like 
![image](https://user-images.githubusercontent.com/29694570/62228346-196a5f00-b383-11e9-8771-1e5ecdea83d3.png)

It works in the local development server but then fails after the app is deployed and served through wsgi

**Comment by jkimbo** [comment]
@dacevedo12 can you create a full reproduction of the issue (as a github repo)? I can't reproduce the problem.

**Comment by jkimbo** [comment]
Actually @dacevedo12 I think you need `os.path.join(PROJECT_ROOT, "static"),` in your `STATICFILES_DIRS` setting and you need to make sure you run `manage.py collectstatic` as part of your deployment process.

**Comment by eclar** [comment]
This is still present in 2.5 :) You can reproduce it with https://gitlab.com/eclar/django_deploy but only with the production image.

**Comment by evanheckert** [comment]
> This is still present in 2.5 :) You can reproduce it with https://gitlab.com/eclar/django_deploy but only with the production image.

Still an issue.

**Comment by mmitsui** [comment]
Has anyone tried updating `urls.py` as per the Django docs on static files ([Serving static files during development](https://docs.djangoproject.com/en/3.0/howto/static-files/))? This seemed to resolve the issue for me.

**Comment by evanheckert** [comment]
@mmitsui Yes, of course.

```
# urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView

urlpatterns = [
    path("__admin/", admin.site.urls), 
    path("gqlendpoint/", csrf_exempt(GraphQLView.as_view(graphiql=True)))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

```

And..
```
# settings.py
import os
...
...
STATIC_URL = "/static/"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
```

**Comment by jkimbo** [comment]
@evanheckert @Ouradze @dacevedo12 when running Django with `DEBUG=False` it will not host static files for you ([ref](https://docs.djangoproject.com/en/3.0/howto/static-files/#deployment)). You will need to run a server to host the static assets or use something like [whitenoise](http://whitenoise.evans.io/en/stable/) to get the python process to host them. Once you have that setup it should work fine.

The reason this changed in v2.3 is that we moved the graphiql javascript bundle into a separate file: https://github.com/graphql-python/graphene-django/pull/508

**Comment by jonwhittlestone** [comment]
> or use something like [whitenoise](http://whitenoise.evans.io/en/stable/) to get the python process to host them. Once you have that setup it should work fine.

I'm using whitenoise, and the only way I can get graphene responding at the route (ie. not 404) is if I set `DEBUG=True`

That is to say, I'm using whitenoise and it's not serving graphiql

My `INSTALLED_APPS` looks like this. How much does the ordering matter?

```
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django_elasticsearch_dsl',
    'webpack_loader',
    ...
    # .... my own apps ...
    'debug_toolbar',
    'django_extensions',
    'flags',
    'rest_framework',
    'django_saml2_auth',
    'revproxy',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.core',
    'wagtail.contrib.modeladmin',
    'wagtailmenus',
    'taggit_serializer',
    'taggit_templatetags2',
    'modelcluster',
    'adminsortable2',
    'taggit',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'django.contrib.admindocs',
]
```
