### ISSUE TITLE
Bundle external JavaScript sources for GraphiQL

### ISSUE THREAD

**Issue by tvogels** [graphql-python/graphene-django#69]
Currently, the GraphiQL interface served with graphene-django cannot be used without an internet connection because it relies on javascript files served from a CDN. This can be problematic in some dev environments. I would suggest bundling these files instead to ensure graphiql can also be used offline.

**Comment by zbyte64** [comment]
This could make #498 obsolete

**Comment by eoinof** [comment]
For anyone who encounters this you can pretty easily specify a custom template file.
e.g. in your urls file

`GraphQLView.graphiql_template` = 'graphql/customGraphiQL.html

graph_urls = [
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
]
`
