### ISSUE TITLE
Found different types with the same name in the schema: ErrorType, ErrorType.

### ISSUE THREAD

**Issue by defiler** [graphql-python/graphene-django#692]
After updating from 2.1.3 to 2.1.6 this error shows up.
It seems that importing `ErrorType` from `graphene_django/forms/types.py` is obsolete now, as `ErrorType` now lives in `graphene_django/types.py`
This module should be removed or it just needs to import `ErrorType` from new location for backwards compatibility?

**Comment by jkimbo** [comment]
@defiler good find! I'll create a PR to fix this.

**Comment by jkimbo** [comment]
https://github.com/graphql-python/graphene-django/pull/701
