### ISSUE TITLE
How to do filter or search on JSONField()?

### ISSUE THREAD

**Issue by elcolie** [graphql-python/graphene-django#697]
The original is [here](https://stackoverflow.com/questions/56902395/need-guide-lines-or-hints-to-use-graphene-python-django-filters-query-on-js)

If you know the way how to do that please share

**Comment by zbyte64** [comment]
Relevant django-filter issues: https://github.com/carltongibson/django-filter/issues/583 https://github.com/carltongibson/django-filter/issues/426

You can do this by manually defining your own filter, example from the first issue:
```
MarkaMoto = django_filters.CharFilter(name='attributes', lookup_expr='MarkaMoto__value__contains')
```

But there are limitations like not supporting `icontains` or querying arrays.

**Comment by saritaegon** [comment]
Thank you very much @zbyte64 I though `graphene-django` has feature to do a generic filter for this problem since it has been around for a year already.

**Comment by elcolie** [comment]
Thank you very much @zbyte64 I though `graphene-django` has feature to do a generic filter for this problem since it has been around for a year already.
