### ISSUE TITLE
Exception thrown in test

### ISSUE THREAD

**Issue by dan-klasson** [graphql-python/graphene-django#704]
I'm trying to test that a `PermissionDenied` exception is being thrown. The problem is that `assertRaises` does not catch the exception, but worse than that each test comes with this test output:

	Creating test database for alias 'default'...
	System check identified no issues (0 silenced).
	Traceback (most recent call last):
	  File "/home/dan/game/venv/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
	    executor(resolve, reject)
	  File "/home/dan/game/venv/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
	    return resolve(f(*args, **kwargs))
	  File "/home/dan/game/venv/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
	    return next(*args, **kwargs)
	  File "/home/dan/game/venv/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 31, in wrapper
	    return func(info.context, *args, **kwargs)
	  File "/home/dan/game/venv/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 43, in wrapper
	    raise exceptions.PermissionDenied()
	graphql.error.located_error.GraphQLLocatedError: You do not have permission to perform this action

How can I stop Graphene from printing this when I run my tests?

**Comment by jkimbo** [comment]
@dan-klasson Graphene captures all exceptions thrown inside a query execution and adds them to the `errors attribute on the response. All graphql servers do this so that they can return partial data. Relevant part of the spec: https://graphql.github.io/graphql-spec/June2018/#sec-Errors-and-Non-Nullability

More information on how to handle errors in graphql servers: https://artsy.github.io/blog/2018/10/19/where-art-thou-my-error/

**Comment by nextmat** [comment]
For anyone else coming across this, the provided [GraphQLTestCase](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/utils/testing.py) and its `assertResponseHasErrors` are a good start for testing errors in responses. 

If you want to confirm a specific error response you do need to parse the payload and assert against its contents.

Something I'm a little confused about though - is raising `Exception` or `GraphQLError` the preferred way to introduce errors into the response or is there a better way? If exceptions are the blessed path, how do you remove the noise from test output?

**Comment by nextmat** [comment]
When using exceptions to return errors in response, the current answer appears to be selective filtering from log output.

[This filter](https://github.com/m3nu) allows you to silence `GraphQLError` and descendants during tests. Other exception types will still be logged.

**Comment by ayding11** [comment]
> For anyone else coming across this, the provided [GraphQLTestCase](https://github.com/graphql-python/graphene-django/blob/master/graphene_django/utils/testing.py) and its `assertResponseHasErrors` are a good start for testing errors in responses.
> 
> If you want to confirm a specific error response you do need to parse the payload and assert against its contents.
> 
> Something I'm a little confused about though - is raising `Exception` or `GraphQLError` the preferred way to introduce errors into the response or is there a better way? If exceptions are the blessed path, how do you remove the noise from test output?

I am also wondering how to get rid of the noise. Any solutions? Thanks.

**Comment by mohibullah70** [comment]
> @dan-klasson Graphene captures all exceptions thrown inside a query execution and adds them to the `errors attribute on the response. All graphql servers do this so that they can return partial data. Relevant part of the spec: https://graphql.github.io/graphql-spec/June2018/#sec-Errors-and-Non-Nullability
> 
> More information on how to handle errors in graphql servers: https://artsy.github.io/blog/2018/10/19/where-art-thou-my-error/

But how to stop GraphQLLocatedError from showing up in test print output?

**Comment by jkimbo** [comment]
@mohibullah70 I'm no longer a maintainer of Graphene but a useful feature that you could create a PR for is the ability to customise how errors are logged in Graphene. Strawberry has something similar that could be used as inspiration: https://strawberry.rocks/docs/types/schema#handling-execution-errors
