### ISSUE TITLE
Start warning if `fields` or `exclude` are not defined on `DjangoObjectType`

### ISSUE THREAD

**Issue by jkimbo** [graphql-python/graphene-django#710]
So that model fields aren't accidentally exposed through DjangoObjectType I propose that we start warning if either `fields` or `exclude` aren't defined with the intention to error completely in the future. This would also align the API more with Django Rest Framework which hopefully makes it more familiar to most developers.

**Comment by radekwlsk** [comment]
@jkimbo is anyone working on it? If not I would be happy to help and prepare PR for this issue.

**Comment by jkimbo** [comment]
@radekwlsk if you have the time that would be great! I don't think anyone is working on it at the moment.

**Comment by radekwlsk** [comment]
> @radekwlsk if you have the time that would be great! I don't think anyone is working on it at the moment.

Great. I will start working on it tomorrow. You can assign me to the issue, @jkimbo .

**Comment by radekwlsk** [comment]
@jkimbo You can close this.

**Comment by jkimbo** [comment]
Thanks @radekwlsk
