### ISSUE TITLE
Make required False in django graphene with relay

### ISSUE THREAD

**Issue by robertpro** [graphql-python/graphene-django#712]
I am sorry for raising an issue here, but I am not sure if you have any support channel.

I want to make required=False on my Node, so I can get the node by the logged in user instead of the user ID, but I can't find how to do it, Could anyone please help?

```python
class Customer(models.Model):
    user = models.OneToOneField(User)

class CustomerNode(DjangoObjectType):
    class Meta:
        model = Customer
        interfaces = (graphene.relay.Node,)

    @classmethod
    @login_required
    def get_queryset(cls, queryset, info):  # This should work
        return queryset.get(user=info.context.user)

class Query(graphene.ObjectType):
    customer = graphene.relay.Node.Field(CustomerNode)
    all_customers = DjangoFilterConnectionField(CustomerNode)
```

```graphql
query getCustomer {
  customer(id: "XXX") {  # I don't want to pass this parameter!
    id
  }
}
```

This is the error if I don't pass any parameter:

```json
"message": "Field \"customer\" argument \"id\" of type \"ID!\" is required but not provided."
```

**Comment by dan-klasson** [comment]
I would return the user in the resolve method.

**Comment by robertpro** [comment]
@dan-klasson I need Customer object, not user,

As a work around I am doing this:

```gql
query getCustomer {
  allCustomers {
    edges {
      node {
        id
      }
    }
  }
}
```

```python
class Query(graphene.ObjectType):
    customer = graphene.relay.Node.Field(CustomerNode)
    all_customers = DjangoFilterConnectionField(CustomerNode)

    @login_required
    def resolve_all_customers(self, info, **kwargs):
        return Customer.objects.filter(user=info.context.user)  # This will return a list with only one object
```

But I don't think this is the best way to do it, since I need to iterate or hard-code the index to get the information

**Comment by dan-klasson** [comment]
You can do something like this but with Customer instead:

	import graphene
	class FooNode(ObjectType):
	    name = graphene.String()

	class Query(ObjectType):

	    foo = graphene.Field(FooNode)

	    def resolve_foo(self, info, **kwargs):
		return User.objects.first()

**Comment by robertpro** [comment]
@dan-klasson yeah, I think you are right, maybe I was trying to do it the wrong way, will close this issue. Thanks!

**Comment by robertpro** [comment]
BTW, if you have any support channel (mailing list, reddit, slack, discord), please let me know!

**Comment by chrisfitkin** [comment]
I'm able to solve this by changing
`customer = graphene.relay.Node.Field(CustomerNode)`
to
`customer = graphene.Field(CustomerNode)`

and adding a `resolve_customer` resolver

`class Query(graphene.ObjectType):
    customer = graphene.Field(UserNode)

    def resolve_customer(self, info):
        user = info.context.user
        if user.is_anonymous:
            raise Exception('Not logged in!')

        customer = Customer.objects.filter(user=user).first()

        return customer
`

I'm not sure what I'm giving up by returning a `grapheneField` instead of a `relay.Node` field.  Anyone know?
