### ISSUE TITLE
Graphene adds a prefix _A before each numeric value

### ISSUE THREAD

**Issue by Lepiloff** [graphql-python/graphene-django#715]
I'm using graphene-django version 2.4.0 with Django 2.2 and now I'm seeing a strange bug. Before each integer fields graphene add simbols _A. For example for models 

```
class Skill(models.Model):
    """Information about an employee's skills."""

    LEVELS = (
        ('basic', 'Basic'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
        ('expert', 'Expert'),
    )

    YEAR_CHOICES = [(r, r) for r in range(1, 11)]

    LAST_YEAR_CHOICES = [(r, r) for r in range(1980, datetime.datetime.now().year + 1)]

    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="employee_skills")
    technology = models.ForeignKey(Technology, on_delete=models.CASCADE)
    last_year = models.IntegerField(verbose_name='Last year using', choices=LAST_YEAR_CHOICES,
                                    default=datetime.datetime.now().year)
    year = models.IntegerField(verbose_name='Duration of technology use (years)', choices=YEAR_CHOICES, default=1)
    level = models.CharField("level", max_length=64, choices=LEVELS)
```
  the JSON output is like: 
`{{"employeeSkills": [{"lastYear": "A_2019", "year": "A_1", "level": "ADVANCED", "technology": {"name": "Python"}}, {"lastYear": "A_2019", "year": "A_2", "level": "INTERMEDIATE", "technology": {"name": "Kotlin"}}, {"lastYear": "A_2019", "year": "A_5", "level": "EXPERT", "technology": {"name": "Java"}}`

I think the problem is with choises, if I use DateField instead of IntegerFields, then everything works fine. But DateField is not a very convenient option in some cases.

**Comment by dan-klasson** [comment]
I think that's because GraphQL doesn't support integer `ENUM`.

**Comment by Lepiloff** [comment]
@dan-klasson Thank you, I didn't know that.

**Comment by ceelian** [comment]
As @dan-klasson stated it's because GraphQL doesn't support integer `ENUM`, just as a reference, here is the description of the GraphQL Enum which explains the motivation behind limiting it to string: https://graphql.org/learn/schema/#enumeration-types

and here is the spec which defines the allowed string as enum identifiers:  http://spec.graphql.org/June2018/#sec-Names
