### ISSUE TITLE
Model Form Mutation with custom model pk still require ID

### ISSUE THREAD

**Issue by ckristhoff** [graphql-python/graphene-django#716]
Hi everyone
I'm trying to implement a mutation with DjangoModelFormMutation. My Model declares a custom pk.

```python
class MyModel(models.Model):
  my_custom_pk = models.CharField(primary_key=True)
  ...
```

The mutation shows a required ID parameter, my_custom_pk also.
Can I use lookup_field to avoid ID field? or what can I do?

**Comment by dan-klasson** [comment]
As far as I know `DjangoModelFormMutation` takes the primary key by default. So just pass your PK as the `id` parameter.

**Comment by ckristhoff** [comment]
Thanks @dan-klasson 
obviously it is'not a problem, I just think it would be more consistent removing the custom pk and use only the ID

**Comment by dan-klasson** [comment]
Sorry I misread your question. `DjangoModelFormMutation` contains the following snippet of code:

        if "id" not in exclude_fields:
            input_fields["id"] = graphene.ID()

Maybe try to include `id` in `exclude_fields`. The drawback with that is that you can then not use the `fields` as far as I know. You could also subclass  `DjangoModelFormMutation` and override `__init_subclass_with_meta__`. Try it out and please report back.

**Comment by ckristhoff** [comment]
Thank again @dan-klasson 
your suggestions really works, but if I exclude id field my model form does not update my model instance.

**Comment by dan-klasson** [comment]
You should file a bug report regarding this then. Are you trying to use relay ids?

**Comment by ckristhoff** [comment]
Hi @dan-klasson 
yes, I do. My model based queries use relay interface, so I wanna consistency between queries and mutations.

**Comment by dan-klasson** [comment]
Why do you have `CharField` instead of `AutoField` on your PK?

**Comment by ulgens** [comment]
Currently, relay doesn't allow accessing objects anything except global ID. The same issue, not sure it's an issue but let's say inconvenience, exists on queries too. I don't have an exact solution for this particular case but i'm using this, for queries:

```python
class SlugNode(Node):
    @classmethod
    def Field(cls, *args, **kwargs):  # noqa: N802
        return SlugNodeField(cls, *args, **kwargs)

    @classmethod
    def node_resolver(cls, only_type, root, info, id=None, slug=None, slug_field="slug"):
        # TODO: slug_field should be overridable in Query
        if id and slug:
            raise ValueError("id and slug cannot be used together.")
        elif id:
            return cls.get_node_from_global_id(info, id, only_type=only_type)
        elif slug:
            model = only_type._meta.model
            try:
                return model.objects.get(**{slug_field: slug})
            except model.DoesNotExist:
                return None
        else:
            raise ValueError("id or slug is required.")
```
Please be aware of code is not in the best state i imagined 🙂
