### ISSUE TITLE
unresolved reference url

### ISSUE THREAD

**Issue by obitodarky** [graphql-python/graphene-django#717]
In [Readme.md](https://github.com/graphql-python/graphene-django/blob/master/README.md) As per the installation steps, under **Urls**, while adding the url pattern for graphql as mentioned below

```
urlpatterns = [
    # ...
    url(r'^graphql$', GraphQLView.as_view(graphiql=True)),
]
```

I got an error saying `unresolved reference url`

Should I use path instead?

**Screenshot**
![Screenshot 2019-07-23 at 12 46 45 PM](https://user-images.githubusercontent.com/21317964/61690891-f965ea80-ad47-11e9-86b8-a17de3412ba3.png)

**Comment by dan-klasson** [comment]
It's probably just complaining you haven't imported `url`. Use `path` if that is what your Django version supports. You should also get rid of `^` and `$` as well in that case.

**Comment by jkimbo** [comment]
Yep @dan-klasson is right, you need to import `url` from Django @obitodarkly

We should update the readme to use the new path syntax as well.
