### ISSUE TITLE
connection_class not being used in ManyToManyField connection.

### ISSUE THREAD

**Issue by jckw** [graphql-python/graphene-django#723]
I have a DjangoObjectType with the the `connection_class` set to a custom connection NonNullConnection, where NonNullConnection is some modified version of the normal graphene.Connection. Notably, NonNullConnection makes all the edges and nodes `required`.

```
class Post(DjangoObjectType):
    class Meta:
        model = PostModel
        interfaces = (Node,)
        filter_fields = () # only added because of deprecation warnings
        connection_class = NonNullConnection
```

Posts are connected to a user model via a ManyToManyField.

```
class User(models.Model):
    liked_posts = models.ManyToManyField("Post")
```

However, when looking at the schema on GraphiQL, the `likedPosts` clearly do not use the NonNullConnection specified as the connection class since the edges are not required.

Any help on this would be hugely appreciated, since it's a bit of a blocker for using Graphene Django with Typescript at the moment for me!

(Thanks for any help and this brilliant lib!!)

**Comment by jckw** [comment]
I think this might be because there's no handling of `connection_class` in the converter function.

https://github.com/graphql-python/graphene-django/blob/54cc6a4b13c18b8efebccaacd8ac8df93bf56949/graphene_django/converter.py#L174

**Comment by jckw** [comment]
Looking into it further, it seems that there are actually two Connections that are created called "JobConnection".

**Comment by jkimbo** [comment]
This sounds like a bug @jckw . Could you either create a PR with a failing test that shows this issue or post a complete code example that can reproduce it?

**Comment by jckw** [comment]
Sorry I've taken so long to get back on this. 

I think this came as a result of using both a ManyToMany field and a ForeignKey field to the same model. I'll try and put a PR with a failing test together tomorrow.

Just to clarify what I mean, I reckon something like this caused the bug:

```
class Publication(models.Model):
    posts = models.ManyToManyField("Post")


class Post(models.Model):
    jobs = models.ManyToManyField("jobs.Job")


class PublicationPost(models.Model):
    publication = models.ForeignKey("Publication", on_delete=models.CASCADE)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
```

(This was definitely a weird way to model the relationships 🙃)
