### ISSUE TITLE
Getting in touch with the community

### ISSUE THREAD

**Issue by nickwhite917** [graphql-python/graphene-django#724]
I've just started using graphene-django on a project and am blown away by how easy it's made development. Thank you all so much for building this amazing tool!

I'm interested in getting involved in the community and contributing to graphene. Can someone provide info on graphene's Slack, IRC, or Discord channels (or any other means of real-time communication)? I'm hoping to get ramped up quickly and will document the process for others after I've done so.

Thanks in advance, I'm looking forward to helping out,

Nick

**Comment by mvanlonden** [comment]
Thank you for your interest. I've invited you to our slack using your public github email

**Comment by nickwhite917** [comment]
Thank you!

**Comment by manesioz** [comment]
I, too, love using graphene and would love to contribute in any way possible. Could I get added to the slack as well? 
Thanks! 
Zack

**Comment by mvanlonden** [comment]
Added @manesioz 🚀

**Comment by thanhngvpt** [comment]
I'm caring about this, can you add me or public channel for registering. Thank you

**Comment by jkimbo** [comment]
@thanhngvpt you can use this link to join the slack group: https://join.slack.com/t/graphenetools/shared_invite/enQtOTE2MDQ1NTg4MDM1LTA4Nzk0MGU0NGEwNzUxZGNjNDQ4ZjAwNDJjMjY0OGE1ZDgxZTg4YjM2ZTc4MjE2ZTAzZjE2ZThhZTQzZTkyMmM
