### ISSUE TITLE
Setting a max limit on connections

### ISSUE THREAD

**Issue by ariannedee** [graphql-python/graphene-django#73]
GitHub's graphQL implementation requires a limit on queries, with a max limit of 30. How would I go about enforcing a max limit on every connection field in graphene?

**Comment by syrusakbary** [comment]
I think that's an interesting idea!

**Comment by jckw** [comment]
No update on this?

**Comment by ArnaudPel** [comment]
Looks like an implementation has been merged already: [#46a1dded](https://github.com/graphql-python/graphene-django/commit/46a1ddedd8af3a73bac5615355e0f92375420ee9)
