### ISSUE TITLE
Traceback is printed on exceptions raised from resolve_field methods

### ISSUE THREAD

**Issue by karlosss** [graphql-python/graphene-django#735]
Hi,

I am trying to implement an easy permission system on retrieving fields. So for each field, I implement such a method:

    def resolve_field(self, info, **kwargs):
        if not has_permission():
            raise PermissionError("Access Denied!")
        return self.field

Everything works fine, the user gets a nicely formatted errors filed back to the frontend. But when I look to my server console, I see this:

```
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Traceback (most recent call last):
...some irrelevant lines...
graphql.error.located_error.GraphQLLocatedError: Access Denied!

[06/Aug/2019 21:19:16] "POST /graphql/ HTTP/1.1" 200 427
```

No exception is thrown, my exception is perfectly caught in the system. But something somewhere translated the exception into `GraphQLLocatedError` and prints the traceback, which is super annoying, since I can't manage to find a way to get rid of it. Is that even possible?

Or, is my idea of implementing permissions (with raising an exception) wrong? 

Thanks!

**Comment by dan-klasson** [comment]
I have the same problem in my tests. I've put it on the back burner for now. I was thinking maybe better to handle that validation in the serializer instead.

**Comment by dan-klasson** [comment]
I'm doing something like this now:

```py
    def mutate_and_get_payload(cls, root, info, **input):

        kwargs = cls.get_serializer_kwargs(root, info, **input)
        serializer = cls._meta.serializer_class(**kwargs)

        if serializer.is_valid() and not error:

            kwargs = {}
            for f, field in serializer.fields.items():
                kwargs[f] = field.get_attribute(obj)

            return cls(errors=None, **kwargs)

        else:

            from rest_framework.exceptions import ValidationError, ErrorDetail

            asdf = {'non_field_errors': [ErrorDetail(string='bohoo', code='parse_error')]}
            if error:
                errors = [
                    ErrorType(field=key, messages=value)
                    for key, value in asdf.items()
                ]
            else:
                errors = [
                    ErrorType(field=key, messages=value)
                    for key, value in serializer.errors.items()
                ]

            return cls(errors=errors)
`

**Comment by tlinhart** [comment]
Exceptions raised in your resolvers get caught and wrapped in `GraphQLLocatedError`, look in the [code](https://github.com/graphql-python/graphql-core/blob/4e739957aa80f46b12acaf74b9b3e88f5942139f/graphql/execution/executor.py#L461). If you look at the [`report_error`](https://github.com/graphql-python/graphql-core/blob/4e739957aa80f46b12acaf74b9b3e88f5942139f/graphql/execution/utils.py#L150) method, you'll see that the exception together with traceback is logged using the `graphql.execution.utils` logger. Thus, you should be able to suppress the tracebacks in the log by silencing this logger.

**Comment by karlosss** [comment]
@tlinhart I am not sure if I don't accidentally silence something I don't want to, but it is definitely a good workaround. This one line of code

```python
import logging
logging.getLogger("graphql.execution.utils").setLevel(logging.CRITICAL)
```

does it. Thanks a lot!
