### ISSUE TITLE
DjangoFilterConnectionField with DataLoader ignoring filter_fields

### ISSUE THREAD

**Issue by cmaruan** [graphql-python/graphene-django#738]
I started to follow [this tutorial](https://apirobot.me/posts/django-graphql-solving-n-1-problem-using-dataloaders) about avoiding the N+1 through dataloaders, which works very well.
But all my fields are `DjangoFilterConnectionField` and to benefit from DataLoader, I had to write a costum resolver to batch my queries into one database hit. 

By doing that, I lost the possibility to filter by using `filter_fields` in my DjangoObjectType. 

Here is what I have done so far:

```python
# types.py
class ClientServiceType(DjangoObjectType):
    class Meta:
        model = ClientService
        filter_fields = {
            'costcenter': ['exact'],
            'created_at': ['lte', 'gte'],
        }
        interfaces = (relay.Node, )
    ...
    def resolve_costcenter(root, info, **kwargs):
        return info.context.fetch_costcenter_by_id.load(root.costcenter_id)
```

`costcenter` is a ForeignKey to other model I have. 

```python
#loaders.py

class CostCenterByIdLoader(DataLoader):
    def batch_load_fn(self, costcenter_ids):
        """
        Fetch from database all CostCenters from id list
        """
        costcenters = {}

        for cc in CostCenter.objects.filter(id__in=costcenter_ids).iterator():
            costcenters[cc.id] = cc

        return Promise.resolve([costcenters.get(cc_id) for cc_id in costcenter_ids])
```
The loader is exposed by the method  `fetch_costcenter_by_id` on my custom context. 

I went through all the documentation and didn't find any text or help on how to get these filter arguments passed on from the query. Maybe I am missing something obvious but I can't actually see what without some help. 

I hope I could explain it well. Thanks

[edit] What I managed to do was follow the path `info.operation.selection_set.selections[0].arguments` but I am not sure if that will always be the case.

**Comment by cmaruan** [comment]
The problem itself was on how I defined the filters and not on the framework. 
Solution was as simple as changing `costcenter` to `costcenter__name`.

**Comment by ngshiheng** [comment]
@cmaruan 
how did you manage to get it work with DjangoFilterConnectionField, I get the following error: 

`graphql.error.located_error.GraphQLLocatedError: 'Promise' object has no attribute 'model'.`
