### ISSUE TITLE
Adding Login Required Failed

### ISSUE THREAD

**Issue by Glingling** [graphql-python/graphene-django#741]
Hi,

I try to protect the acces to GraphQL API, so i implement this from the docs : [http://docs.graphene-python.org/projects/django/en/latest/authorization/#adding-login-required](url)
But when a go on the URL django redirect me to [http://127.0.0.1:8000/accounts/login/?next=/graphql/](url)

Havi I missing somethings ?

Thanks for your answer !

**Comment by zilehuda** [comment]
@Glingling - are you able to sort out this issue? I was also facing the same issue.
