### ISSUE TITLE
How to add description to fields?

### ISSUE THREAD

**Issue by Dawidpol** [graphql-python/graphene-django#743]
It is connected to #208, to [this comment](https://github.com/graphql-python/graphene-django/issues/208#issuecomment-326203930)
Let's say I have this model:
```python
class Country(models.Model):
    code = models.CharField(max_length=5, null=True)
    name = models.CharField(max_length=100, null=True)
```
and in schema i have
```python
class CountryNode(DjangoObjectType):
    class Meta:
        model = Country
        description = "This is a Country Node"
```
I can add a description for CountryNode itself, but how to do it for Country `code` and `name`?

**Comment by dan-klasson** [comment]
```py
code = models.CharField(max_length=5, null=True, help_text="This is a code field")
```

**Comment by liupengf12** [comment]
you can define a field with same name in your DjangoObjectType if you do not want update the model 😄 

```python
class CountryNode(DjangoObjectType):`
    class Meta:
        model = Country
        description = "This is a Country Node"

    code = graphene.String(description="This is a code field")
```

**Comment by jkimbo** [comment]
Closing this issue @Dawidpol because @dan-klasson and @liupengf12 have provided some solutions to the problem.
