### ISSUE TITLE
How to use throttling in django-graphene?

### ISSUE THREAD

**Issue by amiyatulu** [graphql-python/graphene-django#756]
The answer says to use django-throttle-requests

[Issue 676](https://github.com/graphql-python/graphene-django/issues/676)

But how to use it, it gives the following error:

This the error with django-throttle-requests
`'ResolveInfo' object has no attribute 'META'`

for the code:

```
from django.utils.decorators import method_decorator
from throttle.decorators import throttle

class CreatePageView(graphene.Mutation):
    pageview = graphene.Field(PageViewType)
    class Arguments:
        subscriptionkey = graphene.String(required=True)

    @method_decorator(throttle(zone='default'))
    def mutate(self, info, subscriptionkey):
        pv = PageView(subscriptionkey=subscriptionkey)
        pv.save()
        return CreatePageView(pageview=pv)

```

**Comment by zbyte64** [comment]
`django-throttle-requests` works at the view level, you would likely apply it in your `urls.py` where you expose the graphql view.
