### ISSUE TITLE
Examples on adding calculated fields

### ISSUE THREAD

**Issue by skorokithakis** [graphql-python/graphene-django#76]
Exposing fields that are in the db/model works fine, but what about calculated fields? For example, if I want to expose a field called `Author.book_count` that will obviously not be queriable or editable, how can I do that?

**Comment by Jufik** [comment]
@skorokithakis checkout issue this issue:
https://github.com/graphql-python/graphene/issues/101

Import graphene and do:
```vote_count = graphene.Int(source='vote_count')```

'vote_count' is my property

**Comment by skorokithakis** [comment]
Ah, thanks! It would be great if this was in the docs.

**Comment by hungnv132** [comment]
How to add a new field that its type is a list?

**Comment by paymog** [comment]
How do I resolve a django object along with an extra, calculated field like below during a query?

```python
class ProjectType(DjangoObjectType):
    class Meta:
        model = Project

    extra_field = graphene.String()


class Query(ObjectType):
    project = graphene.Field(ProjectType,
                             name=graphene.String())

    def resolve_project(self, info, name):

        if id is not None:
            return Project.objects.get(pk=id) # how do I populate `extra_field` here?


        return None
```

**Comment by mvanlonden** [comment]
@paymog 
```
    def resolve_project(self, info, name):

        if id is not None:
            return Project.objects.get(pk=id) # how do I populate `extra_field` here?


        return None
```

**Comment by fescobar** [comment]
Small example:

**Brand** model
```sh
class Brand(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name
```

BrandNode
```sh
class BrandNode(DjangoObjectType):
    # extra field INT
    extra_field_real_id_plus_one = graphene.Int()

    def resolve_extra_field_real_id_plus_one(parent, info, **kwargs):
        value = parent.id + 1
        print(f'Real Id: {parent.id}')
        print(f'Id ++: {value}')
        return value

    class Meta:
        model = Brand
        filter_fields = {
            'name': ['icontains', 'exact']
        }
        interfaces = (relay.Node,)
```

`extra_field_real_id_plus_one ` is the extra field. You can get any value from the original model, exactly from the `parent` parameter. You can calculate or format whatever you want and just you need to return the value.
You can get the extra field calculated value in queries, mutations, etc.
