### ISSUE TITLE
It is possible to translate validation errors that graphene django provides?

### ISSUE THREAD

**Issue by claudio-evocorp** [graphql-python/graphene-django#764]
`{
  "errors": [
    {
      "message": "Authentication credentials were not provided",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": {
    "viewer": null
  }
}`

**Comment by zbyte64** [comment]
Yes, but that would be covered by django's own internationalization effort: https://docs.djangoproject.com/en/2.2/topics/i18n/

This error message for example is not from our own codebase, but as long as the originating codebase wraps their text with: `django.utils.translation.gettext` which is often imported as `_`.
