### ISSUE TITLE
Add support for GEOS API types-- PointField, PolygonField etc.

### ISSUE THREAD

**Issue by EverWinter23** [graphql-python/graphene-django#766]
Can we add support for fields offered by ``django.contrib.gis.geos``--  [GEOS](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/geos/). ``django-graphql-geojson`` package comes closest to solving the problem, however, the particular implementation has a major drawback that it converts the whole *model* into *GeoJSON*, which causes problems with external interfaces which are defined on *non-geometric* fields. (May also break internal ones.)

Converting *GEOS* fields into *GeoJSON* should more than sufficient for most use cases because it provides you with pre-built interfaces and filters on non-geometric types.

How would one go about adding support for serialization of these fields?  Having gone through the codebase-- adding them to ``converter.py`` coupled with ``tests.py`` should be sufficient or am I missing something?

**Comment by jkimbo** [comment]
@EverWinter23 did you get any further with this? What you are suggesting: "adding them to converter.py coupled with tests.py" should be all that is needed. Can you created a PR?

**Comment by EverWinter23** [comment]
@jkimbo I did, wrote this module [here](https://github.com/EverWinter23/rover). Will gladly submit a PR. I'm loving `graphene`; you and the community have done a great job. 

Off topic:
I'm having problems with authorization. Especially implementing something like `rbac`, in REST API, you could easily define roles, what methods are allowed[PUT PATCH GET POST], and who can access what.

Having trouble doing the same with graphene. I don't want to put everything in the resolvers. Is there something I could do, I've heard about `graphql-shield`, but thats for `nodejs`. Help would be appreciated.

I will submit the PR within next two weeks.

**Comment by ProjectCheshire** [comment]
https://github.com/flavors/django-graphql-jwt

And then set up the user passes test decorators, then have one for superadmin 
There's also a package for Geojson
https://github.com/flavors/django-graphql-geojson

**Comment by ProjectCheshire** [comment]
https://github.com/flavors/django-graphql-extensions/blob/master/README.rst

**Comment by EverWinter23** [comment]
@ProjectCheshire Thanks. That helps alot.

**Comment by jkimbo** [comment]
Looks like https://github.com/EverWinter23/graphene-gis solves this issue (thanks @EverWinter23 ). I've created a PR to add it to the documentation: #902
