### ISSUE TITLE
Support Django 3

### ISSUE THREAD

**Issue by Siecje** [graphql-python/graphene-django#771]
`from django.utils import six` has been removed in Django version 3.

https://github.com/graphql-python/graphene-django/blob/master/graphene_django/settings.py#L18

**Comment by zbyte64** [comment]
Dupe of #705

**Comment by jkimbo** [comment]
Not a dupe of #705 (because that is dealing with Graphene v3) but I think this was resolved in https://github.com/graphql-python/graphene-django/pull/793
