### ISSUE TITLE
Type included in interface only is not added to schema

### ISSUE THREAD

**Issue by jfulse** [graphql-python/graphene-django#773]
I have an interface type implemented by two concrete types

```
    class InterfaceType(graphene.Interface):
        id = graphene.ID(required=True)
        name = graphene.String(required=True)

    class Type1(graphene_django.types.DjangoObjectType):
        a_field = graphene.String(required=False)

        class Meta:
            model = Model1
            interfaces = (InterfaceType,)

    class Type2(graphene_django.types.DjangoObjectType):
        another_field = graphene.String(required=False)

        class Meta:
            model = Model2
            interfaces = (InterfaceType,)
```

This works as long as some query or mutation uses `Type1` and `Type2` directly. But in my case they are only used indirectly, through `InterfaceType`.

The problem is when I try to request `aField` or `anotherField` through inline fragments:

    query {
        interfaceQuery {
            id
            name
            ...on Type1 {
                aField
            }
            ...on Type2 {
                anotherField
            }
        }
    }

I get the error `"Unknown type "Type1". Perhaps you meant ..."`

It's like the types aren't added to the schema since they're not directly in use - but I still need them in order to query `aField` and `anotherField`.

Can you spot a mistake in the above?

**Comment by zbyte64** [comment]
Can you also paste your `interfaceQuery` definition as well?

**Comment by jfulse** [comment]
Answered here: https://stackoverflow.com/a/58522186/1540547
