### ISSUE TITLE
content-type is plain/text when using apollo fetchOptions no-cors

### ISSUE THREAD

**Issue by allen-munsch** [graphql-python/graphene-django#778]
What about servers that use cors and send an OPTIONS request? This doesn't seem to forward the options() to the django `View` class that `GraphQLView` inherits from, graphql might not handle `OPTIONS` requests, just wondering if django should?:

https://github.com/graphql-python/graphene-django/blob/b0cba398a1bacd9305c50e784b862785348fca2d/graphene_django/views.py#L118

Also.

Would there be an issue if "plain/text" was also handled here?

```
elif content_type in ["application/json", "plain/text"]:
```

https://github.com/graphql-python/graphene-django/blob/b0cba398a1bacd9305c50e784b862785348fca2d/graphene_django/views.py#L206

I tried using the apollo react library with `fetchOptions` because I was getting a `405 method not allowed`:

```
fetchOptions: {
  mode: 'no-cors',
},
```

but had an issue with the content-type : https://github.com/apollographql/apollo-link/issues/275

---

Or is it the case, cors should be configured as part of the middleware? 

Like here: https://stackoverflow.com/questions/35760943/how-can-i-enable-cors-on-django-rest-framework

Or, that the `GraphQLView` should be custom?

I could add a quick blurb in the documentation somewhere?

related: 

- https://github.com/graphql-python/graphene-django/issues/168
- https://github.com/graphql-python/graphene-django/issues/288

Edit: just found : https://github.com/graphql-python/graphene-django/wiki/CORS-CSRF

I had also confused `apollo-boost` with `apollo-client`. Switched to `apollo-client` and used the following for `graphene-django` ( no `crsf_exempt` on the django url and no cors middleware )

```
import { ApolloProvider } from "react-apollo";
import ApolloClient from 'apollo-client';
import { HttpLink} from 'apollo-link-http';
import {InMemoryCache as Cache} from "apollo-cache-inmemory";
import { ApolloLink } from 'apollo-link'

const uri = `http://127.0.0.1:8000/graphql`; // not localhost
const AuthLink = (operation, next) => {
  const token = window.csrf_token;

  operation.setContext(context => ({
    ...context,
    headers: {
      ...context.headers,
      "X-CSRFToken": token,
    },
  }));

  return next(operation);
};

const link = ApolloLink.from([
  AuthLink,
  new HttpLink({ uri }),
]);

const apollo = new ApolloClient({
  link,
  cache: new Cache().restore({}),
});
```

**Comment by jkimbo** [comment]
@allen-munsch I think `django-cors-headers` is probably the best solution in this case. Does that solve your issue?

I'd rather not expand the view to accept plain text as well as it should really be JSON.
