### ISSUE TITLE
Mutation Error: "mutate() takes 4 positional arguments but 5 were given"

### ISSUE THREAD

**Issue by lealhugui** [graphql-python/graphene-django#78]
I have the following schema:

```python
# app/schema.py
import graphene
from graphene import relay, AbstractType
from graphene_django import DjangoObjectType
from graphene_django.filter import DjangoFilterConnectionField

from .models import Person

class PersonNode(DjangoObjectType):

    class Meta:
        model = Person
        filter_fields = ["id", "first_name", "last_name"]
        interfaces = (relay.Node, )

class Query(AbstractType):
    all_person = DjangoFilterConnectionField(PersonNode)

class CreatePerson(graphene.Mutation):
    class Input:
        firstName = graphene.String()
        lastName = graphene.String()
    
    person = graphene.Field(PersonNode)
    ok = graphene.Boolean()

    @classmethod
    def mutate(cls, input, args, info):
        f_name = args.get('firstName')
        l_name = args.get('lastName')
        p = Person.objects.create(first_name=f_name, last_name=l_name)
        return CreatePerson(person=PersonNode(p), ok=True)

class MutationPerson(AbstractType):
    createPerson = CreatePerson.Field()

# .\schema.py
import graphene

import srv_engine.main.schema as main_schema


class Query(main_schema.Query, graphene.ObjectType):
    pass

class Mutation(main_schema.MutationPerson, graphene.ObjectType):
    pass

schema = graphene.Schema(query=Query, mutation=Mutation)
```

When i try to execute the mutation, with the following query:
```javascript
mutation{
  createPerson(firstName: "Foo", lastName: "Bar" ){
    ok,
    person{
      firstName
    }
  }
}
```
I get the following result:

```json
{
  "errors": [
    {
      "message": "mutate() takes 4 positional arguments but 5 were given",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ],
  "data": {
    "createPerson": null
  }
}
```

Any help would be good.

**Comment by blakegong** [comment]
You are mixing Relay Mutation with "pure" GraphQL Mutation. In your code, you used relay.Node as the interface of PersonNode, but you did not use relay.ClientIDMutation to write your Mutation.

The problem is, for graphene.Mutation, the mutation itself should be written as in https://github.com/graphql-python/graphene/blob/master/docs/types/mutations.rst, note that ```mutate``` method is a not a class method:

```python
class CreatePerson(graphene.Mutation):
    class Input:
        firstName = graphene.String()
        lastName = graphene.String()
    
    person = graphene.Field(lambda: PersonNode)
    ok = graphene.Boolean()

    def mutate(self, args, context, info):
        f_name = args.get('firstName')
        l_name = args.get('lastName')
        p = Person.objects.create(first_name=f_name, last_name=l_name)
        return CreatePerson(person=p, ok=True)
```

**Comment by lealhugui** [comment]
Wich approach is the right one? Defining the relay interface seems more
concise, but I couldn't find it anywhere in the docs. Is it missing in the
docs, or was I that completely missed this part? Can you give some example
on the implementation with relay.ClientIDMutation?

Em sex, 23 de dez de 2016 14:32, Yue Gong <notifications@github.com>
escreveu:

**Comment by blakegong** [comment]
It depends on whether you are using Relay as your front-end framework. If yes, then you have to. If not, then I guess you are using [Apollo](http://www.apollodata.com/)? Well, in that case, it depends on you. 

Using Relay means you need to comply your GraphQL server with [GraphQL Relay Spec](https://facebook.github.io/relay/docs/graphql-relay-specification.html). It means for example, expressing one-to-many relation like the following is illegal:

```
query {
  group {
    users {
      name
    }
  }
}
```

Instead, you should be doing:

```
query {
  group {
    users(first: 100) {
      edges {
        node {
          name
        }
      }
    }
  }
}
```

Relay queries comes with nice paginations as shown here and a bunch of other stuff, but totally up to you whether to use it.

I think by modifying the above code using example from https://github.com/graphql-python/graphene/blob/master/docs/relay/mutations.rst, it shouldn't be too hard. Just take note that as mentioned in https://facebook.github.io/relay/graphql/mutations.htm, all the input should be included in `input` field, which is already handled automatically by relay.ClientIDMutation. So your Mutation query should be like:

```
mutation{
  createPerson(input: { firstName: "Foo", lastName: "Bar" }) {
    ...
  }
}
```

**Comment by lealhugui** [comment]
Yes, I'll use Relay as front-end.
I just implemented the mutation subclassing "ClientIDMutation" (like in the exemple) and it worked like a charm!

Thank you @blakegong !
