### ISSUE TITLE
Slightly incorrect Travis pipeline

### ISSUE THREAD

**Issue by barseghyanartur** [graphql-python/graphene-django#782]
In current implementation, when testing a tagged commit, PyPI release would be triggered after the first success. This is incorrect, since what works on Python 3.5 might not work on Python 3.6 (not even talking about Python 2, which is the first one to be tested in the list).

Thus, I suggest to set ``fast_finish`` to ``false`` so that release attempt would be made only once after all checks are finished (all tests passed).

```yaml
# ...
matrix:
  fast_finish: false
# ...
```

Alternatively, if my proposal above isn't acceptable (for whatever reason), then I suggest to add ``skip_existing: true`` to the ``deploy`` pipeline. The reason: Travis would report failures even if tests pass when testing for the second time (and further on). Currently, once Python 2 tests pass, release is made, then testing on Python 3.5 starts, tests pass, but the final step fails, since package is already on the PyPI. With ``skip_existing: true`` that would no longer happen.

```yaml
# ...
deploy:
  skip_existing: true
  provider: pypi
# ...
```

Let me know if I shall submit a PR (please, mention which fix would be more appropriate/acceptable).

**Comment by jkimbo** [comment]
Good spot @barseghyanartur . I actually think the better solution is to split the travis pipeline into "jobs" like the graphene one is: https://github.com/graphql-python/graphene/blob/master/.travis.yml#L24-L41

If you can make a PR to that effect that would be very helpful!

**Comment by barseghyanartur** [comment]
@jkimbo:

Indeed, that's even a better approach. I'll prepare a PR.

**Comment by jkimbo** [comment]
@barseghyanartur I've created a PR for this: https://github.com/graphql-python/graphene-django/pull/837

**Comment by barseghyanartur** [comment]
Cool!
