### ISSUE TITLE
Post Request Fail When CSRF_USE_SESSIONS = True

### ISSUE THREAD

**Issue by Flavyoo** [graphql-python/graphene-django#786]
When the `CSRF_USE_SESSIONS` settings variable is set to `True` post requests can not be made as the request will be rejected. This is because the `CSRFTOKEN` is not provided, because it will not be stored in a cookie.

Django will end up giving this warning:  `Forbidden (CSRF token missing or incorrect.):`

Currently this issue can be prevented by passing the view to `csrf_exempt`

**Comment by jkimbo** [comment]
#826 has been merged and will be released shortly

**Comment by colonder** [comment]
Please, reopen as I still encounter this error.

**Comment by jkimbo** [comment]
@colonder have you wrapped the graphql view in the csrf exempt function?

**Comment by sanginovs** [comment]
https://stackoverflow.com/a/73156636
