### ISSUE TITLE
Handling aggregate objects

### ISSUE THREAD

**Issue by SpyTec** [graphql-python/graphene-django#787]
In my application right now I've been aggregating database entries  and serving them in a REST API. Though when it comes to graphene I've not had any luck getting aggregates to works. Any help would be thankful

Current code:
```py
aggregated_snapshots = DjangoFilterConnectionField(IssueSnapshotNode)

def resolve_aggregated_snapshots(self, info, **kwargs):
    return IssueSnapshot.objects.order_by() \
        .values('status', type=F('issue__type_name')) \
        .annotate(status_count=Count('status'))
```

Error message returned:
```
Merging 'QuerySet' classes must involve the same values in each case
```

**Comment by zbyte64** [comment]
Looks like issue #758

**Comment by SpyTec** [comment]
Probably. Before the latest update I also tried to do this, though at that time I got a different error I don't remember at the moment

**Comment by zbyte64** [comment]
After some digging, you might want to try replacing `values` with `only` or `defer`. PR #796 revealed how the two are treated differently and that values delivers dictionaries while graphene_django want's django instances.

**Comment by SpyTec** [comment]
Maybe this is just my inexperience, but from what I can see getting a field from a related model `issue__type_name` won't work with only() as it will only show you the `issue_id` field, not the `type_name`

**Comment by zbyte64** [comment]
Sounds like we might want the filtering functionality of `DjangoFilterConnectionField` but with the option to change the type. Might be able to subclass and override `node_type` as well as `type` ...

**Comment by SpyTec** [comment]
I'm not well into the library implementation, what does `node_type` and `type` represent and affect?

**Comment by zbyte64** [comment]
I believe `node_type` is the inner type that the connection field connects to, `type` adds wrappings, basically just `NotNull` with a type check which ensures we are connecting it to a django object type.

**Comment by SpyTec** [comment]
Yeah, this has been a bit over my head. Not been successful with aggregating based off of a relation of `issue__type_name`

**Comment by SpyTec** [comment]
Not had any success yet
