### ISSUE TITLE
Serializer mutation dosen't return many to many field in response with nested serializer

### ISSUE THREAD

**Issue by rdahal35** [graphql-python/graphene-django#788]
class EnergyDetailSerializer(serializers.ModelSerializer):

    address = SellerAddressSerializer()
    energy_source = EnergySourceSerializers()
    payment_method = PaymentMethodSerializer(many=True)

    class Meta:
        model = EnergyDetail
        exclude = ['seller']

    def create(self, validated_data, seller):
        energy = EnergyDetail.objects.all().first()
        return energy

class EnergyDetailMutation(SerializerMutation):

    class Meta:
        serializer_class = EnergyDetailSerializer
        model_operations = ['create', 'update']

    @classmethod
    def perform_mutate(cls, serializer, info):
        if not info.context.user.is_authenticated:
            raise Exception('Authentication credentials were not provided')
        obj = serializer.create(serializer.validated_data,
                                info.context.user.seller)
        kwargs = {}
        for f, field in serializer.fields.items():
            if not field.write_only:
                kwargs[f] = field.get_attribute(obj)

        return cls(errors=None, **kwargs)

AssertionError: User Error: expected iterable, but did not find one for field EnergyDetailMutationPayload.paymentMethod.

I think it is trying to find enegry.payment_method and it does not return iterable values.
Because to get objects of many to many field we need to call .all() method

**Comment by ktian94** [comment]
Ran into this today too. What was your workaround?

**Comment by Tineshnehete** [comment]
Hi there , I also face same issue but its fixed it now  .

**Comment by Tineshnehete** [comment]
Hey there i also had same issue but its not fixed .
##sloution 
The err is accurring code details field is returning mamy many relation ships manager class so to solve overide class with resolve method for M2M field

**Comment by Tineshnehete** [comment]
Hey there i also had same issue but its not fixed .
### sloution
The err is accurring code details field is returning mamy many relation ships manager class so to solve overide class with resolve method for M2M field

```
class ModelSerialiser(serializers.ModelSerializer):
    fieldn = FieldSerialiser(many=True, required=False)
    class Meta:
        model = Model
        fields = "__all__"        
   # your methods create , update
```
Mutation 
```
class ModelMutation(SerializerMutation):
    class Meta:
        serializer_class = ModelSerialiser
        model_operations = ['create', 'update']
        lookup_field = "id"
    
    def resolve_fieldn(self , info ,  **kwargs):
        return  self.fieldn.all() if self.fieldn is not None else None
```
