### ISSUE TITLE
Add to convert_form_field single dispatch

### ISSUE THREAD

**Issue by AceFire6** [graphql-python/graphene-django#806]
Is it possible to add more resolvers to the `convert_form_field` single dispatch function?

I want to add a custom resolver to automatically be used to convert GraphQL IDs to database compatible integer IDs:

```python
@convert_form_field.register(ModelChoiceField)
def convert_form_field_to_id(field):
    return ConvertedID(required=field.required)
```

Is something like this possible? Where would I put the initialisation of it so that it happens before all the mappings are done for the forms?

Thanks

**Comment by zbyte64** [comment]
Typically I create a file like `schema_fields.py` to host that logic and have my `schema.py` import, that was it happens before the ObjectTypes are even defined.

**Comment by pfcodes** [comment]
> Typically I create a file like `schema_fields.py` to host that logic and have my `schemas.py` import, that way it happens before the ObjectTypes are even defined.

this helped me out, thanks
