### ISSUE TITLE
Django will drop `django.utils.six` in 3.0 

### ISSUE THREAD

**Issue by Rocamonde** [graphql-python/graphene-django#814]
`django.utils.six` has been removed in Django 3.0rc1. Django users running version 3.0 won't be able to run `graphene-django`. (`settings.py` line 18: `from django.utils import six`)

Either we depend directly on `six` or we drop Python 2 compatibility and all the Django versions that still support it.

**Comment by Rocamonde** [comment]
My bad, apparently this has already been fixed in `master` branch. Could someone indicate in what version this change will be included and when will this version be released?

Thank you

**Comment by jkimbo** [comment]
@Rocamonde just released v2.7.0 which resolves this issue: https://github.com/graphql-python/graphene-django/releases/tag/v2.7.0
