### ISSUE TITLE
@BossGrand  I have a similar issue, it errors out this `graphql.error.located_error.GraphQLLocatedError: 'ImageFieldFile' object has no attribute 'decode'`

### ISSUE THREAD

**Issue by udemezue01** [graphql-python/graphene-django#818]
@BossGrand  I have a similar issue, it errors out this `graphql.error.located_error.GraphQLLocatedError: 'ImageFieldFile' object has no attribute 'decode'`

_Originally posted by @horiyomi in https://github.com/graphql-python/graphene-django/issues/769#issuecomment-560012948_

**Comment by slam24** [comment]
I tried with this code and work for me.
`class UserType(DjangoObjectType):
    class Meta:
        model = User

    extra_field = graphene.String()

    def resolve_extra_field(self, info):
        return info.context.build_absolute_uri(self.profile.url)`

**Comment by udemezue01** [comment]
oh good then the full code would be ???

**Comment by udemezue01** [comment]
class ProfileType(DjangoObjectType):
	class Meta:
		model  = Profile
                extra_field = graphene.String()
        def resolve_extra_field(self, info):
                  return info.context.build_absolute_uri(self.profile.url)

**Comment by slam24** [comment]
class UserType(DjangoObjectType):
    class Meta:
        model = User
        exclude = ('profile', 'password')

  ```
  image = graphene.String()

    def resolve_image(self, info):
        return info.context.build_absolute_uri(self.profile.url)
```

**Comment by horiyomi** [comment]
@slam24 @udemezue01 I have Tried

**Comment by horiyomi** [comment]
It works now, i had a typo. Thanks

**Comment by slam24** [comment]
@udemezue01 Close the issues please.
