### ISSUE TITLE
Return type of SerializerMutation

### ISSUE THREAD

**Issue by oaosman84** [graphql-python/graphene-django#819]
It looks like the implementation of `SerializerMutation` takes the fields from the Serializer and adds them directly to the output type of the GraphQL Mutation. For instance, if I have a mutation that affects a `User` model, and I have a SerializerMutation from that, it will have output type of `UserMutationPayload` and the fields on `User` (e.g. name, id, etc) will be added directly to `UserMutationPayload`.

This is a bit different than most mutation return types (for instance, `DjangoModelFormMutation` would have a `user` object under `UserMutationPayload` with type `User`). It also breaks a bunch of caching behavior for clients like Apollo that depend on having the right `__typename` for objects that are returned.

Fixing this would require a breaking change to `SerializerMutation`, which I'd be open to implementing (we'd prob reuse a bunch of logic from `DjangoModelFormMutation`), so I don't know how people feel about that.

**Comment by mcabrams** [comment]
I would definitely like the described functionality.  It also makes the PayloadTypes clearer (for example, using @oaosman84 's example, currently the fields on `User` in this example would all be marked as optional) - if there's a `user` object under `UserMutationPayload` with type `User` the fields can be marked required according to the actual model fields (i.e. via `null=True` checks).

**Comment by mcabrams** [comment]
In addition, presumably this would not have to be breaking change if a new Meta property was added dictating the style for `UserMutationPayload`
