### ISSUE TITLE
Settings for unittests missing in package

### ISSUE THREAD

**Issue by crazyscientist** [graphql-python/graphene-django#820]
Hi there,

I'm trying to build an RPM package on https://build.opensuse.org based on the package at PyPI and run the unittests during the build process. But I kind of miss a settings module I can use.

Would you mind including e.g. `django_test_settings.py` in the next release?

**Comment by jkimbo** [comment]
Sounds reasonable though I'm not that familiar with the pip deploy process. @crazyscientist what would I need to change in the setup.py to get it to include that file?

**Comment by crazyscientist** [comment]
@jkimbo, I would do the following:

* Move `django_test_settings.py` to the `test` directory 
* Remove the exclusion statement for the tests subpackage
* Adjust the MANIFEST in case the tests rely on data files

Would you prefer me submitting a PR?

**Comment by jkimbo** [comment]
@crazyscientist sorry for the delay: yes a PR would be great thanks!

**Comment by jkimbo** [comment]
@crazyscientist do you have time to make that PR?

**Comment by crazyscientist** [comment]
> @crazyscientist do you have time to make that PR?

@jkimbo, sorry, I was stuck with another project. I might be able to get around to this; maybe next week?

**Comment by ulgens** [comment]
@crazyscientist Any hope there? :slightly_smiling_face:

**Comment by crazyscientist** [comment]
> Any hope there? :slightly_smiling_face:

@ulgens Finally, inspiration struck. I hope the changes I propose in my PR will work for you as well :crossed_fingers:
