### ISSUE TITLE
How can we solve round trip (N+1) problem with Relay & filter ?

### ISSUE THREAD

**Issue by zayazayazaya** [graphql-python/graphene-django#831]

**Comment by jkimbo** [comment]
@zayazayazaya you'll need to use something like Dataloader: https://docs.graphene-python.org/en/latest/execution/dataloader/ 

Using it in the `get_queryset` method should prevent N+1 queries

**Comment by zayazayazaya** [comment]
Can you please provide me example that is using data loader in the get_queryset? I didn't find doc or example to use dataloader in the get_queryset method..

**Comment by zayazayazaya** [comment]
@jkimbo  here
