### ISSUE TITLE
How can I integrate with GraphiQL explorer and GraphQL Voyager?

### ISSUE THREAD

**Issue by zayazayazaya** [graphql-python/graphene-django#834]

**Comment by jkimbo** [comment]
@zayazayazaya graphiql is available automatically as long as you pass `graphiql=True` to the `GraphQLView.as_view` call: http://docs.graphene-python.org/projects/django/en/latest/installation/#installation

To add GraphQL Voyager you will have to set it up in your project and point it to your graphql endpoint. Looks like there are instructions on how to do that in the project README: https://github.com/APIs-guru/graphql-voyager#using-pre-bundled-version

**Comment by jonocodes** [comment]
I'm thinking OP was asking more along the lines of this
https://github.com/graphql-python/graphene/issues/998

**Comment by avinoamsn** [comment]
> @zayazayazaya graphiql is available automatically as long as you pass `graphiql=True` to the `GraphQLView.as_view` call: http://docs.graphene-python.org/projects/django/en/latest/installation/#installation

@jkimbo This is not an answer to OP's question. OP is asking about adding `graphiql-explorer` to the provided GraphiQL interface (like @jonocodes said), NOT about enabling GraphiQL itself. https://github.com/graphql-python/graphene-django/issues/1204 seems to have a decent manual solution, borrowed from [strawberry](https://github.com/strawberry-graphql/strawberry).

**Comment by jkimbo** [comment]
@avinoamsn alright I must have misread the question. It wasn't intentional 🙂

Anyway the right answer is to override the default template to include the code necessary to make graphiql-explorer work as you rightly point out.
