### ISSUE TITLE
Handling database transactions

### ISSUE THREAD

**Issue by brucedesa** [graphql-python/graphene-django#835]
I noticed that graphene-django doesn't handle database transactions. I believe this is a issue that people should know or be careful about.

The same logic of DRF could be implemented as in the lines below that run in the dispatch method.

https://github.com/encode/django-rest-framework/blob/d985c7cbb999b2bc18a109249c583e91f4c27aec/rest_framework/views.py#L65-L102

Basically on one exception runs:

```python
atomic_requests = settings.get('ATOMIC_REQUESTS', False)
if atomic_requests and connection.in_atomic_block:
   transaction.set_rollback(True)
````

In implementing this in graphene-django as we do not have the exception could run the rollback in the error checking of the execution result as in line 171.

https://github.com/graphql-python/graphene-django/blob/968002f1554e3a7a1c0617682be64b67823b2581/graphene_django/views.py#L167-L190

What do you think about this implementation?

**Comment by jkimbo** [comment]
Wouldn’t it mean that if part of the query/mutation raised an exception then every database change would be rolled back? Also wouldn’t the whole execution need to be wrapped in a transaction atomic block as well?

**Comment by brucedesa** [comment]
As good practice all requests are within an atomic block this is Django's default behavior.

In case of performance Django has utilities to run mutations without atomicity.

But since i use ATOMIC_REQUESTS=True, and the exceptions are not raised up, graphene-django does not care to make the request atomic and rollback on failure.

**Comment by jkimbo** [comment]
Ok fair enough, it seems like a good addition to the library. Your suggestion on where to put the transaction rollback is correct. Could you create a PR that adds the rollback under a settings option?

**Comment by ace-han** [comment]
Any progress on this issue or PR?

**Comment by ace-han** [comment]
Hello, any progress on this issue or PR?

**Comment by iorlandini** [comment]
I was faced with an issue similar to the one described in this issue and I created the PR https://github.com/graphql-python/graphene-django/pull/1039 to solve both use cases.

**Comment by iorlandini** [comment]
@jkimbo, @ulgens, @ace-han and @brucedesa I was faced with an issue similar to the one described in this issue and I created the PR #1039 to solve both use cases.

**Comment by overide** [comment]
@jkimbo I tried wrapping `mutate` method in Django's `transaction.atomic` decorator and it worked. Why can't we use it ? Just curious

```python
@classmethod
@transaction.atomic
def mutate(cls, root, info, **kwargs):
    # do something
```

**Comment by iorlandini** [comment]
> @jkimbo I tried wrapping `mutate` method in Django's `transaction.atomic` decorator and it worked. Why can't we use it ? Just curious
> 
> ```python
> @classmethod
> @transaction.atomic
> def mutate(cls, root, info, **kwargs):
>     # do something
> ```

You can use it. This PR is about making **graphql-python** works as Django is expected when turning on the settings `ATOMIC_TRANSACTION` https://docs.djangoproject.com/en/3.1/topics/db/transactions/#tying-transactions-to-http-requests

**Comment by overide** [comment]
> > @jkimbo I tried wrapping `mutate` method in Django's `transaction.atomic` decorator and it worked. Why can't we use it ? Just curious
> > ```python
> > @classmethod
> > @transaction.atomic
> > def mutate(cls, root, info, **kwargs):
> >     # do something
> > ```
> 
> You can use it. The PR #1039 is about making **graphql-python** works as Django is expected when turning on the settings `ATOMIC_TRANSACTION` https://docs.djangoproject.com/en/3.1/topics/db/transactions/#tying-transactions-to-http-requests

Got it, thanks a lot!
