### ISSUE TITLE
v2.8.0 not compatible with Django 3.0.2 regarding six

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [graphql-python/graphene-django#845]
I upgraded Django and graphene django but when I make a request I get this error 
```
Could not import 'fieldrecords.schema.schema' for Graphene setting 'SCHEMA'. ImportError: cannot import name 'six'.
```

**Comment by jkimbo** [comment]
@a-c-sreedhar-reddy can you post the full output of `pip freeze`? six is a dependency for graphene Django so it should definitely be installed.

**Comment by a-c-sreedhar-reddy** [comment]
pip3 freeze 
```
aniso8601==7.0.0
apturl==0.5.2
asgiref==3.2.3
asn1crypto==0.24.0
Babel==2.7.0
Brlapi==0.6.6
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
defer==1.0.6
distro-info===0.18ubuntu0.18.04.1
Django==3.0.2
django-cors-headers==3.2.0
django-graphql-jwt==0.2.2
django-phonenumber-field==3.0.1
djangorestframework==3.10.3
djangorestframework-simplejwt==4.3.0
graphene==2.1.8
graphene-django==2.8.0
graphql-core==2.2.1
graphql-relay==2.0.0
httplib2==0.9.2
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.0
netifaces==0.10.4
oauth==1.0.1
olefile==0.45.1
pexpect==4.2.1
phonenumbers==8.10.23
Pillow==5.1.0
promise==2.2.1
protobuf==3.0.0
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
pygobject==3.26.1
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyRFC3339==1.0
pyserial==3.4
python-apt==1.6.4
python-dateutil==2.6.1
python-debian==0.1.32
pytz==2019.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-unixsocket==0.1.5
Rx==1.6.1
SecretStorage==2.3.1
simplejson==3.13.2
singledispatch==3.4.0.3
six==1.13.0
sqlparse==0.3.0
ssh-import-id==5.7
system-service==0.3
systemd-python==234
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
usb-creator==0.3.3
wadllib==1.3.2
xkit==0.0.0
zope.interface==4.3.2
```
requirements.txt
```
aniso8601==7.0.0
Babel==2.7.0
Django==3.0.2
django-cors-headers==3.2.0
django-graphql-jwt==0.2.2
django-phonenumber-field==3.0.1
djangorestframework==3.10.3
djangorestframework-simplejwt==4.3.0
graphene==2.1.8
graphene-django==2.8.0
graphql-core==2.2.1
graphql-relay==2.0.0
phonenumbers==8.10.23
promise==2.2.1
PyJWT==1.7.1
pytz==2019.3
Rx==1.6.1
singledispatch==3.4.0.3
six==1.13.0
sqlparse==0.3.0
```

**Comment by dvf** [comment]
Django 3.0 [removed a bunch of Python 2 compatibility APIs](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) in lieu of Python 2 being deprecated, so it looks like we'll have to remove reliance on these APIs in graphene-django, probably with a major version bump.

Happy to help with this if there aren't any outstanding PRs already.

**Comment by Miraliu** [comment]
Try upgrade django-graphql-jwt to 0.3.0. There seems to be an import of django.utils.six in the older version of that package. 
My graphene-django==2.8.0 is working fine so far with Django==3.0.2 .

**Comment by jkimbo** [comment]
@dvf yep Django 3 did remove all the six imports but graphene-Django has automated tests that run against v3 and they work fine. @Miraliu ’s suggestion seems sounds like it’s worth trying @a-c-sreedhar-reddy

**Comment by BossGrand** [comment]
I also had a break because of six, but upgrading my graphene-django to 2.8.0 fixed it for me. I also had to update another dependency.

**Comment by BossGrand** [comment]
Update:
What I have found is that graphiql breaks because of this line
https://github.com/graphql-python/graphene-django/blob/b8a2d5953a32c3bbd31fd7799271e879384ca000/graphene_django/views.py#L5

**Comment by jkimbo** [comment]
@BossGrand you should still be able to import six since graphene-django has an explicit dependency on it: https://github.com/graphql-python/graphene-django/blob/master/setup.py

V2 of Graphene Django still supports Python 2 so six is required.

**Comment by BossGrand** [comment]
Ah gotcha thanks @jkimbo will try again

**Comment by beraiarezo** [comment]
upgrade graphql_jwt version to 0.3.0 verion,  I had same problem and solved by run this command try
`pip install "django-graphql-jwt>=0.3.0"`

**Comment by dperetti** [comment]
@jkimbo :
> @BossGrand you should still be able to import six since graphene-django has an explicit dependency on it: https://github.com/graphql-python/graphene-django/blob/master/setup.py#L59
> 
> V2 of Graphene Django still supports Python 2 so six is required.

If `six` is required, shouldn't this be enforced in `setup.py`?
