### ISSUE TITLE
Any example for round trip (N+1) problem solution with Relay & filter ?

### ISSUE THREAD

**Issue by zayazayazaya** [graphql-python/graphene-django#846]

**Comment by zayazayazaya** [comment]
Anyone please provide me example that resolves N+1 with relay using Batching & Cache?

**Comment by cb360** [comment]
me too

**Comment by pollaro** [comment]
You can try and use the [Dataloader](https://docs.graphene-python.org/en/latest/execution/dataloader/).

**Comment by frankchen211** [comment]
[Django + GraphQL. Solving N+1 Problem using DataLoaders](https://apirobot.me/posts/django-graphql-solving-n-1-problem-using-dataloaders)

You can try this, but for 1-n relationship it seems not working #909
