### ISSUE TITLE
Add custom header support to GraphiQL

### ISSUE THREAD

**Issue by MythicManiac** [graphql-python/graphene-django#850]
Related issue: https://github.com/graphql/graphiql/issues/500

GraphiQL by default does not implement a way to pass custom request headers, which are still fairly commonly used for example by authentication middleware. It would be nice if graphene-django's built-in GraphiQL view had support for doing authenticated requests with custom HTTP headers.

**Comment by francoisihry** [comment]
Yes, without being able to customize the headers, it's not possible to test JWT authentication

**Comment by jkimbo** [comment]
This seems like a good enhancement. If anyone wants to contribute a PR for this that would be very helpful.

**Comment by radekwlsk** [comment]
@MythicManiac @jkimbo Hey, I've prepared PR #1016 that adds support for headers introduced to 
`graphiql` https://github.com/graphql/graphiql/pull/1543

**Comment by shaozi** [comment]
How to enable GRAPHIQL_HEADER_EDITOR_ENABLED if I am not using Django?

**Comment by ulgens** [comment]
> How to enable GRAPHIQL_HEADER_EDITOR_ENABLED if I am not using Django?

This is `graphene-django` repository. I'm not sure why would you want to use this tool without Django.

**Comment by shaozi** [comment]
haha, my bad. I found my answer in the flask repo. Thanks!

**Comment by wrosko** [comment]
> haha, my bad. I found my answer in the flask repo. Thanks!

@shaozi sorry to bring this up almost a year later. Where can this be done for graphene/flask?

**Comment by shaozi** [comment]
You can download the latest graphiql and make it a template (almost without any changes), then pass it to the app:
```python
GraphQLView.as_view("graphql", schema=schema, graphiql=True,
                                         graphiql_version='1.0.5',
                                         graphiql_template=template,
                                         graphiql_html_title='Graphql-Dev')
```
