### ISSUE TITLE
All queries are firing a second request

### ISSUE THREAD

**Issue by jdgreenberger** [graphql-python/graphene-django#855]
I'm not totally sure when this problem emerged, but it appears as though Graphene Django is generating a second duplicate request. I'm using Django 3. Here are the steps I've taken to debug:

1. Established that only one http request is sent to my Django server, yet resolvers are fired twice.
2. Set the `graphql` url to point to a custom view that subclasses GraphQLView. When I immediately return from the `dispatch` method, there is only one request processed.
3. If I switch to return the superclass GraphQLView.dispatch, two requests are processed.
4. If I set the `graphql` url to point directly to the lib GraphQLView and add print statements in the source code, I see two request objects processed in the dispatch method.

Do you have any idea what's happening? My best guess based on the above steps would be that graphene is somehow triggering another duplicate request.

**Comment by jkimbo** [comment]
@jdgreenberger that sounds odd. Can you create a reproduction of the issue so that I can test it?

**Comment by jdgreenberger** [comment]
@jkimbo I wasn't able to get a replication using a test environment, and I, unfortunately, don't have time right now to step by step rebuild our production settings. But it appears as though the second request only fires when the django debug toolbar is enabled. Would that be expected behavior? I'll close for now, since there is a solution. But this problem does appear specific to using the GraphQL view (e.g. I don't get double requests when returning JSON from a regular django view).

**Comment by jkimbo** [comment]
Interesting, sounds like it's an issue related to the django debug toolbar then though I'm sure what it could be. If you get a chance to dig into it more please update this thread.
