### ISSUE TITLE
Cookbook example requirements file needs updating

### ISSUE THREAD

**Issue by airstrike** [graphql-python/graphene-django#857]
Running pip install -r requirements.txt on the cookbook example results in an error due to stale dependencies. 

See
https://github.com/graphql-python/graphene-django/blob/62ecbae61449c080d0651895840dea1ed079cf0a/examples/cookbook/requirements.txt#L3

`graphql-relay 2.0.1 has requirement graphql-core<3,>=2.2 but you'll have graphql-core 3.0.2 which is incompatible.`

Same message for graphene 2.1.8

**Comment by jkimbo** [comment]
Thanks for raising this issue @airstrike . Should be fixed in https://github.com/graphql-python/graphene-django/pull/861
