### ISSUE TITLE
This will break/lead to not working tests if your endpoint is not '/graphql'

### ISSUE THREAD

**Issue by easherma** [graphql-python/graphene-django#866]
https://github.com/graphql-python/graphene-django/blob/b66a3f347947804d0ab7d9763309e2977b5bcd5a/graphene_django/utils/testing.py#L12

**Comment by jkimbo** [comment]
True. Though I’m not sure how best to improve it. Any suggestions? You can always override the value in the subclass.

**Comment by easherma** [comment]
I think worse case, a note in the docs would help. I could probably put a PR for that in sometime soon.

Fancy solution could be getting it from the app settings or URL of the app? That could be more trouble than it would be worth, though.

**Comment by jkimbo** [comment]
@easherma If you are able to create a or to update the docs that would be great. I’ll leave this issue open as a bug. (And I agree I don’t think it’s worth trying to determine the url automatically)

**Comment by syberen** [comment]
Also the URL in the `GraphQLTestCase` by default includes a trailing slash, while the example in the installation docs doesn't.

Happy to open a PR to change either one of them, if there is a consensus on the trailing slash. 

Would also be happy to add docs showing an example on how to subclass and use a different endpoint altogether, but I think testing should work "out of the box", using the examples in the docs.

**Comment by ulgens** [comment]
@syberen I think the one in the code is okay. If you have time for a PR, please proceed, thank you :slightly_smiling_face:

**Comment by syberen** [comment]
@ulgens Sure!
