### ISSUE TITLE
Need custom fields in the graphql response on the basis of db values

### ISSUE THREAD

**Issue by monikadixit** [graphql-python/graphene-django#872]
Hi , I have table which has totalCpuCount, diffCount, wisbCount, totalRequests etc etc (CapacityModel) per day basis for each application , I need to calculate the avg of the day and return the response in the custom fields. I cant store these custom field in the db 

Basically in the response I get the list of node for each application (per date) but I want the average for the day. 

schema.py
```python
class CapacityNode(DjangoObjectType):
    deltas = generic.GenericScalar()
    class Meta:
        model = CapacityModel
        filter_fields = ['date', 'type', 'name', 'app']
        interfaces = (relay.Node,)


class Query(ObjectType):    
    capacity = relay.Node.Field(CapacityNode)
    all_capacity = DjangoFilterConnectionField(CapacityNode)
```

I need response something like 

```
{
  "data": {
    "allCapacity": {
      "edges": [
        {
          "node": {
            "date": "2019-10-12",
            "avgTotalCpuCount": 11716,
            "avgDiffCount": -1375,
            "avgWisbCount": 2808,
            "avgTotalRequests": 247927
            "avgSkynetDefineInDnsCount": 1430,
            "avgCmsNonGenesisCount": 1547,
            "avgPoolCount": 10,}
		  }
		}
      ]
	}
  }
}
```

**Comment by jkimbo** [comment]
@monikadixit you can define custom fields and resolvers on your `CapacityNode` type to calculate the data you want. The Graphene documentation is here: https://docs.graphene-python.org/en/latest/types/objecttypes/#quick-example

So in your example you can do:

```python
class CapacityNode(DjangoObjectType):
	avgTotalCpuCount = Int()

	def resolve_avgTotalCpuCount(node, info):
		# Calculate the average cpu count...

    class Meta:
        model = CapacityModel
        filter_fields = ['date', 'type', 'name', 'app']
        interfaces = (relay.Node,)
```

**Comment by monikadixit** [comment]
Hi thanks for your reply. 
This is not solving my issue because I want to loop through the list and calculate the avg, but in this case it will resolve the avgTotalCpuCount for each node. 

That's also fine , if I can calculate the avg , I am not able to define global variable to use calcualte it 

I have tried to use resolverinfo object but no use 

def resolve_avgTotalCpuCount(self, node ):
        node.context.__dict__['totalCpuCount'] = node.context.__dict__['totalCpuCount'] + 
   self.__dict__['total_cpu_count']
        print("node......." , node.context.__dict__['_body'])
        return

**Comment by zbyte64** [comment]
If you want an average accross all nodes then the method should be defined at the `Query` class level.

**Comment by monikadixit** [comment]
could you please give any example ?

**Comment by monikadixit** [comment]
I was able to resolve this , 

`class avgCapacityNode(ObjectType):
    avgCpu=graphene.Float()
    avgWisb = graphene.Float()

class Query(ObjectType):

    extra_field = graphene.Field(avgCapacityNode, date=graphene.String(), manager=graphene.String())

    def resolve_extra_field(self, info, **kwargs):
        date = kwargs.get('date', None)
        manager =kwargs.get('manager', None)
        # manager =kwargs.get('manager', None)
        print(date)
        if date:
            avgCpu = CapacityModel.objects.filter(date = date).filter(manager = manager).aggregate(Avg('wisb') )
            avgWisb = CapacityModel.objects.filter(date = date).aggregate(Avg('total_requests') )
            avgCapacityNode.avgCpu = avgCpu['wisb__avg']
            avgCapacityNode.avgWisb = avgWisb['total_requests__avg']
            return avgCapacityNode
        else:
            avgCpu = CapacityModel.objects.filter(date = '2019-10-02').aggregate(Avg('wisb') )
            avgWisb = CapacityModel.objects.filter(date = '2019-10-02').aggregate(Avg('total_requests') )
            avgCapacityNode.avgCpu = avgCpu['wisb__avg']
            avgCapacityNode.avgWisb = avgWisb['total_requests__avg']
            return avgCapacityNode`
