### ISSUE TITLE
Improvements / Bug Fixes

### ISSUE THREAD

**Issue by nickhudkins** [graphql-python/graphene-django#88]
Hey @syrusakbary I've got some time over the next few weeks and would love to get some of these PRs merged, and issues resolved. 

Anything that I can do to help out here?

**Comment by fmartins** [comment]
@nickhudkins 

I am working on this issues bellow and any help is welcome :+1: 

https://github.com/graphql-python/graphene-django/issues/89
https://github.com/graphql-python/graphene-django/issues/79
https://github.com/graphql-python/graphene/issues/385
