### ISSUE TITLE
Argument for a mutation from set of choices.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [graphql-python/graphene-django#887]
If there is model with one of its field as a CharField and takes values from a choice.
How can a mutation be created so that one of its arguement is one of the choice?

**Comment by radekwlsk** [comment]
I think you mean enums. The mutation Argument should be of Enum type .

Have a look here on how Graphene-Django can convert Django choices to GraphQL enums: http://docs.graphene-python.org/projects/django/en/latest/queries/#choices-to-enum-conversion

And here for general docs on enums in Graphene: https://docs.graphene-python.org/en/latest/types/enums/#enums
