### ISSUE TITLE
ModuleNotFoundError: No module named 'graphene_django'

### ISSUE THREAD

**Issue by ManuBoca92** [graphql-python/graphene-django#897]
Hi guys,
Please I need your help. I am trying to use this module but I keep getting errors. I think it might be a bug with the dependencies, but not sure. Please see my setup

`requirements.txt` file
```
Django==3.0.4
django-filter==2.2.0
django-graphiql==0.4.4
graphene==2.1.8
graphene-django==2.8.2
pylint==2.4.4
yapf==0.29.0
```

`settings.py` file
```
INSTALLED_APPS = [
   'company',
   'graphene_django',
]

GRAPHENE = {
    'SCHEMA': 'startupql.schema.schema' 
```
My `schema.py` file is inside both my django project `startupql` and  django app `company`

I have tried to find the solution and searched for similar issues but couldn't resolve it. Please help! I am using `python 3.8.1` in my venv.

**Comment by SmileyChris** [comment]
I set up a temp venv and installed your requirements. graphene_django is found just fine. Did you actually pip install again after adding those requirements? 
```
# pew mktmpenv
# pip install -r requirements.txt
# python
>>> from django.conf import settings
>>> settings.configure()
>>> import graphene_django
>>> graphene_django.DjangoObjectType
<DjangoObjectType meta=<ObjectTypeOptions name='DjangoObjectType'>>
```

This is a configuration issue at your end, not an issue with this library. Try asking #django on irc or stackoverflow.

**Comment by ManuBoca92** [comment]
Yes you are right, it was a probem with my env. I removed my old env, created a new one and reinstalled requirements and it works now. Thanks very much.

**Comment by Kayumba288** [comment]
thank you SmileyChris for your support response, you help me much for the same problem as  ManuBoca92
