### ISSUE TITLE
iterable gets refiltered by resolve_queryset but iterable might be promise

### ISSUE THREAD

**Issue by frankchen211** [graphql-python/graphene-django#909]
I'm trying to use DataLoader but I got a problem in DjangoConnectionField.
According to the comment, does that means I can't DataLoader here?  My iterable here is Promise.

https://github.com/graphql-python/graphene-django/blob/0da06d4d54d3e73d43d88534259f55733ab7609b/graphene_django/fields.py#L176

**Comment by ayyoubelamrani4** [comment]
@frankchen211 did you find a way to solve this properly?
