### ISSUE TITLE
Problem with GraphQLTestCase

### ISSUE THREAD

**Issue by fneitzel** [graphql-python/graphene-django#917]
I have the following test, following the tutorial:

```
    def test_query(self):
        response = self.query('''
            query{
                links{
                    id
                    description
                    url
                }
            }
        ''',
        op_name='links'
        )

        print(response.content)
        content = json.loads(response.content)

        # This validates the status code and if you get errors
        self.assertResponseNoErrors(response)
```
**Using the same query in GraphiQL GUI returns data as expected.**

But I always receive this error:

> Traceback (most recent call last):
>   File "/<project>/databases/links/tests.py", line 34, in test_query
>     content = json.loads(response.content)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
> 
> response.content is:
> b'\n<!doctype html>\n<html lang="en">\n<head>\n  <title>Not Found</title>\n</head>\n<body>\n  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>\n</body>\n</html>\n'

I use graphene-django 2.9

Can anybody hint what I do wrong?

**Comment by fneitzel** [comment]
AH! I found my problem:

the tutorial assumes:

GRAPHQL_URL = '/graphql/'

but in my case it is:

GRAPHQL_URL = '/links/graphql/'

Could that be added to the tutorial please.

**Comment by 13shreya** [comment]
we can overwrite GRAPHQL_URL by this GraphQLTestCase.GRAPHQL_URL = "new_url"
