### ISSUE TITLE
Date type not accepting ISO DateTime string.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [graphql-python/graphene-django#943]
This causes error
![Screenshot from 2020-04-21 10-55-09](https://user-images.githubusercontent.com/16081083/79829710-71d60680-83c1-11ea-8ac7-a56c53760752.png)
But this works fine
![Screenshot from 2020-04-21 10-55-54](https://user-images.githubusercontent.com/16081083/79830046-3a1b8e80-83c2-11ea-8715-77b23497d7f6.png)

Is it a bug or feature?

**Comment by jkimbo** [comment]
@a-c-sreedhar-reddy this is expected: If you are expecting datetimes as inputs then you need to use the DateTime type.
