### ISSUE TITLE
How to create a reusable/inherited Mutation class in Graphene?

### ISSUE THREAD

**Issue by haquebd** [graphql-python/graphene-django#950]
I have a large project with 1000 new Models. I need to create individual Mutations for each of them. I am looking for a solution to create a Parent Class and inherit that to create each Mutations with different Models attributes. Is it possible and how? Can anyone share an example?

**Comment by zbyte64** [comment]
Yes inheritance works with the mutation class. The form mutation is an example: https://github.com/graphql-python/graphene-django/blob/master/graphene_django/forms/mutation.py
