### ISSUE TITLE
Include FilePathField to convert_field_to_string

### ISSUE THREAD

**Issue by YuryBecker** [graphql-python/graphene-django#96]
Seems like this one was forgotten?

I got the "Don't know how to convert to Django field" error so I looked in the converter and sure enough
that field wasn't there.

Perhaps there is a more complex reason why it's not there?

**Comment by funkjunky** [comment]
https://github.com/graphql-python/graphene-django/pull/366

**Comment by mvanlonden** [comment]
Fixed here https://github.com/graphql-python/graphene-django/pull/366#issuecomment-394869564
