### ISSUE TITLE
GraphiQL not loading when using Uvicorn ASGI

### ISSUE THREAD

**Issue by ccsv** [graphql-python/graphene-django#963]
* **What is the current behavior?**
When running the site using Uvicorn the graphiql page does not load but the rest of the Django site works fine

```
[32mINFO[0m:     127.0.0.1:52463 - "GET /static/graphene_django/graphiql.js HTTP/1.1" 404
Not Found: /static/graphene_django/graphiql.js
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

1) Install Django with a graphene endpoint and Uvicorn

2) Run `uvicorn MYSITE.asgi:application` in the command line replacing MYSITE with your site name

3) Navigate to the Graphene endpoint (graphiql terminal page)

4) Check the command line output

* **What is the expected behavior?**

Expected behavior should be the same as when running `python manage.py runserver` you get a POST for the graphql

```
[13/May/2020 19:53:01] "GET /static/graphene_django/graphiql.js HTTP/1.1" 200 2958
[13/May/2020 19:53:01] "POST /graphql/ HTTP/1.1" 200 24772
```

* **What is the motivation / use case for changing the behavior?**

Making graphene-django compatible with ASGI

* **Please tell us about your environment:**
  
  - Version:  Python 3.82

asgiref==3.2.7
Django==3.0.5
django-graphiql==0.4.4
graphene==2.1.8
graphene-django==2.9.0
uvicorn==0.11.3

  - Platform: Windows 10

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow)

Posted Stackoverflow question a month ago [here](https://stackoverflow.com/questions/61286482/django-graphene-graphiql-page-not-loading-when-running-from-uvicorn) with no answer so I suspect it is a bug

**Comment by jkimbo** [comment]
@ccsv have you run `./manage.py collectstatic`?

**Comment by EverWinter23** [comment]
On the GraphiQL page open `console` and check the requests that it makes-- does it return the js/css static files? If not use @jkimbo suggestion.

**Comment by mrcyme** [comment]
@ccsv did you find a solution ? I am facing the same problem and couldn't find any solution.
Thanks

**Comment by mnasiri** [comment]
fix same issue [here](https://github.com/graphql-python/graphene-django/pull/1460) in new versions
