### ISSUE TITLE
Missing or empty only_fields defaults to all fields

### ISSUE THREAD

**Issue by sdcooke** [graphql-python/graphene-django#97]
If you don't include `only_fields` on `Meta` by default all fields will be included on a `DjangoObjectType`.

Sometimes you want to have a `DjangoObjectType` and manually define any fields you need and there is no way to stop this behaviour - I would have assumed `only_fields = ()` would default to no fields, but it doesn't.

As a workaround I've added `only_fields = ('something_that_is_not_a_field_name',)` but I thought I'd raise here in case others were having similar issues.

**Comment by mvanlonden** [comment]
@camgunz or @sdcooke could either of you create a PR that respects `only_fields = ()` or `only_fields = []`?
